TEXTS_DE = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "Datei",
    "menu.file.open":               "EXE \u00f6ffnen\u2026",
    "menu.file.save_as":            "Speichern unter\u2026",
    "menu.file.quit":               "Beenden",
    "menu.tools":                   "Werkzeuge",
    "menu.tools.details":           "\u00c4nderungen / Details\u2026",
    "menu.tools.export":            "Strings exportieren\u2026",
    "menu.tools.import":            "Strings importieren\u2026",
    "menu.tools.autotranslate":     "Automatische \u00dcbersetzung",
    "menu.tools.translate_all":     "Alle Strings \u00fcbersetzen\u2026",
    "menu.view":                    "Ansicht",
    "menu.view.strings":            "Strings",
    "menu.view.fonts":              "Font-Editor",
    "menu.view.settings":           "Editor-Einstellungen",
    "menu.view.language":           "Sprache",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "\U0001f4c1 EXE ausw\u00e4hlen\u2026",
    "header.save_as":               "\U0001f4be Speichern unter\u2026",
    "header.profile":               "Profil:",
    "header.profile_none":          "\u2014",
    "header.no_file":               "Keine Datei geladen.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  \U0001f4dd Strings  ",
    "tab.fonts":                    "  \U0001f524 Font-Editor  ",
    "tab.settings":                 "  \u2699 Editor-Einstellungen  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "\U0001f50d Suche:",
    "filter.toggle_closed":         "Filter \u25b8",
    "filter.toggle_open":           "Filter \u25be",
    "filter.kind":                  "Art:",
    "filter.font":                  "Font:",
    "filter.change":                "\u00c4nderung:",
    "filter.status":                "Status:",
    "filter.reset":                 "\u274c Filter zur\u00fccksetzen",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Offset",
    "col.text":                     "Stringtext",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Text bearbeiten (Leerzeichen hervorgehoben) ",
    "edit.apply":                   "\u2714 \u00c4nderung \u00fcbernehmen",
    "edit.stats":                   "Gesamtl\u00e4nge: {n} Zeichen | F\u00fchrende Leerzeichen: {lead} | Nachfolgende Leerzeichen: {trail}",
    "edit.encoding_blocked":        "Kodierung blockiert: {error}",
    "edit.diff_unavailable":        "Diff-Status nicht verf\u00fcgbar: {error}",
    "edit.fixed_rest":              "Fixed-Rest: {rest}/{cap} Bytes",
    "edit.block_rest":              "Gemeinsamer Rest B{block} nach allen \u00c4nderungen: {rest} Bytes",
    "edit.block_preview":           "B{block} gemeinsamer Rest: Vorschau erforderlich",
    "edit.range_info":              "{kind} | {font} | Bytes {old}\u2192{new} (\u0394 {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "\U0001f310 \u00dcbersetzung",
    "action.details":               "\U0001f50e \u00c4nderungen / Details\u2026",
    "action.export":                "\U0001f4e4 Exportieren\u2026",
    "action.import":                "\U0001f4e5 Importieren\u2026",
    "action.font_assign":           "Font-Zuordnung\u2026",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Engine:",
    "tr.from":                      "Von:",
    "tr.to":                        "Nach:",
    "tr.all":                       "\u26a1 Alle \u00fcbersetzen",
    "tr.translated":                "\u00dcbersetzter Text:",
    "tr.apply":                     "\u2714 \u00dcbersetzung \u00fcbernehmen",
    "tr.translating":               "\u00dcbersetze...",
    "tr.error":                     "Fehler: {error}",
    "tr.no_changes":                "Keine \u00c4nderung zu \u00fcbernehmen.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Zeichenzuordnung (CharMap) ",
    "settings.font_group":          " Font-Zuordnung ",
    "settings.font_auto":           "Die Zuordnung erfolgt automatisch.\nEine abweichende Auswahl gilt nur f\u00fcr den\naktuell gew\u00e4hlten String.",
    "settings.font_label":          "Zugeordneter Font:",
    "settings.hint_group":          " Speicherverhalten ",
    "settings.hint_text":           "CharMap- und Font-Zuordnungen werden sofort\nund automatisch gespeichert.\n\nDie EXE selbst wird erst \u00fcber\n\u201eDatei \u2192 Speichern unter\u2026\u201c geschrieben.",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} von {total} Strings",
    "status.filter_pending":        "Filteransicht wartet \u2014 \u00c4nderung zuerst \u00fcbernehmen oder verwerfen.",
    "status.selection_blocked":     "Auswahlwechsel blockiert \u2014 \u00c4nderung zuerst \u00fcbernehmen oder verwerfen.",
    "status.filter_unavailable":    "Filter nicht verf\u00fcgbar: {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Nicht \u00fcbernommene Text\u00e4nderung",
    "dlg.pending_font.msg":         "\u00dcbernehmen oder verwerfen Sie die offene Text- oder \u00dcbersetzungs\u00e4nderung, bevor Sie den zugeordneten Font wechseln.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.pending_charmap.msg":      "\u00dcbernehmen oder verwerfen Sie die offene Text- oder \u00dcbersetzungs\u00e4nderung, bevor Sie die CharMap \u00e4ndern.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.pending_translation.title": "Nicht \u00fcbernommene \u00dcbersetzung",
    "dlg.pending_translation.switch": "Offene \u00dcbersetzung \u00fcbernehmen, bevor die automatische \u00dcbersetzung ausgeschaltet wird?\n\nJa = \u00dcbernehmen, Nein = Verwerfen, Abbrechen = Offen lassen",
    "dlg.pending_translation.new":  "\u00dcbernehmen oder verwerfen Sie die offene \u00dcbersetzung, bevor Sie eine neue anfordern.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.text_blocked.title":       "Text\u00e4nderung blockiert",
    "dlg.text_blocked.translation": "\u00dcbernehmen oder verwerfen Sie die offene \u00dcbersetzung, bevor Sie die Text\u00e4nderung \u00fcbernehmen.\n\nEs wurde nichts ge\u00e4ndert.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "Alle \u00fcbersetzen",
    "dlg.translate_all.none":       "Kein String geladen.",
    "dlg.translate_all.confirm":    "Alle {n} Strings automatisch mit '{engine}' \u00fcbersetzen?",
    "dlg.translate_all.window":     "\u00dcbersetze alle...",
    "dlg.translate_all.progress":   "{current}/{total}: {text}",
    "dlg.translate_all.blocked":    "Alle \u00fcbersetzen blockiert",
    "dlg.translate_all.unchanged":  "Kein Text ge\u00e4ndert. Die EXE wurde nicht neu gepackt und bleibt unver\u00e4ndert.",
    "dlg.translate_all.nochange":   "Es wurden weder Text noch EXE-Daten ge\u00e4ndert.\n\n{detail}",
    "dlg.translate_all.done":       "Abgeschlossen",
    "dlg.translate_all.summary":    "Fertig: {translated} \u00fcbersetzt, {unchanged} unver\u00e4ndert, {blank} leer.",
    "dlg.translate_all.suffix":     "\n{n} Suffix-Gruppeneintr\u00e4ge sicher \u00fcbersprungen.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Export blockiert",
    "dlg.export.failed":            "Export fehlgeschlagen",
    "dlg.export.partial":           "Es wurde keine unvollst\u00e4ndige Exportdatei geschrieben.\n\n{error}",
    "dlg.export.done":              "Export abgeschlossen",
    "dlg.export.done_msg":          "{n} Strings exportiert.\n\n{path}",
    "dlg.export.status":            "{n} Strings nach {file} exportiert.",
    "fd.export":                    "Strings exportieren",
    "dlg.import.blocked":           "Import blockiert",
    "dlg.import.nochange":          "Es wurde kein Editorzustand ge\u00e4ndert.\n\n{error}",
    "dlg.import.done":              "Import abgeschlossen",
    "dlg.import.none":              "Profil: {profile}\nGe\u00e4nderte Strings: 0\n\nEs wurde kein Editorzustand ge\u00e4ndert.",
    "dlg.import.confirm":           "Profil: {profile}\nZu \u00e4ndernde Strings: {n}\n\nDie vollst\u00e4ndige validierte Import-Transaktion anwenden?",
    "dlg.import.title":             "Strings importieren",
    "dlg.import.done_msg":          "Profil: {profile}\nGe\u00e4nderte Strings: {n}\n\nDie EXE wurde nicht automatisch gespeichert.",
    "dlg.import.status":            "{n} Strings importiert.",
    "fd.import":                    "Strings importieren",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "\u00c4nderungen / Vorschau \u2014 {profile}",
    "dlg.preview.warn":             "Vorschau",
    "dlg.preview.load_first":       "Laden Sie zuerst eine unterst\u00fctzte EXE.",
    "dlg.preview.failed":           "Vorschau fehlgeschlagen",
    "dlg.preview.close":            "Schlie\u00dfen",
    "preview.tab.summary":          "\u00dcbersicht",
    "preview.tab.strings":          "Strings",
    "preview.tab.blocks":           "Bl\u00f6cke",
    "preview.tab.pointers":         "Pointer",
    "preview.tab.fonts":            "Fonts",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Ausf\u00fchrbare Datei \u00f6ffnen",
    "fd.save_exe":                  "Ausf\u00fchrbare Datei speichern unter",
    "dlg.load.failed":              "Laden fehlgeschlagen",
    "dlg.load.failed_msg":          "Die neue EXE wurde nicht geladen. Der bisherige Editorzustand bleibt unver\u00e4ndert.\n\n{error}",
    "dlg.load.unsupported_status":  "Nicht unterst\u00fctzte EXE. Bearbeiten und Speichern sind deaktiviert.",
    "dlg.load.unsupported_label":   "UNSUPPORTED",
    "dlg.load.font_failed":         "Font-Initialisierung fehlgeschlagen. Speichern ist blockiert.",
    "dlg.load.integrity_status":    "Integrit\u00e4tspr\u00fcfung fehlgeschlagen: {error}",
    "dlg.load.integrity_title":     "Integrit\u00e4tspr\u00fcfung fehlgeschlagen",
    "dlg.load.integrity_msg":       "Die Bearbeitung kann gepr\u00fcft werden, Repack und Speichern sind aber blockiert.\n\n{errors}",
    "dlg.unsaved.title":            "Nicht gespeicherte \u00c4nderungen",
    "dlg.unsaved.load":             "Die aktuelle EXE hat nicht gespeicherte oder offene \u00c4nderungen.\n\nVerwerfen und eine andere Datei laden?",
    "dlg.unsaved.close":            "Die aktuelle EXE hat nicht gespeicherte oder offene \u00c4nderungen.\n\nVerwerfen und den Editor schlie\u00dfen?",
    "dlg.save.unsupported":         "Nicht unterst\u00fctzt",
    "dlg.save.unsupported_msg":     "Laden Sie vor dem Speichern eine unterst\u00fctzte EXE.",
    "dlg.save.blocked":             "Speichern blockiert",
    "dlg.save.verify":              "Die geladene Quelle konnte nicht gepr\u00fcft werden: {error}",
    "dlg.save.external":            "Die geladene Quelldatei wurde au\u00dferhalb des Editors ge\u00e4ndert. Sie wurde nicht \u00fcberschrieben.",
    "dlg.save.done":                "Speichern abgeschlossen",
    "dlg.save.noop":                "Die Originaldatei ist bereits byteidentisch und unver\u00e4ndert.",
    "dlg.save.overwrite_title":     "Geladenes Original \u00fcberschreiben",
    "dlg.save.overwrite_msg":       "Das geladene Original durch die bearbeitete EXE ersetzen?\n\nZuvor wird eine byteidentische Sicherung angelegt.",
    "dlg.save.failed":              "Speichern fehlgeschlagen",
    "dlg.save.failed_msg":          "Es wurde keine unvollst\u00e4ndige Zieldatei geschrieben.\n\n{error}",
    "dlg.save.done_msg":            "EXE gespeichert unter:\n{path}{backup}",
    "dlg.save.backup":              "\nSicherung: {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "Eine erfolgreiche Repack-Validierung ist erforderlich.",
    "block.font_invalid":           "Die Fontvalidierung ist fehlgeschlagen.",
    "block.font_pending":           "\u00dcbernehmen oder verwerfen Sie die offenen Font\u00e4nderungen vor dem Speichern.",
    "block.text_pending":           "\u00dcbernehmen oder verwerfen Sie die offene Text\u00e4nderung vor dem Speichern.",
    "block.generic":                "Speichern ist derzeit blockiert.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Font:",
    "font.apply":                   "\u00c4nderungen \u00fcbernehmen",
    "font.load_first":              "Laden Sie zuerst eine EXE.",
    "font.characters":              " Zeichen ",
    "font.matrix":                  " Pixelmatrix (Klicken/Ziehen) ",
    "font.props":                   " Eigenschaften ",
    "font.width":                   "Breite (px):",
    "font.tools":                   " Werkzeuge ",
    "font.copy":                    "\U0001f4cb Kopieren",
    "font.paste":                   "\U0001f4cc Einf\u00fcgen",
    "font.clear":                   "\U0001f9f9 Leeren",
    "font.invert":                  "\U0001f504 Invertieren",
    "font.file":                    " Datei ",
    "font.import":                  "\U0001f4e5 Import",
    "font.export":                  "\U0001f4e4 Export",
    "font.edit_charmap":            "Zeichenzuordnung bearbeiten\u2026",
    "font.charmap_title":           "Zeichenzuordnung",
    "font.charmap_title_for":       "Zeichenzuordnung {font}:",
    "font.remove":                  "\u2716 Entfernen",
    "font.blocked_title":           "Fontoperation blockiert",
    "font.blocked_status":          "\u2716 Fontoperation blockiert: {error}",
    "font.no_profile":              "Kein Fontprofil f\u00fcr '{profile}'.",
    "font.summary":                 "{font}  \u2022  {chars} Zeichen  \u2022  {unique} eindeutige Glyphen",
    "font.pending_title":           "Offene Font\u00e4nderungen",
    "font.pending_msg":             "Offene \u00c4nderungen an {font} vor dem Wechsel \u00fcbernehmen?\n\nJa = \u00dcbernehmen, Nein = Verwerfen, Abbrechen = Bleiben",
    "font.no_data":                 "Keine Daten",
    "font.no_data_msg":             "Laden Sie eine EXE und w\u00e4hlen Sie zuerst einen Font.",
    "font.no_exe_msg":              "Laden Sie zuerst eine EXE-Datei.",
    "font.fd_export":               "Font exportieren",
    "font.fd_import":               "Font importieren ({font})",
    "font.export_error":            "Exportfehler",
    "font.exported":                "\u2714 {font} exportiert \u2192 {file}",
    "font.imported":                "\u2714 {n} Glyphen aus {file} in {font} importiert",
    "font.written":                 "\u2714 {n} Glyphen in die EXE-Daten geschrieben  ({font})",
    "font.written_title":           "Font geschrieben",
    "font.written_msg":             "{n} eindeutige Glyphen in die EXE-Daten gepatcht.\nZum Speichern \u201eSpeichern unter\u2026\u201c in der Kopfzeile verwenden.",
    "font.no_selection":            "Keine Auswahl",
    "font.no_selection_msg":        "W\u00e4hlen Sie zuerst ein Zeichen.",
    "font.empty_clipboard":         "Zwischenablage leer",
    "font.empty_clipboard_msg":     "Kopieren Sie zuerst ein Zeichen (Strg+C).",
    "font.copied":                  "\u2713 0x{code:02X} '{char}' in die Zwischenablage kopiert",
    "font.pasted":                  "\u2713 Eingef\u00fcgt in 0x{code:02X} '{char}'",
    "font.alias":                   "\u26a0 Alias von 0x{code:02X} ('{char}')\nDas Bearbeiten \u00e4ndert auch das Original.",
    "font.invalid_entry":           "Ung\u00fcltiger CharMap-Eintrag",
    "font.invalid_entry_msg":       "Geben Sie ein Unicode-Zeichen ein.",
    "font.invalid_byte":            "Ung\u00fcltiges CharMap-Byte",
    # font_editor internal messages — not yet translated
    "font.err.live_unavailable":    "No supported font state is loaded",
    "font.err.buffer_unavailable":  "Live EXE buffer is unavailable",
    "font.err.import_failed":       "Import failed without changes: {error}",
    "font.err.apply_failed":        "Apply failed; live data was not changed: {error}",
    "font.err.paste_rejected":      "Paste rejected without changes: {error}",
    "font.err.initial_load":        "Initial font could not be loaded",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Konfiguration",
    "utils.cfg.damaged":            "Die vorhandene Konfiguration ist besch\u00e4digt und wurde nicht ersetzt.\n\u00c4nderungen an der Konfiguration sind gesperrt, bis sie repariert oder entfernt wird.\n\n{reason}",
    "utils.cfg.locked":             "Konfiguration\u00e4nderungen werden nicht gespeichert, solange die vorhandene Konfiguration besch\u00e4digt ist.\n\n{reason}",
    "utils.cfg.save_failed":        "Konfiguration konnte nicht gespeichert werden: {error}",

    # ── build_exe.py — not yet translated ────────────────────────────────────
    "build.err.no_entry":           "Entrypoint missing: {path}",
    "build.err.no_config":          "Config source missing: {path}",
    "build.err.no_icon":            "Icon resource missing: {path}",
    "build.err.pyi_failed":         "PyInstaller failed with exit code {code}",
    "build.err.no_exe":             "Expected executable not produced: {path}",
    "build.err.config_mismatch":    "Release config is not byte-identical to the source",
    "build.err.key_nonempty":       "deepl_key.txt must be empty",
    "build.step.config":            "[1/6] config source  {hash}  {size} B",
    "build.step.icon":              "      icon source    {hash}  {size} B",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] built  {hash}  {size} B",
    "build.step.removed_obsolete":  "      removed superseded release: {name}",
    "build.step.release_exe":       "[4/6] release exe -> {path}",
    "build.step.config_verified":   "[5/6] release config verified  {hash}",
    "build.step.key_file":          "[6/6] release deepl_key.txt  0 B",
    "build.step.release_header":    "\nRelease:",

    # ── translator.py — not yet translated ───────────────────────────────────
    "tr.err.markers_changed":       "Protected translation markers changed (missing={missing}, unexpected={unexpected})",
    "tr.err.marker_count":          "Protected marker count changed: {marker}",
    "tr.err.marker_unrestored":     "Unrestored translation marker remains",
    "tr.err.no_text":               "Translator returned no text",
    "tr.err.lingva_unreachable":    "All servers are inaccessible (403/503). Try Google Translate or MyMemory.",
    "tr.err.mymemory":              "MyMemory error {status}: {detail}",
    "tr.err.deepl_no_key":          "DeepL key not found.\nRegister for free at https://www.deepl.com/pro#developer\nThen save the key in deepl_key.txt.",
    "tr.err.argos_not_installed":   "Argos Translate not installed.\nExecute: pip install argostranslate\nand download the language packs.",
    "tr.err.argos_no_package":      "Argos package '{src}\u2192{tgt}' not installed.\nDownload it with argostranslate.package.",
    "tr.err.argos_no_translation":  "No Argos translation available for {src}\u2192{tgt}.",

    # ── charmap.py — not yet translated ──────────────────────────────────────
    "charmap.err.invalid_key":      "Invalid CharMap byte key: {key}",
    "charmap.err.key_not_one_byte": "CharMap key must identify one byte: {key}",
    "charmap.err.value_not_char":   "CharMap value must be one character: {value}",
    "charmap.err.ambiguous":        "Ambiguous CharMap character: {char}",
    "charmap.err.outside_font":     "Byte 0x{byte:02X} for {char!r} is outside the active font",
    "charmap.err.no_codepoint":     "Character U+{cp:04X} at position {pos} has no CharMap entry",
    "charmap.err.conflict":         "Character {char!r} at position {pos} conflicts with glyph {glyph!r}",

    # ── font_safety.py — not yet translated ──────────────────────────────────
    "fsafe.err.invalid_width":      "Invalid glyph width: {width!r}",
    "fsafe.err.unknown_font":       "Unknown font: {font}",
    "fsafe.err.incomplete_desc":    "Incomplete font description for {font}",
    "fsafe.err.unsupported_type":   "Unsupported font type for {font}",
    "fsafe.err.invalid_row_count":  "Invalid row/pointer count for {font}",
    "fsafe.err.ptr_table_outside":  "Pointer table outside EXE for {font}",
    "fsafe.err.ptr_table_size":     "Pointer table size mismatch for {font}: {got} bytes for {ptrs} pointers",
    "fsafe.err.glyph_range":        "Glyph range outside EXE or overlaps pointer table for {font}",
    "fsafe.err.ptr_target":         "Glyph pointer {idx} for {font} targets {addr:#x} outside {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "First glyph for {font} does not start at glyph_start",
    "fsafe.err.slot_invalid":       "Invalid/overlapping glyph slot at {addr:#x} in {font}",
    "fsafe.err.dynamic_uneven":     "Dynamic glyph slot at {addr:#x} has an uneven row layout",
    "fsafe.err.dynamic_capacity":   "Dynamic glyph slot at {addr:#x} has unsupported capacity {cap}",
    "fsafe.err.width_exceeds_slot": "Glyph width {width} at {addr:#x} exceeds slot capacity {max}",
    "fsafe.err.fixed_size":         "Fixed glyph slot at {addr:#x} has size {got}, expected {expected}",
    "fsafe.err.fixed_width":        "Fixed glyph width {width} at {addr:#x} is invalid",
    "fsafe.err.glyph_exceeds_slot": "Glyph data at {addr:#x} exceeds its physical slot",
    "fsafe.err.model_char_count":   "Font model has {got} characters, expected {expected}",
    "fsafe.err.invalid_char_idx":   "Invalid character index {idx}",
    "fsafe.err.no_glyph_obj":       "Character {idx} has no glyph object",
    "fsafe.err.invalid_glyph_off":  "Character {idx} has an invalid glyph offset",
    "fsafe.err.alias_not_shared":   "Aliases at {addr:#x} do not share one canonical glyph object",
    "fsafe.err.alias_meta":         "Alias metadata mismatch for character {idx}",
    "fsafe.err.glyph_start":        "Font model does not begin at glyph_start",
    "fsafe.err.slot_boundary":      "Slot boundary mismatch at {addr:#x}",
    "fsafe.err.slot_outside_exe":   "Slot at {addr:#x} is outside the EXE",
    "fsafe.err.dynamic_cap_meta":   "Invalid dynamic slot capacity at {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "Stored capacity mismatch at {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "Width/row-class exceeds slot at {addr:#x}",
    "fsafe.err.fixed_slot":         "Invalid fixed slot at {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "Stored fixed capacity mismatch at {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Invalid fixed width at {addr:#x}",
    "fsafe.err.bitmap_value":       "Bitmap value outside row class at {addr:#x}",
    "fsafe.err.serial_exceeds":     "Glyph serialization exceeds slot at {addr:#x}",
    "fsafe.err.bpr_conversion":     "Unsupported bytes-per-row conversion",
    "fsafe.err.width_not_int":      "Width must be an integer",
    "fsafe.err.width_exceeds_max":  "Width {width} exceeds this glyph slot (max {max})",
    "fsafe.err.fixed_width_range":  "FLOW/MICRO width must remain between 1 and 8",
    "fsafe.err.clipboard_invalid":  "Clipboard does not contain a valid glyph",
    "fsafe.err.height_mismatch":    "Incompatible glyph height: source {src}, target {tgt}",
    "fsafe.err.clip_type_invalid":  "Clipboard font type is invalid",
    "fsafe.err.clip_bpr_invalid":   "Clipboard row class is invalid",
    "fsafe.err.clip_fixed_width":   "Clipboard fixed width is invalid",
    "fsafe.err.clip_bitmap":        "Clipboard bitmap is invalid",
    "fsafe.err.target_too_wide":    "Glyph is wider than a FLOW/MICRO target",
    "fsafe.err.paste_exceeds_slot": "Glyph width {width} exceeds target slot capacity {max}",
    "fsafe.err.write_exceeds":      "Glyph write at {addr:#x} exceeds its slot",
    "fsafe.err.ptr_alias_struct":   "Font model no longer matches the EXE pointer/alias structure",
    "fsafe.err.changed_outside":    "Font serialization changed bytes outside glyph slots",
    "fsafe.err.readback_mismatch":  "Font readback mismatch at {addr:#x}",
    "fsafe.err.import_truncated":   "Import is truncated before glyph {idx}",
    "fsafe.err.import_width":       "Imported width {width} exceeds glyph {idx} capacity {cap}",
    "fsafe.err.import_fixed_width": "Imported fixed width {width} is invalid at glyph {idx}",
    "fsafe.err.import_trunc_body":  "Import is truncated inside glyph {idx}",
    "fsafe.err.import_trailing":    "Import has {n} unexpected trailing bytes",
    "fsafe.err.no_dir":             "Target directory does not exist: {dir}",
    "fsafe.err.short_write":        "Short write: {written} of {total} bytes",
    "fsafe.err.readback_tmp":       "Temporary-file readback mismatch",
    "fsafe.err.no_backup_src":      "Cannot back up a missing original file",
    "fsafe.err.buffers_differ":     "Font buffers differ in {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "Font buffers do not have the same pre-commit state",

    # ── diff_preview.py — not yet translated ─────────────────────────────────
    "diff.err.no_raw":              "Entry {sid} does not contain strict raw bytes",
    "diff.err.no_ref_type":         "Entry {sid} has no reference type",
    "diff.err.range_outside":       "Baseline range for {label} is outside the EXE",
    "diff.err.not_nul_term":        "Baseline string {label} is not NUL-terminated",
    "diff.err.ptr_normal_outside":  "Normal pointer source outside EXE: {addr:#x}",
    "diff.err.ptr_code_outside":    "Code pointer source outside EXE: {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Unknown pointer kind: {kind}",
    "diff.err.ptr_base_mismatch":   "Pointer {addr:#x} has base {got}, expected {expected}",
    "diff.err.ptr_outside_ranges":  "Pointer {addr:#x} targets outside Repack ranges: {target:#x}",
    "diff.err.no_unique_sid":       "Current entries do not have unique string_ids",
    "diff.err.fixed_id":            "Invalid fixed string_id: {sid}",
    "diff.err.unknown_fixed_slot":  "Unknown fixed baseline slot: {sid}",
    "diff.err.ambiguous_targets":   "Baseline pointer sources for {sid} have {n} targets",
    "diff.err.baseline_failed":     "Baseline reconstruction failed: {detail}",
    "diff.err.repack_mutated":      "Authoritative Repack dry-run mutated its inputs",
    "diff.err.range_cross_end":     "Repacked string crosses block end at {addr:#x}",
    "diff.err.pending_preflight":   "Unknown pending string_id: {sid}",
    "diff.err.pending_not_bytes":   "Pending replacement for {sid} is not raw bytes",
    "diff.err.fixed_exceed":        "Fixed string {sid} exceeds {max} bytes ({got} bytes)",
    "diff.err.dup_normal_ptr":      "Duplicate normal pointer source: {addr:#x}",
    "diff.err.dup_code_ptr":        "Duplicate code pointer source: {addr:#x}",
    "diff.err.alias_not_canonical": "Aliases at {addr:#x} are not canonical",
    "diff.err.ptr_table_changed":   "Font pointer table changed for {font}",
    "diff.err.glyph_set_changed":   "Physical glyph set changed for {font}",
    "diff.err.alias_set_changed":   "Alias set changed at {addr:#x} in {font}",
    "diff.err.meta_reconstruct":    "String metadata could not be reconstructed: {error}",
    "diff.err.no_font_key":         "Pending font model has no font key",
    "diff.err.font_preview_failed": "Pending font preview failed: {error}",
    "diff.err.sid_sets_differ":     "Baseline/current string_id sets differ",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "Preview mutated baseline_data",
    "diff.err.mutated_current":     "Preview mutated current_data",
    "diff.err.mutated_entries":     "Preview mutated current entries",
    "diff.err.mutated_font":        "Preview mutated the pending font model",
    "diff.err.baseline_repack":     "Baseline Repack failed: {detail}",
    "diff.err.unknown_baseline":    "Unknown baseline validation failure",
    "diff.err.unknown_baseline_repack": "Unknown baseline Repack failure",

    # ── repack_validator.py — not yet translated ──────────────────────────────
    "repack.err.encoding":          "String {sid} contains a character that cannot be encoded",
    "repack.err.site_outside":      "Relocation site outside file: {addr:#x}",
    "repack.err.missing_code_ptrs": "Missing code pointers: {addrs}",
    "repack.err.extra_code_ptrs":   "Unexpected code pointers: {addrs}",
    "repack.err.mismatched_ptrs":   "Mismatched code pointers: {addrs}",
    "repack.err.no_sid":            "Entry at {addr:#x} has no string_id",
    "repack.err.dup_sid":           "Duplicate string_id: {sid}",
    "repack.err.fixed_has_ptrs":    "Fixed entry {sid} unexpectedly has pointers",
    "repack.err.dup_normal_src":    "Duplicate normal pointer source: {addr:#x}",
    "repack.err.uninv_normal_src":  "Uninventoried normal pointer source: {addr:#x}",
    "repack.err.normal_target":     "Normal pointer {src:#x} targets {expected:#x}, entry is {actual:#x}",
    "repack.err.dup_code_src":      "Duplicate code pointer source: {addr:#x}",
    "repack.err.uninv_code_src":    "Uninventoried code pointer source: {addr:#x}",
    "repack.err.code_target":       "Code pointer {src:#x} targets {expected:#x}, entry is {actual:#x}",
    "repack.err.unowned_normal":    "{n} relocation-backed normal pointers are not owned",
    "repack.err.unowned_code":      "{n} relocation-backed code pointers are not owned",
    "repack.err.unknown_fixed":     "Unknown fixed string: {addr:#x}",
    "repack.err.fixed_slot_size":   "Fixed string exceeds slot at {addr:#x}",
    "repack.err.fixed_mismatch":    "Fixed string bytes mismatch at {addr:#x}",
    "repack.err.outside_ranges":    "String outside valid ranges: {addr:#x}",
    "repack.err.crosses_range":     "String crosses range end: {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "String bytes/NUL mismatch at {addr:#x}",
    "repack.err.illegal_overlap":   "Illegal string overlap: {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Unknown occupied bytes in range {idx}: {n} bytes, first {addr:#x}",
    "repack.err.entry_outside":     "Entry outside valid ranges: {addr:#x}",
    "repack.err.range_overflow":    "Range {idx} overflow: {required} > {total}",
    "repack.err.ptr_value_range":   "Pointer value outside 16-bit range: {value:#x}",
    "repack.err.normal_src_file":   "Normal pointer source outside file: {addr:#x}",
    "repack.err.code_src_file":     "Code pointer source outside file: {addr:#x}",
    "repack.err.suffix_chain":      "Unresolved suffix-sharing chain",
    "repack.err.file_size_changed": "File size changed",
    "repack.err.extra_diffs":       "Unexpected changed bytes outside ranges/pointer offsets: {n}, first {addr:#x}",

    # ── string_exchange.py — not yet translated ───────────────────────────────
    "xchg.err.not_serialisable":    "Value cannot be canonicalised: {error}",
    "xchg.err.not_raw_text":        "Entry {sid} does not contain strict raw-byte text",
    "xchg.err.no_ref_type":         "Entry {sid} has no supported reference type",
    "xchg.err.charmap_not_obj":     "CharMap must be an object",
    "xchg.err.invalid_key":         "Invalid CharMap byte key: {key!r}",
    "xchg.err.key_not_one_byte":    "CharMap key must identify one byte: {key!r}",
    "xchg.err.invalid_char":        "Invalid CharMap character: {char!r}",
    "xchg.err.conflict_key":        "Conflicting CharMap key: {key!r}",
    "xchg.err.ambiguous_char":      "Ambiguous CharMap character: {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF cannot be exported as visible text",
    "xchg.err.no_sid":              "Every entry must have a string_id",
    "xchg.err.dup_sid":             "Duplicate string_id in live entries",
    "xchg.err.no_charmap":          "No confirmed CharMap/font codes for {font}",
    "xchg.err.outside_repack":      "Entry {sid} is outside all Repack blocks",
    "xchg.err.unknown_fixed_slot":  "Unknown fixed slot for {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR and LF are not allowed in imported strings",
    "xchg.err.unconfirmed_byte":    "Unconfirmed byte-like character U+{cp:04X} must use \\xNN",
    "xchg.err.trailing_backslash":  "Trailing backslash in exchange text",
    "xchg.err.bad_escape":          "Backslash must be escaped as \\\\ or form \\xNN",
    "xchg.err.nul_byte_escape":     "NUL, CR and LF byte escapes are not allowed",
    "xchg.err.use_visible":         "Byte 0x{byte:02X} must use its confirmed visible representation",
    "xchg.err.new_dup_escape":      "New or duplicated byte escape \\x{byte:02X}",
    "xchg.err.control_token":       "Invalid control token: {token!r}",
    "xchg.err.token_outside_font":  "Control token outside active font: {token!r}",
    "xchg.err.unconfirmed_intro":   "Unconfirmed byte 0x{byte:02X} was introduced or duplicated",
    "xchg.err.not_utf8":            "Import is not valid UTF-8",
    "xchg.err.invalid_json":        "Invalid or truncated JSON: {error}",
    "xchg.err.root_not_obj":        "Exchange document root must be an object",
    "xchg.err.dup_json_key":        "Duplicate JSON key: {key!r}",
    "xchg.err.invalid_constant":    "Invalid JSON numeric constant: {value}",
    "xchg.err.schema_mismatch":     "Top-level schema fields do not match version 1",
    "xchg.err.bad_format":          "Unsupported string exchange format",
    "xchg.err.bad_version":         "Unsupported string exchange version",
    "xchg.err.no_profile_id":       "profile_id must be a non-empty string",
    "xchg.err.bad_entry_count":     "entry_count must be a non-negative integer",
    "xchg.err.entries_not_array":   "entries must be an array",
    "xchg.err.count_mismatch":      "entry_count does not match entries",
    "xchg.err.entry_schema":        "Entry schema fields do not match version 1",
    "xchg.err.no_string_id":        "string_id must be a non-empty string",
    "xchg.err.dup_entry_id":        "Duplicate string_id: {sid}",
    "xchg.err.invalid_kind":        "Invalid kind for {sid}",
    "xchg.err.editable_not_bool":   "editable must be boolean for {sid}",
    "xchg.err.suffix_not_array":    "suffix_links must be an array for {sid}",
    "xchg.err.suffix_link_schema":  "Invalid suffix link schema for {sid}",
    "xchg.err.suffix_role":         "Invalid suffix role for {sid}",
    "xchg.err.suffix_peer":         "Invalid suffix peer for {sid}",
    "xchg.err.suffix_offset":       "Invalid suffix offset for {sid}",
    "xchg.err.no_font":             "Invalid font for {sid}",
    "xchg.err.invalid_block":       "Invalid repack_block for {sid}",
    "xchg.err.invalid_ptr_count":   "Invalid {field} for {sid}",
    "xchg.err.invalid_capacity":    "Invalid fixed capacity for {sid}",
    "xchg.err.bad_hash":            "{field} must be an uppercase SHA-256",
    "xchg.err.source_text_str":     "source_text must be a string for {sid}",
    "xchg.err.translated_type":     "translated_text must be null or string for {sid}",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 does not match entry hashes",
    "xchg.err.wrong_profile":       "Wrong profile: {got!r}, expected {expected!r}",
    "xchg.err.structure_mismatch":  "Profile structure fingerprint mismatch",
    "xchg.err.charmap_mismatch":    "CharMap fingerprint mismatch",
    "xchg.err.entry_count_mismatch": "Import entry count does not match the loaded EXE",
    "xchg.err.missing_sid":         "Missing string_id: {sid}",
    "xchg.err.unknown_sid":         "Unknown string_id: {sid}",
    "xchg.err.manipulated_field":   "Manipulated {field} for {sid}",
    "xchg.err.source_hash":         "source_text/hash mismatch for {sid}",
    "xchg.err.token_mismatch":      "Protected token mismatch for {sid}",
    "xchg.err.layout_mismatch":     "Protected whitespace/layout mismatch for {sid}",
    "xchg.err.read_only":           "Suffix entry is read-only: {sid}",
    "xchg.err.fixed_exceeds":       "Fixed string {sid} exceeds {cap} bytes",
    "xchg.err.stale_conflict":      "Stale source conflict for {sid}",
    "xchg.err.escape_changed":      "Unconfirmed byte escapes changed for {sid}",
    "xchg.err.unknown_sid_replace": "Replacement set contains an unknown string_id",
    "xchg.err.replace_not_bytes":   "Replacement for {sid} is not raw bytes",
    "xchg.err.fixed_exceed_import": "Fixed string {sid} exceeds {max} bytes",
    "xchg.err.repack_blocked":      "Import Repack blocked: {detail}",
    "xchg.err.suffix_changed":      "Import would change suffix-sharing relationships",
    "xchg.err.font_validation":     "Import font validation failed: {error}",
    "xchg.err.unknown_repack":      "Unknown Repack validation failure",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Ungültige Filtermetadaten in Zeile {idx}",
    "sfilter.err.dup_sid":        "Fehlende oder doppelte string_id in Zeile {idx}",
    "sfilter.err.invalid_kind":   "Ungültige String-Art für {sid}: {kind!r}",
    "sfilter.err.invalid_font":   "Ungültiger effektiver Font für {sid}",
    "sfilter.err.invalid_text":   "Ungültiger durchsuchbarer Text für {sid}",
    "sfilter.err.invalid_preview":"Ungültiger Vorschaustatus für {sid}",
    "sfilter.err.invalid_override":"Ungültige Status-Überschreibung für {sid}",
    "sfilter.err.query_not_text": "Suchanfrage muss Text sein",
    "sfilter.err.unknown_kind":   "Unbekannter Art-Filter: {kind!r}",
    "sfilter.err.font_empty":     "Font-Filter muss ein nicht leerer Name sein",
    "sfilter.err.unknown_change": "Unbekannter Änderungs-Filter: {change!r}",
    "sfilter.err.unknown_status": "Unbekannter Status-Filter: {status!r}",
}
