TEXTS_ES = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "Archivo",
    "menu.file.open":               "Abrir EXE…",
    "menu.file.save_as":            "Guardar como…",
    "menu.file.quit":               "Salir",
    "menu.tools":                   "Herramientas",
    "menu.tools.details":           "Cambios / Detalles…",
    "menu.tools.export":            "Exportar cadenas…",
    "menu.tools.import":            "Importar cadenas…",
    "menu.tools.autotranslate":     "Traducción automática",
    "menu.tools.translate_all":     "Traducir todas las cadenas…",
    "menu.view":                    "Ver",
    "menu.view.strings":            "Cadenas",
    "menu.view.fonts":              "Editor de fuentes",
    "menu.view.settings":           "Configuración del editor",
    "menu.view.language":           "Idioma",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "📁 Elegir EXE…",
    "header.save_as":               "💾 Guardar como…",
    "header.profile":               "Perfil:",
    "header.profile_none":          "—",
    "header.no_file":               "No hay ningún archivo cargado.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  📝 Cadenas  ",
    "tab.fonts":                    "  🔤 Editor de fuentes  ",
    "tab.settings":                 "  ⚙ Configuración del editor  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "🔍 Buscar:",
    "filter.toggle_closed":         "Filtrar ▸",
    "filter.toggle_open":           "Filtrar ▾",
    "filter.kind":                  "Tipo:",
    "filter.font":                  "Fuente:",
    "filter.change":                "Cambio:",
    "filter.status":                "Estado:",
    "filter.reset":                 "❌ Restablecer filtros",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Desplazamiento",
    "col.text":                     "Texto de cadena",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Editar texto (espacios resaltados) ",
    "edit.apply":                   "✔ Aplicar cambio",
    "edit.stats":                   "Longitud total: {n} caracteres | Espacios iniciales: {lead} | Espacios finales: {trail}",
    "edit.encoding_blocked":        "Codificación bloqueada: {error}",
    "edit.diff_unavailable":        "Estado de diferencias no disponible: {error}",
    "edit.fixed_rest":              "Espacio fijo restante: {rest}/{cap} bytes",
    "edit.block_rest":              "Espacio compartido de B{block} restante después de todos los cambios: {rest} bytes",
    "edit.block_preview":           "Espacio compartido de B{block}: se requiere vista previa",
    "edit.range_info":              "{kind} | {font} | bytes {old}→{new} (Δ {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "🌐 Traducción",
    "action.details":               "🔎 Cambios / Detalles…",
    "action.export":                "📤 Exportar…",
    "action.import":                "📥 Importar…",
    "action.font_assign":           "Asignación de fuente…",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Motor:",
    "tr.from":                      "Desde:",
    "tr.to":                        "Hasta:",
    "tr.all":                       "⚡ Traducir todo",
    "tr.translated":                "Texto traducido:",
    "tr.apply":                     "✔ Aplicar traducción",
    "tr.translating":               "Traduciendo...",
    "tr.error":                     "Error: {error}",
    "tr.no_changes":                "No hay cambios que aplicar.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Mapeo de caracteres (CharMap) ",
    "settings.font_group":          " Asignación de fuente ",
    "settings.font_auto":           "La asignación es automática.\nUna elección diferente solo se aplica a la\ncadena seleccionada actualmente.",
    "settings.font_label":          "Fuente asignada:",
    "settings.hint_group":          " Comportamiento del guardado ",
    "settings.hint_text":           "Las asignaciones de CharMap y fuente se guardan\ninmediatamente y de forma automática.\n\nEl EXE solo se escribe mediante\n«Archivo → Guardar como…».",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} de {total} cadenas",
    "status.filter_pending":        "La vista del filtro está esperando — aplica o descarta primero el cambio.",
    "status.selection_blocked":     "Cambio de selección bloqueado — aplica o descarta primero el cambio.",
    "status.filter_unavailable":    "Filtro no disponible: {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Cambio de texto pendiente",
    "dlg.pending_font.msg":         "Aplica o descarta el cambio de texto o la traducción pendiente antes de cambiar la fuente asociada.\n\nNo se ha cambiado nada.",
    "dlg.pending_charmap.msg":      "Aplica o descarta el cambio de texto o la traducción pendiente antes de cambiar el CharMap.\n\nNo se ha cambiado nada.",
    "dlg.pending_translation.title": "Traducción pendiente",
    "dlg.pending_translation.switch": "¿Aplicar la traducción pendiente antes de desactivar la traducción automática?\n\nSí = Aplicar, No = Descartar, Cancelar = Mantenerla abierta",
    "dlg.pending_translation.new":  "Aplica o descarta la traducción pendiente antes de solicitar una nueva.\n\nNo se ha cambiado nada.",
    "dlg.text_blocked.title":       "Cambio de texto bloqueado",
    "dlg.text_blocked.translation": "Aplica o descarta la traducción pendiente antes de aplicar el cambio de texto.\n\nNo se ha cambiado nada.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "TRADUCIR TODO",
    "dlg.translate_all.none":       "No hay ninguna cadena cargada.",
    "dlg.translate_all.confirm":    "¿Traducir automáticamente las {n} cadenas con '{engine}'?",
    "dlg.translate_all.window":     "Traduciendo TODO...",
    "dlg.translate_all.progress":   "{current}/{total}: {text}",
    "dlg.translate_all.blocked":    "TRADUCCIÓN TOTAL bloqueada",
    "dlg.translate_all.unchanged":  "No se ha cambiado ningún texto. El EXE no se ha vuelto a empaquetar y permanece sin cambios.",
    "dlg.translate_all.nochange":   "No se ha cambiado ningún texto ni dato del EXE.\n\n{detail}",
    "dlg.translate_all.done":       "Completado",
    "dlg.translate_all.summary":    "Completado: {translated} traducidas, {unchanged} sin cambios, {blank} vacías.",
    "dlg.translate_all.suffix":     "\n{n} entradas de grupo de sufijos omitidas de forma segura.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Exportación bloqueada",
    "dlg.export.failed":            "Exportación fallida",
    "dlg.export.partial":           "No se ha escrito ningún archivo de exportación parcial.\n\n{error}",
    "dlg.export.done":              "Exportación completada",
    "dlg.export.done_msg":          "Se han exportado {n} cadenas.\n\n{path}",
    "dlg.export.status":            "Se han exportado {n} cadenas a {file}.",
    "fd.export":                    "Exportar cadenas",
    "dlg.import.blocked":           "Importación bloqueada",
    "dlg.import.nochange":          "El estado del editor no ha cambiado.\n\n{error}",
    "dlg.import.done":              "Importación completada",
    "dlg.import.none":              "Perfil: {profile}\nCadenas modificadas: 0\n\nEl estado del editor no ha cambiado.",
    "dlg.import.confirm":           "Perfil: {profile}\nCadenas a modificar: {n}\n\n¿Aplicar la transacción de importación validada completa?",
    "dlg.import.title":             "Importar cadenas",
    "dlg.import.done_msg":          "Perfil: {profile}\nCadenas modificadas: {n}\n\nEl EXE no se ha guardado automáticamente.",
    "dlg.import.status":            "Se han importado {n} cadenas.",
    "fd.import":                    "Importar cadenas",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "Cambios / Vista previa — {profile}",
    "dlg.preview.warn":             "Vista previa",
    "dlg.preview.load_first":       "Carga primero un ejecutable compatible.",
    "dlg.preview.failed":           "Vista previa fallida",
    "dlg.preview.close":            "Cerrar",
    "preview.tab.summary":          "Resumen",
    "preview.tab.strings":          "Cadenas",
    "preview.tab.blocks":           "Bloques",
    "preview.tab.pointers":         "Punteros",
    "preview.tab.fonts":            "Fuentes",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Abrir ejecutable",
    "fd.save_exe":                  "Guardar ejecutable como",
    "dlg.load.failed":              "Carga fallida",
    "dlg.load.failed_msg":          "El nuevo EXE no se ha cargado. El estado anterior del editor no ha cambiado.\n\n{error}",
    "dlg.load.unsupported_status":  "Ejecutable no compatible. La edición y el guardado están deshabilitados.",
    "dlg.load.unsupported_label":   "NO COMPATIBLE",
    "dlg.load.font_failed":         "La inicialización de la fuente ha fallado. El guardado está bloqueado.",
    "dlg.load.integrity_status":    "La comprobación de integridad ha fallado: {error}",
    "dlg.load.integrity_title":     "Comprobación de integridad fallida",
    "dlg.load.integrity_msg":       "La edición se puede inspeccionar, pero Repack y Guardar están bloqueados.\n\n{errors}",
    "dlg.unsaved.title":            "Cambios sin guardar",
    "dlg.unsaved.load":             "El EXE actual contiene cambios sin guardar o pendientes.\n\n¿Descartarlos y cargar otro archivo?",
    "dlg.unsaved.close":            "El EXE actual contiene cambios sin guardar o pendientes.\n\n¿Descartarlos y cerrar el editor?",
    "dlg.save.unsupported":         "No compatible",
    "dlg.save.unsupported_msg":     "Carga un ejecutable compatible antes de guardar.",
    "dlg.save.blocked":             "Guardado bloqueado",
    "dlg.save.verify":              "No se ha podido verificar el origen cargado: {error}",
    "dlg.save.external":            "El archivo de origen cargado ha cambiado fuera del editor. No se ha sobrescrito.",
    "dlg.save.done":                "Guardado completado",
    "dlg.save.noop":                "El archivo original ya es idéntico byte a byte y no ha cambiado.",
    "dlg.save.overwrite_title":     "Sobrescribir original cargado",
    "dlg.save.overwrite_msg":       "¿Reemplazar el original cargado por el EXE editado?\n\nPrimero se creará una copia de seguridad idéntica byte a byte.",
    "dlg.save.failed":              "Guardado fallido",
    "dlg.save.failed_msg":          "No se ha escrito ningún archivo de destino parcial.\n\n{error}",
    "dlg.save.done_msg":            "Ejecutable guardado en:\n{path}{backup}",
    "dlg.save.backup":              "\nCopia de seguridad: {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "Se requiere una validación de Repack correcta.",
    "block.font_invalid":           "La validación de la fuente ha fallado.",
    "block.font_pending":           "Aplica o descarta los cambios de fuente pendientes antes de guardar.",
    "block.text_pending":           "Aplica o descarta el cambio de texto pendiente antes de guardar.",
    "block.generic":                "El guardado está bloqueado actualmente.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Fuente:",
    "font.apply":                   "Aplicar cambios",
    "font.load_first":              "Carga primero un EXE.",
    "font.characters":              " Caracteres ",
    "font.matrix":                  " Matriz de píxeles (clic/arrastrar) ",
    "font.props":                   " Propiedades ",
    "font.width":                   "Anchura (px):",
    "font.tools":                   " Herramientas ",
    "font.copy":                    "📋 Copiar",
    "font.paste":                   "📌 Pegar",
    "font.clear":                   "🧹 Borrar",
    "font.invert":                  "🔄 Invertir",
    "font.file":                    " Archivo ",
    "font.import":                  "📥 Importar",
    "font.export":                  "📤 Exportar",
    "font.edit_charmap":            "Editar mapeo de caracteres…",
    "font.charmap_title":           "Mapeo de caracteres",
    "font.charmap_title_for":       "Mapeo de caracteres de {font}:",
    "font.remove":                  "✖ Eliminar",
    "font.blocked_title":           "Operación de fuente bloqueada",
    "font.blocked_status":          "✖ Operación de fuente bloqueada: {error}",
    "font.no_profile":              "No hay perfil de fuente para '{profile}'.",
    "font.summary":                 "{font}  •  {chars} caracteres  •  {unique} glifos únicos",
    "font.pending_title":           "Cambios de fuente pendientes",
    "font.pending_msg":             "¿Aplicar los cambios pendientes a {font} antes de cambiar?\n\nSí = Aplicar, No = Descartar, Cancelar = Permanecer",
    "font.no_data":                 "Sin datos",
    "font.no_data_msg":             "Carga un EXE y selecciona primero una fuente.",
    "font.no_exe_msg":              "Carga primero un archivo EXE.",
    "font.fd_export":               "Exportar fuente",
    "font.fd_import":               "Importar fuente ({font})",
    "font.export_error":            "Error de exportación",
    "font.exported":                "✔ {font} exportado → {file}",
    "font.imported":                "✔ Se han importado {n} glifos de {file} a {font}",
    "font.written":                 "✔ Se han escrito {n} glifos en los datos del EXE  ({font})",
    "font.written_title":           "Fuente escrita",
    "font.written_msg":             "{n} glifos únicos modificados en los datos del EXE.\nUsa «Guardar como...» en la barra superior para guardar el archivo.",
    "font.no_selection":            "Ninguna selección",
    "font.no_selection_msg":        "Selecciona primero un carácter.",
    "font.empty_clipboard":         "Portapapeles vacío",
    "font.empty_clipboard_msg":     "Copia primero un carácter (Ctrl+C).",
    "font.copied":                  "✓ Se ha copiado 0x{code:02X} '{char}' al portapapeles",
    "font.pasted":                  "✓ Pegado en 0x{code:02X} '{char}'",
    "font.alias":                   "⚠ Alias de 0x{code:02X} ('{char}')\nEditar este glifo también modifica el original.",
    "font.invalid_entry":           "Entrada de CharMap no válida",
    "font.invalid_entry_msg":       "Introduce un carácter Unicode.",
    "font.invalid_byte":            "Byte de CharMap no válido",
    # font_editor internal (non-GUI) messages
    "font.err.live_unavailable":    "No se ha cargado un estado de fuente compatible",
    "font.err.buffer_unavailable":  "El búfer EXE activo no está disponible",
    "font.err.import_failed":       "La importación ha fallado sin cambios: {error}",
    "font.err.apply_failed":        "La aplicación ha fallado; los datos activos no han cambiado: {error}",
    "font.err.paste_rejected":      "Pegado rechazado sin cambios: {error}",
    "font.err.initial_load":        "No se ha podido cargar la fuente inicial",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Configuración",
    "utils.cfg.damaged":            "La configuración existente está dañada y no se ha reemplazado.\nLos cambios de configuración permanecen bloqueados hasta que se repare o elimine.\n\n{reason}",
    "utils.cfg.locked":             "Los cambios de configuración no se guardan mientras la configuración existente esté dañada.\n\n{reason}",
    "utils.cfg.save_failed":        "No se ha podido guardar la configuración: {error}",

    # ── build_exe.py ──────────────────────────────────────────────────────────
    "build.err.no_entry":           "Falta el punto de entrada: {path}",
    "build.err.no_config":          "Falta el origen de configuración: {path}",
    "build.err.no_icon":            "Falta el recurso de icono: {path}",
    "build.err.pyi_failed":         "PyInstaller ha fallado con el código de salida {code}",
    "build.err.no_exe":             "No se ha producido el ejecutable esperado: {path}",
    "build.err.config_mismatch":    "La configuración de release no es idéntica byte a byte al origen",
    "build.err.key_nonempty":       "deepl_key.txt debe estar vacío",
    "build.step.config":            "[1/6] origen de configuración  {hash}  {size} B",
    "build.step.icon":              "      origen del icono    {hash}  {size} B",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] compilado  {hash}  {size} B",
    "build.step.removed_obsolete":  "      release anterior eliminada: {name}",
    "build.step.release_exe":       "[4/6] exe de release -> {path}",
    "build.step.config_verified":   "[5/6] configuración de release verificada  {hash}",
    "build.step.key_file":          "[6/6] deepl_key.txt de release  0 B",
    "build.step.release_header":    "\nRelease:",

    # ── translator.py ─────────────────────────────────────────────────────────
    "tr.err.markers_changed":       "Los marcadores de traducción protegidos han cambiado (faltantes={missing}, inesperados={unexpected})",
    "tr.err.marker_count":          "Ha cambiado el recuento de marcadores protegidos: {marker}",
    "tr.err.marker_unrestored":     "Queda un marcador de traducción sin restaurar",
    "tr.err.no_text":               "El traductor no ha devuelto texto",
    "tr.err.lingva_unreachable":    "Todos los servidores son inaccesibles (403/503). Prueba Google Translate o MyMemory.",
    "tr.err.mymemory":              "Error de MyMemory {status}: {detail}",
    "tr.err.deepl_no_key":          "No se ha encontrado la clave de DeepL.\nRegístrate gratis en https://www.deepl.com/pro#developer\nDespués guarda la clave en deepl_key.txt.",
    "tr.err.argos_not_installed":   "Argos Translate no está instalado.\nEjecuta: pip install argostranslate\ny descarga los paquetes de idiomas.",
    "tr.err.argos_no_package":      "El paquete de Argos '{src}→{tgt}' no está instalado.\nDescárgalo con argostranslate.package.",
    "tr.err.argos_no_translation":  "No hay ninguna traducción de Argos disponible para {src}→{tgt}.",

    # ── charmap.py ───────────────────────────────────────────────────────────
    "charmap.err.invalid_key":      "Clave de byte de CharMap no válida: {key}",
    "charmap.err.key_not_one_byte": "La clave de CharMap debe identificar un byte: {key}",
    "charmap.err.value_not_char":   "El valor de CharMap debe ser un solo carácter: {value}",
    "charmap.err.ambiguous":        "Carácter de CharMap ambigu: {char}",
    "charmap.err.outside_font":     "El byte 0x{byte:02X} para {char!r} está fuera de la fuente activa",
    "charmap.err.no_codepoint":     "El carácter U+{cp:04X} en la posición {pos} no tiene entrada de CharMap",
    "charmap.err.conflict":         "El carácter {char!r} en la posición {pos} entra en conflicto con el glifo {glyph!r}",

    # ── font_safety.py ───────────────────────────────────────────────────────
    "fsafe.err.invalid_width":      "Anchura de glifo no válida: {width!r}",
    "fsafe.err.unknown_font":       "Fuente desconocida: {font}",
    "fsafe.err.incomplete_desc":    "Descripción incompleta de la fuente para {font}",
    "fsafe.err.unsupported_type":   "Tipo de fuente no compatible para {font}",
    "fsafe.err.invalid_row_count":  "Número de filas/punteros no válido para {font}",
    "fsafe.err.ptr_table_outside":  "Tabla de punteros fuera del EXE para {font}",
    "fsafe.err.ptr_table_size":     "Tamaño de tabla de punteros incorrecto para {font}: {got} bytes para {ptrs} punteros",
    "fsafe.err.glyph_range":        "Rango de glifos fuera del EXE o solapado con la tabla de punteros para {font}",
    "fsafe.err.ptr_target":         "El puntero de glifo {idx} para {font} apunta a {addr:#x}, fuera de {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "El primer glifo de {font} no comienza en glyph_start",
    "fsafe.err.slot_invalid":       "Ranura de glifo no válida/solapada en {addr:#x} en {font}",
    "fsafe.err.dynamic_uneven":     "La ranura de glifo dinámica en {addr:#x} tiene una disposición irregular de filas",
    "fsafe.err.dynamic_capacity":   "La ranura de glifo dinámica en {addr:#x} tiene una capacidad no compatible de {cap}",
    "fsafe.err.width_exceeds_slot": "La anchura del glifo {width} en {addr:#x} supera la capacidad de la ranura {max}",
    "fsafe.err.fixed_size":         "La ranura de glifo fija en {addr:#x} tiene tamaño {got}, se esperaba {expected}",
    "fsafe.err.fixed_width":        "La anchura del glifo fijo {width} en {addr:#x} no es válida",
    "fsafe.err.glyph_exceeds_slot": "Los datos del glifo en {addr:#x} superan su ranura física",
    "fsafe.err.model_char_count":   "El modelo de fuente tiene {got} caracteres, se esperaban {expected}",
    "fsafe.err.invalid_char_idx":   "Índice de carácter no válido {idx}",
    "fsafe.err.no_glyph_obj":       "El carácter {idx} no tiene objeto de glifo",
    "fsafe.err.invalid_glyph_off":  "El carácter {idx} tiene un desplazamiento de glifo no válido",
    "fsafe.err.alias_not_shared":   "Los alias en {addr:#x} no comparten un único objeto de glifo canónico",
    "fsafe.err.alias_meta":         "Metadatos de alias no coincidentes para el carácter {idx}",
    "fsafe.err.glyph_start":        "El modelo de fuente no comienza en glyph_start",
    "fsafe.err.slot_boundary":      "Límite de ranura no coincidente en {addr:#x}",
    "fsafe.err.slot_outside_exe":   "La ranura en {addr:#x} está fuera del EXE",
    "fsafe.err.dynamic_cap_meta":   "Capacidad de ranura dinámica no válida en {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "La capacidad almacenada no coincide en {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "La anchura/clase de fila supera la ranura en {addr:#x}",
    "fsafe.err.fixed_slot":         "Ranura fija no válida en {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "La capacidad fija almacenada no coincide en {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Anchura fija no válida en {addr:#x}",
    "fsafe.err.bitmap_value":       "Valor de bitmap fuera de la clase de fila en {addr:#x}",
    "fsafe.err.serial_exceeds":     "La serialización del glifo supera la ranura en {addr:#x}",
    "fsafe.err.bpr_conversion":     "Conversión de bytes por fila no compatible",
    "fsafe.err.width_not_int":      "La anchura debe ser un entero",
    "fsafe.err.width_exceeds_max":  "La anchura {width} supera esta ranura de glifo (máx. {max})",
    "fsafe.err.fixed_width_range":  "La anchura FLOW/MICRO debe mantenerse entre 1 y 8",
    "fsafe.err.clipboard_invalid":  "El portapapeles no contiene un glifo válido",
    "fsafe.err.height_mismatch":    "Altura de glifo incompatible: origen {src}, destino {tgt}",
    "fsafe.err.clip_type_invalid":  "El tipo de fuente del portapapeles no es válido",
    "fsafe.err.clip_bpr_invalid":   "La clase de fila del portapapeles no es válida",
    "fsafe.err.clip_fixed_width":   "La anchura fija del portapapeles no es válida",
    "fsafe.err.clip_bitmap":        "El bitmap del portapapeles no es válido",
    "fsafe.err.target_too_wide":    "El glifo es más ancho que un destino FLOW/MICRO",
    "fsafe.err.paste_exceeds_slot": "La anchura del glifo {width} supera la capacidad de la ranura de destino {max}",
    "fsafe.err.write_exceeds":      "La escritura del glifo en {addr:#x} supera su ranura",
    "fsafe.err.ptr_alias_struct":   "El modelo de fuente ya no coincide con la estructura de punteros/alias del EXE",
    "fsafe.err.changed_outside":    "La serialización de la fuente ha cambiado bytes fuera de las ranuras de glifos",
    "fsafe.err.readback_mismatch":  "Incoherencia al releer la fuente en {addr:#x}",
    "fsafe.err.import_truncated":   "La importación está truncada antes del glifo {idx}",
    "fsafe.err.import_width":       "La anchura importada {width} supera la capacidad {cap} del glifo {idx}",
    "fsafe.err.import_fixed_width": "La anchura fija importada {width} no es válida en el glifo {idx}",
    "fsafe.err.import_trunc_body":  "La importación está truncada dentro del glifo {idx}",
    "fsafe.err.import_trailing":    "La importación contiene {n} bytes finales inesperados",
    "fsafe.err.no_dir":             "El directorio de destino no existe: {dir}",
    "fsafe.err.short_write":        "Escritura parcial: {written} de {total} bytes",
    "fsafe.err.readback_tmp":       "Incoherencia al releer el archivo temporal",
    "fsafe.err.no_backup_src":      "No se puede hacer una copia de seguridad de un archivo original inexistente",
    "fsafe.err.buffers_differ":     "Los búferes de fuente difieren en {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "Los búferes de fuente no tienen el mismo estado previo al commit",

    # ── diff_preview.py ───────────────────────────────────────────────────────
    "diff.err.no_raw":              "La entrada {sid} no contiene bytes raw estrictos",
    "diff.err.no_ref_type":         "La entrada {sid} no tiene tipo de referencia",
    "diff.err.range_outside":       "El rango base para {label} está fuera del EXE",
    "diff.err.not_nul_term":        "La cadena base {label} no está terminada en NUL",
    "diff.err.ptr_normal_outside":  "Origen de puntero normal fuera del EXE: {addr:#x}",
    "diff.err.ptr_code_outside":    "Origen de puntero de código fuera del EXE: {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Tipo de puntero desconocido: {kind}",
    "diff.err.ptr_base_mismatch":   "El puntero {addr:#x} tiene base {got}, se esperaba {expected}",
    "diff.err.ptr_outside_ranges":  "El puntero {addr:#x} apunta fuera de los rangos Repack: {target:#x}",
    "diff.err.no_unique_sid":       "Las entradas actuales no tienen string_id únicos",
    "diff.err.fixed_id":            "string_id fijo no válido: {sid}",
    "diff.err.unknown_fixed_slot":  "Ranura base fija desconocida: {sid}",
    "diff.err.ambiguous_targets":   "Los orígenes de puntero base para {sid} tienen {n} destinos",
    "diff.err.baseline_failed":     "La reconstrucción de la base ha fallado: {detail}",
    "diff.err.repack_mutated":      "La ejecución de prueba del Repack de referencia ha modificado sus entradas",
    "diff.err.range_cross_end":     "La cadena recompaquetada cruza el final del bloque en {addr:#x}",
    "diff.err.pending_preflight":   "string_id pendiente desconocido: {sid}",
    "diff.err.pending_not_bytes":   "El reemplazo pendiente para {sid} no son bytes raw",
    "diff.err.fixed_exceed":        "La cadena fija {sid} supera {max} bytes ({got} bytes)",
    "diff.err.dup_normal_ptr":      "Origen de puntero normal duplicado: {addr:#x}",
    "diff.err.dup_code_ptr":        "Origen de puntero de código duplicado: {addr:#x}",
    "diff.err.alias_not_canonical": "Los alias en {addr:#x} no son canónicos",
    "diff.err.ptr_table_changed":   "La tabla de punteros de fuente ha cambiado para {font}",
    "diff.err.glyph_set_changed":   "El conjunto físico de glifos ha cambiado para {font}",
    "diff.err.alias_set_changed":   "El conjunto de alias ha cambiado en {addr:#x} en {font}",
    "diff.err.meta_reconstruct":    "No se han podido reconstruir los metadatos de la cadena: {error}",
    "diff.err.no_font_key":         "El modelo de fuente pendiente no tiene clave de fuente",
    "diff.err.font_preview_failed": "La vista previa de la fuente pendiente ha fallado: {error}",
    "diff.err.sid_sets_differ":     "Los conjuntos de string_id base/actual difieren",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "La vista previa ha modificado baseline_data",
    "diff.err.mutated_current":     "La vista previa ha modificado current_data",
    "diff.err.mutated_entries":     "La vista previa ha modificado las entradas actuales",
    "diff.err.mutated_font":        "La vista previa ha modificado el modelo de fuente pendiente",
    "diff.err.baseline_repack":     "El Repack base ha fallado: {detail}",
    "diff.err.unknown_baseline":    "Fallo de validación base desconocido",
    "diff.err.unknown_baseline_repack": "Fallo de Repack base desconocido",

    # ── repack_validator.py ───────────────────────────────────────────────────
    "repack.err.encoding":          "La cadena {sid} contiene un carácter que no se puede codificar",
    "repack.err.site_outside":      "Sitio de reubicación fuera del archivo: {addr:#x}",
    "repack.err.missing_code_ptrs": "Faltan punteros de código: {addrs}",
    "repack.err.extra_code_ptrs":   "Punteros de código inesperados: {addrs}",
    "repack.err.mismatched_ptrs":   "Punteros de código no coincidentes: {addrs}",
    "repack.err.no_sid":            "La entrada en {addr:#x} no tiene string_id",
    "repack.err.dup_sid":           "string_id duplicado: {sid}",
    "repack.err.fixed_has_ptrs":    "La entrada fija {sid} tiene punteros inesperadamente",
    "repack.err.dup_normal_src":    "Origen de puntero normal duplicado: {addr:#x}",
    "repack.err.uninv_normal_src":  "Origen de puntero normal no inventariado: {addr:#x}",
    "repack.err.normal_target":     "El puntero normal {src:#x} apunta a {expected:#x}, mientras que la entrada es {actual:#x}",
    "repack.err.dup_code_src":      "Origen de puntero de código duplicado: {addr:#x}",
    "repack.err.uninv_code_src":    "Origen de puntero de código no inventariado: {addr:#x}",
    "repack.err.code_target":       "El puntero de código {src:#x} apunta a {expected:#x}, mientras que la entrada es {actual:#x}",
    "repack.err.unowned_normal":    "{n} punteros normales respaldados por reubicaciones no están asignados",
    "repack.err.unowned_code":      "{n} punteros de código respaldados por reubicaciones no están asignados",
    "repack.err.unknown_fixed":     "Cadena fija desconocida: {addr:#x}",
    "repack.err.fixed_slot_size":   "La cadena fija supera la ranura en {addr:#x}",
    "repack.err.fixed_mismatch":    "Bytes de cadena fija no coincidentes en {addr:#x}",
    "repack.err.outside_ranges":    "Cadena fuera de los rangos válidos: {addr:#x}",
    "repack.err.crosses_range":     "La cadena cruza el final del rango: {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "Bytes/NUL de cadena no coincidentes en {addr:#x}",
    "repack.err.illegal_overlap":   "Solapamiento ilegal de cadenas: {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Bytes ocupados desconocidos en el rango {idx}: {n} bytes, primero {addr:#x}",
    "repack.err.entry_outside":     "Entrada fuera de los rangos válidos: {addr:#x}",
    "repack.err.range_overflow":    "Desbordamiento del rango {idx}: {required} > {total}",
    "repack.err.ptr_value_range":   "Valor de puntero fuera del rango de 16 bits: {value:#x}",
    "repack.err.normal_src_file":   "Origen de puntero normal fuera del archivo: {addr:#x}",
    "repack.err.code_src_file":     "Origen de puntero de código fuera del archivo: {addr:#x}",
    "repack.err.suffix_chain":      "Cadena de compartición de sufijos no resuelta",
    "repack.err.file_size_changed": "El tamaño del archivo ha cambiado",
    "repack.err.extra_diffs":       "Bytes modificados inesperadamente fuera de rangos/offsets de punteros: {n}, primero {addr:#x}",

    # ── string_exchange.py ────────────────────────────────────────────────────
    "xchg.err.not_serialisable":    "El valor no se puede canonizar: {error}",
    "xchg.err.not_raw_text":        "La entrada {sid} no contiene texto de bytes raw estrictos",
    "xchg.err.no_ref_type":         "La entrada {sid} no tiene un tipo de referencia compatible",
    "xchg.err.charmap_not_obj":     "CharMap debe ser un objeto",
    "xchg.err.invalid_key":         "Clave de byte de CharMap no válida: {key!r}",
    "xchg.err.key_not_one_byte":    "La clave de CharMap debe identificar un byte: {key!r}",
    "xchg.err.invalid_char":        "Carácter de CharMap no válido: {char!r}",
    "xchg.err.conflict_key":        "Clave de CharMap en conflicto: {key!r}",
    "xchg.err.ambiguous_char":      "Carácter de CharMap ambiguo: {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF no se pueden exportar como texto visible",
    "xchg.err.no_sid":              "Cada entrada debe tener un string_id",
    "xchg.err.dup_sid":             "string_id duplicado en las entradas activas",
    "xchg.err.no_charmap":          "No hay códigos de CharMap/fuente confirmados para {font}",
    "xchg.err.outside_repack":      "La entrada {sid} está fuera de todos los bloques Repack",
    "xchg.err.unknown_fixed_slot":  "Ranura fija desconocida para {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR y LF no están permitidos en las cadenas importadas",
    "xchg.err.unconfirmed_byte":    "El carácter similar a byte U+{cp:04X} no confirmado debe usar \\xNN",
    "xchg.err.trailing_backslash":  "Barra inversa final en el texto de intercambio",
    "xchg.err.bad_escape":          "La barra inversa debe escaparse como \\\\ o con la forma \\xNN",
    "xchg.err.nul_byte_escape":     "Las secuencias de bytes NUL, CR y LF no están permitidas",
    "xchg.err.use_visible":         "El byte 0x{byte:02X} debe usar su representación visible confirmada",
    "xchg.err.new_dup_escape":      "Secuencia de byte nueva o duplicada \\x{byte:02X}",
    "xchg.err.control_token":       "Token de control no válido: {token!r}",
    "xchg.err.token_outside_font":  "Token de control fuera de la fuente activa: {token!r}",
    "xchg.err.unconfirmed_intro":   "Se ha introducido o duplicado el byte no confirmado 0x{byte:02X}",
    "xchg.err.not_utf8":            "La importación no es UTF-8 válida",
    "xchg.err.invalid_json":        "JSON no válido o truncado: {error}",
    "xchg.err.root_not_obj":        "La raíz del documento de intercambio debe ser un objeto",
    "xchg.err.dup_json_key":        "Clave JSON duplicada: {key!r}",
    "xchg.err.invalid_constant":    "Constante numérica JSON no válida: {value}",
    "xchg.err.schema_mismatch":     "Los campos del esquema de nivel superior no coinciden con la versión 1",
    "xchg.err.bad_format":          "Formato de intercambio de cadenas no compatible",
    "xchg.err.bad_version":         "Versión del formato de intercambio de cadenas no compatible",
    "xchg.err.no_profile_id":       "profile_id debe ser una cadena no vacía",
    "xchg.err.bad_entry_count":     "entry_count debe ser un entero no negativo",
    "xchg.err.entries_not_array":   "entries debe ser una matriz",
    "xchg.err.count_mismatch":      "entry_count no coincide con entries",
    "xchg.err.entry_schema":        "Los campos del esquema de entrada no coinciden con la versión 1",
    "xchg.err.no_string_id":        "string_id debe ser una cadena no vacía",
    "xchg.err.dup_entry_id":        "string_id duplicado: {sid}",
    "xchg.err.invalid_kind":        "Tipo no válido para {sid}",
    "xchg.err.editable_not_bool":   "editable debe ser booleano para {sid}",
    "xchg.err.suffix_not_array":    "suffix_links debe ser una matriz para {sid}",
    "xchg.err.suffix_link_schema":  "Esquema de enlace de sufijo no válido para {sid}",
    "xchg.err.suffix_role":         "Rol de sufijo no válido para {sid}",
    "xchg.err.suffix_peer":         "Par de sufijo no válido para {sid}",
    "xchg.err.suffix_offset":       "Desplazamiento de sufijo no válido para {sid}",
    "xchg.err.no_font":             "Fuente no válida para {sid}",
    "xchg.err.invalid_block":       "repack_block no válido para {sid}",
    "xchg.err.invalid_ptr_count":   "{field} no válido para {sid}",
    "xchg.err.invalid_capacity":    "Capacidad fija no válida para {sid}",
    "xchg.err.bad_hash":            "{field} debe ser un SHA-256 en mayúsculas",
    "xchg.err.source_text_str":     "source_text debe ser una cadena para {sid}",
    "xchg.err.translated_type":     "translated_text debe ser null o una cadena para {sid}",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 no coincide con los hashes de las entradas",
    "xchg.err.wrong_profile":       "Perfil incorrecto: {got!r}, se esperaba {expected!r}",
    "xchg.err.structure_mismatch":  "La huella de estructura del perfil no coincide",
    "xchg.err.charmap_mismatch":    "La huella de CharMap no coincide",
    "xchg.err.entry_count_mismatch": "El número de entradas importadas no coincide con el EXE cargado",
    "xchg.err.missing_sid":         "Falta string_id: {sid}",
    "xchg.err.unknown_sid":         "string_id desconocido: {sid}",
    "xchg.err.manipulated_field":   "{field} manipulado para {sid}",
    "xchg.err.source_hash":         "source_text/hash no coincide para {sid}",
    "xchg.err.token_mismatch":      "Token protegido no coincide para {sid}",
    "xchg.err.layout_mismatch":     "Espaciado/diseño protegido no coincide para {sid}",
    "xchg.err.read_only":           "La entrada de sufijo es de solo lectura: {sid}",
    "xchg.err.fixed_exceeds":       "La cadena fija {sid} supera {cap} bytes",
    "xchg.err.stale_conflict":      "Conflicto con el origen obsoleto para {sid}",
    "xchg.err.escape_changed":      "Las secuencias de bytes no confirmadas han cambiado para {sid}",
    "xchg.err.unknown_sid_replace": "El conjunto de reemplazos contiene un string_id desconocido",
    "xchg.err.replace_not_bytes":   "El reemplazo de {sid} no son bytes raw",
    "xchg.err.fixed_exceed_import": "La cadena fija {sid} supera {max} bytes",
    "xchg.err.repack_blocked":      "Repack de importación bloqueado: {detail}",
    "xchg.err.suffix_changed":      "La importación cambiaría las relaciones de compartición de sufijos",
    "xchg.err.font_validation":     "La validación de fuente de la importación ha fallado: {error}",
    "xchg.err.unknown_repack":      "Fallo de validación de Repack desconocido",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Metadatos de filtro no válidos en la fila {idx}",
    "sfilter.err.dup_sid":        "string_id ausente o duplicado en la fila {idx}",
    "sfilter.err.invalid_kind":   "Tipo de cadena no válido para {sid}: {kind!r}",
    "sfilter.err.invalid_font":   "Fuente efectiva no válida para {sid}",
    "sfilter.err.invalid_text":   "Texto de búsqueda no válido para {sid}",
    "sfilter.err.invalid_preview":"Estado de vista previa no válido para {sid}",
    "sfilter.err.invalid_override":"Anulación de estado no válida para {sid}",
    "sfilter.err.query_not_text": "La consulta de búsqueda debe ser texto",
    "sfilter.err.unknown_kind":   "Filtro Tipo desconocido: {kind!r}",
    "sfilter.err.font_empty":     "El filtro Fuente debe ser un nombre no vacío",
    "sfilter.err.unknown_change": "Filtro Cambio desconocido: {change!r}",
    "sfilter.err.unknown_status": "Filtro Estado desconocido: {status!r}",
}
