TEXTS_EN = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "File",
    "menu.file.open":               "Open EXE\u2026",
    "menu.file.save_as":            "Save As\u2026",
    "menu.file.quit":               "Exit",
    "menu.tools":                   "Tools",
    "menu.tools.details":           "Changes / Details\u2026",
    "menu.tools.export":            "Export strings\u2026",
    "menu.tools.import":            "Import strings\u2026",
    "menu.tools.autotranslate":     "Automatic translation",
    "menu.tools.translate_all":     "Translate all strings\u2026",
    "menu.view":                    "View",
    "menu.view.strings":            "Strings",
    "menu.view.fonts":              "Font Editor",
    "menu.view.settings":           "Editor Settings",
    "menu.view.language":           "Language",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "\U0001f4c1 Choose EXE\u2026",
    "header.save_as":               "\U0001f4be Save As\u2026",
    "header.profile":               "Profile:",
    "header.profile_none":          "\u2014",
    "header.no_file":               "No file loaded.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  \U0001f4dd Strings  ",
    "tab.fonts":                    "  \U0001f524 Font Editor  ",
    "tab.settings":                 "  \u2699 Editor Settings  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "\U0001f50d Search:",
    "filter.toggle_closed":         "Filter \u25b8",
    "filter.toggle_open":           "Filter \u25be",
    "filter.kind":                  "Kind:",
    "filter.font":                  "Font:",
    "filter.change":                "Change:",
    "filter.status":                "Status:",
    "filter.reset":                 "\u274c Reset filters",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Offset",
    "col.text":                     "String text",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Edit text (spaces highlighted) ",
    "edit.apply":                   "\u2714 Apply change",
    "edit.stats":                   "Total length: {n} chars | Leading spaces: {lead} | Trailing spaces: {trail}",
    "edit.encoding_blocked":        "Encoding blocked: {error}",
    "edit.diff_unavailable":        "Diff status unavailable: {error}",
    "edit.fixed_rest":              "Fixed rest: {rest}/{cap} bytes",
    "edit.block_rest":              "Shared B{block} rest after all changes: {rest} bytes",
    "edit.block_preview":           "B{block} shared rest: preview required",
    "edit.range_info":              "{kind} | {font} | bytes {old}\u2192{new} (\u0394 {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "\U0001f310 Translation",
    "action.details":               "\U0001f50e Changes / Details\u2026",
    "action.export":                "\U0001f4e4 Export\u2026",
    "action.import":                "\U0001f4e5 Import\u2026",
    "action.font_assign":           "Font assignment\u2026",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Engine:",
    "tr.from":                      "From:",
    "tr.to":                        "To:",
    "tr.all":                       "\u26a1 Translate all",
    "tr.translated":                "Translated text:",
    "tr.apply":                     "\u2714 Apply translation",
    "tr.translating":               "Translating...",
    "tr.error":                     "Error: {error}",
    "tr.no_changes":                "No changes to apply.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Character mapping (CharMap) ",
    "settings.font_group":          " Font assignment ",
    "settings.font_auto":           "The assignment is automatic.\nA different choice applies only to the\ncurrently selected string.",
    "settings.font_label":          "Assigned font:",
    "settings.hint_group":          " Saving behaviour ",
    "settings.hint_text":           "CharMap and font assignments are saved\nimmediately and automatically.\n\nThe EXE itself is only written via\n\u201eFile \u2192 Save As\u2026\u201c.",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} of {total} strings",
    "status.filter_pending":        "Filter view is waiting \u2014 apply or discard the change first.",
    "status.selection_blocked":     "Selection change blocked \u2014 apply or discard the change first.",
    "status.filter_unavailable":    "Filter unavailable: {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Pending Text Change",
    "dlg.pending_font.msg":         "Apply or discard the pending text or translation before changing the associated font.\n\nNothing was changed.",
    "dlg.pending_charmap.msg":      "Apply or discard the pending text or translation before changing the CharMap.\n\nNothing was changed.",
    "dlg.pending_translation.title": "Pending Translation",
    "dlg.pending_translation.switch": "Apply the pending translation before switching automatic translation off?\n\nYes = Apply, No = Discard, Cancel = Keep it open",
    "dlg.pending_translation.new":  "Apply or discard the pending translation before requesting a new one.\n\nNothing was changed.",
    "dlg.text_blocked.title":       "Text Change Blocked",
    "dlg.text_blocked.translation": "Apply or discard the pending translation before applying the text change.\n\nNothing was changed.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "Translate ALL",
    "dlg.translate_all.none":       "No string loaded.",
    "dlg.translate_all.confirm":    "Automatically translate all {n} strings with '{engine}'?",
    "dlg.translate_all.window":     "Translating ALL...",
    "dlg.translate_all.progress":   "{current}/{total}: {text}",
    "dlg.translate_all.blocked":    "Translate ALL Blocked",
    "dlg.translate_all.unchanged":  "No text changed. The EXE was not repacked and remains unchanged.",
    "dlg.translate_all.nochange":   "No text or EXE data was changed.\n\n{detail}",
    "dlg.translate_all.done":       "Completed",
    "dlg.translate_all.summary":    "Complete: {translated} translated, {unchanged} unchanged, {blank} blank.",
    "dlg.translate_all.suffix":     "\n{n} suffix-group entries safely skipped.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Export Blocked",
    "dlg.export.failed":            "Export Failed",
    "dlg.export.partial":           "No partial export file was committed.\n\n{error}",
    "dlg.export.done":              "Export Complete",
    "dlg.export.done_msg":          "Exported {n} strings.\n\n{path}",
    "dlg.export.status":            "Exported {n} strings to {file}.",
    "fd.export":                    "Export Strings",
    "dlg.import.blocked":           "Import Blocked",
    "dlg.import.nochange":          "No editor state was changed.\n\n{error}",
    "dlg.import.done":              "Import Complete",
    "dlg.import.none":              "Profile: {profile}\nChanged strings: 0\n\nNo editor state was changed.",
    "dlg.import.confirm":           "Profile: {profile}\nStrings to change: {n}\n\nApply the complete validated import transaction?",
    "dlg.import.title":             "Import Strings",
    "dlg.import.done_msg":          "Profile: {profile}\nChanged strings: {n}\n\nThe EXE was not saved automatically.",
    "dlg.import.status":            "Imported {n} strings.",
    "fd.import":                    "Import Strings",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "Changes / Preview \u2014 {profile}",
    "dlg.preview.warn":             "Preview",
    "dlg.preview.load_first":       "Load a supported executable first.",
    "dlg.preview.failed":           "Preview Failed",
    "dlg.preview.close":            "Close",
    "preview.tab.summary":          "Summary",
    "preview.tab.strings":          "Strings",
    "preview.tab.blocks":           "Blocks",
    "preview.tab.pointers":         "Pointers",
    "preview.tab.fonts":            "Fonts",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Open executable",
    "fd.save_exe":                  "Save executable as",
    "dlg.load.failed":              "Load Failed",
    "dlg.load.failed_msg":          "The new EXE was not loaded. The previous editor state is unchanged.\n\n{error}",
    "dlg.load.unsupported_status":  "Unsupported executable. Editing and saving are disabled.",
    "dlg.load.unsupported_label":   "UNSUPPORTED",
    "dlg.load.font_failed":         "Font initialization failed. Saving is blocked.",
    "dlg.load.integrity_status":    "Integrity check failed: {error}",
    "dlg.load.integrity_title":     "Integrity Check Failed",
    "dlg.load.integrity_msg":       "Editing can be inspected, but Repack and Save are blocked.\n\n{errors}",
    "dlg.unsaved.title":            "Unsaved Changes",
    "dlg.unsaved.load":             "The current EXE has unsaved or pending changes.\n\nDiscard them and load another file?",
    "dlg.unsaved.close":            "The current EXE has unsaved or pending changes.\n\nDiscard them and close the editor?",
    "dlg.save.unsupported":         "Unsupported",
    "dlg.save.unsupported_msg":     "Load a supported executable before saving.",
    "dlg.save.blocked":             "Save Blocked",
    "dlg.save.verify":              "Could not verify the loaded source: {error}",
    "dlg.save.external":            "The loaded source file changed outside the editor. It was not overwritten.",
    "dlg.save.done":                "Save Complete",
    "dlg.save.noop":                "The original file is already byte-identical and unchanged.",
    "dlg.save.overwrite_title":     "Overwrite Loaded Original",
    "dlg.save.overwrite_msg":       "Replace the loaded original with the edited EXE?\n\nA byte-identical backup will be created first.",
    "dlg.save.failed":              "Save Failed",
    "dlg.save.failed_msg":          "No partial target file was committed.\n\n{error}",
    "dlg.save.done_msg":            "Executable saved to:\n{path}{backup}",
    "dlg.save.backup":              "\nBackup: {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "A successful Repack validation is required.",
    "block.font_invalid":           "Font validation failed.",
    "block.font_pending":           "Apply or discard the pending font changes before saving.",
    "block.text_pending":           "Apply or discard the pending text change before saving.",
    "block.generic":                "Saving is currently blocked.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Font:",
    "font.apply":                   "Apply changes",
    "font.load_first":              "Load an EXE first.",
    "font.characters":              " Characters ",
    "font.matrix":                  " Pixel matrix (click/drag) ",
    "font.props":                   " Properties ",
    "font.width":                   "Width (px):",
    "font.tools":                   " Tools ",
    "font.copy":                    "\U0001f4cb Copy",
    "font.paste":                   "\U0001f4cc Paste",
    "font.clear":                   "\U0001f9f9 Clear",
    "font.invert":                  "\U0001f504 Invert",
    "font.file":                    " File ",
    "font.import":                  "\U0001f4e5 Import",
    "font.export":                  "\U0001f4e4 Export",
    "font.edit_charmap":            "Edit character mapping\u2026",
    "font.charmap_title":           "Char Mapping",
    "font.charmap_title_for":       "{font} char mapping:",
    "font.remove":                  "\u2716 Remove",
    "font.blocked_title":           "Font Operation Blocked",
    "font.blocked_status":          "\u2716 Font operation blocked: {error}",
    "font.no_profile":              "No font profile for '{profile}'.",
    "font.summary":                 "{font}  \u2022  {chars} chars  \u2022  {unique} unique glyphs",
    "font.pending_title":           "Pending Font Changes",
    "font.pending_msg":             "Apply pending changes to {font} before switching?\n\nYes = Apply, No = Discard, Cancel = Stay",
    "font.no_data":                 "No data",
    "font.no_data_msg":             "Load an EXE and select a font first.",
    "font.no_exe_msg":              "Load an EXE file first.",
    "font.fd_export":               "Export Font",
    "font.fd_import":               "Import Font ({font})",
    "font.export_error":            "Export error",
    "font.exported":                "\u2714 Exported {font} \u2192 {file}",
    "font.imported":                "\u2714 Imported {n} glyphs from {file} into {font}",
    "font.written":                 "\u2714 {n} glyphs written to EXE data  ({font})",
    "font.written_title":           "Font Written",
    "font.written_msg":             "{n} unique glyphs patched into EXE data.\nUse 'Save As...' in the top bar to save the file.",
    "font.no_selection":            "No selection",
    "font.no_selection_msg":        "Select a character first.",
    "font.empty_clipboard":         "Empty clipboard",
    "font.empty_clipboard_msg":     "Copy a character first (Ctrl+C).",
    "font.copied":                  "\u2713 Copied 0x{code:02X} '{char}' to clipboard",
    "font.pasted":                  "\u2713 Pasted to 0x{code:02X} '{char}'",
    "font.alias":                   "\u26a0 Alias of 0x{code:02X} ('{char}')\nEditing this glyph edits the original too.",
    "font.invalid_entry":           "Invalid CharMap Entry",
    "font.invalid_entry_msg":       "Enter a Unicode character.",
    "font.invalid_byte":            "Invalid CharMap Byte",
    # font_editor internal (non-GUI) messages
    "font.err.live_unavailable":    "No supported font state is loaded",
    "font.err.buffer_unavailable":  "Live EXE buffer is unavailable",
    "font.err.import_failed":       "Import failed without changes: {error}",
    "font.err.apply_failed":        "Apply failed; live data was not changed: {error}",
    "font.err.paste_rejected":      "Paste rejected without changes: {error}",
    "font.err.initial_load":        "Initial font could not be loaded",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Config",
    "utils.cfg.damaged":            "The existing configuration is damaged and was not replaced.\nConfiguration changes stay blocked until it is repaired or removed.\n\n{reason}",
    "utils.cfg.locked":             "Configuration changes are not saved while the existing configuration is damaged.\n\n{reason}",
    "utils.cfg.save_failed":        "Could not save config: {error}",

    # ── build_exe.py ──────────────────────────────────────────────────────────
    "build.err.no_entry":           "Entrypoint missing: {path}",
    "build.err.no_config":          "Config source missing: {path}",
    "build.err.no_icon":            "Icon resource missing: {path}",
    "build.err.pyi_failed":         "PyInstaller failed with exit code {code}",
    "build.err.no_exe":             "Expected executable not produced: {path}",
    "build.err.config_mismatch":    "Release config is not byte-identical to the source",
    "build.err.key_nonempty":       "deepl_key.txt must be empty",
    "build.step.config":            "[1/6] config source  {hash}  {size} B",
    "build.step.icon":              "      icon source    {hash}  {size} B",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] built  {hash}  {size} B",
    "build.step.removed_obsolete":  "      removed superseded release: {name}",
    "build.step.release_exe":       "[4/6] release exe -> {path}",
    "build.step.config_verified":   "[5/6] release config verified  {hash}",
    "build.step.key_file":          "[6/6] release deepl_key.txt  0 B",
    "build.step.release_header":    "\nRelease:",

    # ── translator.py ─────────────────────────────────────────────────────────
    "tr.err.markers_changed":       "Protected translation markers changed (missing={missing}, unexpected={unexpected})",
    "tr.err.marker_count":          "Protected marker count changed: {marker}",
    "tr.err.marker_unrestored":     "Unrestored translation marker remains",
    "tr.err.no_text":               "Translator returned no text",
    "tr.err.lingva_unreachable":    "All servers are inaccessible (403/503). Try Google Translate or MyMemory.",
    "tr.err.mymemory":              "MyMemory error {status}: {detail}",
    "tr.err.deepl_no_key":          "DeepL key not found.\nRegister for free at https://www.deepl.com/pro#developer\nThen save the key in deepl_key.txt.",
    "tr.err.argos_not_installed":   "Argos Translate not installed.\nExecute: pip install argostranslate\nand download the language packs.",
    "tr.err.argos_no_package":      "Argos package '{src}\u2192{tgt}' not installed.\nDownload it with argostranslate.package.",
    "tr.err.argos_no_translation":  "No Argos translation available for {src}\u2192{tgt}.",

    # ── charmap.py ───────────────────────────────────────────────────────────
    "charmap.err.invalid_key":      "Invalid CharMap byte key: {key}",
    "charmap.err.key_not_one_byte": "CharMap key must identify one byte: {key}",
    "charmap.err.value_not_char":   "CharMap value must be one character: {value}",
    "charmap.err.ambiguous":        "Ambiguous CharMap character: {char}",
    "charmap.err.outside_font":     "Byte 0x{byte:02X} for {char!r} is outside the active font",
    "charmap.err.no_codepoint":     "Character U+{cp:04X} at position {pos} has no CharMap entry",
    "charmap.err.conflict":         "Character {char!r} at position {pos} conflicts with glyph {glyph!r}",

    # ── font_safety.py ───────────────────────────────────────────────────────
    "fsafe.err.invalid_width":      "Invalid glyph width: {width!r}",
    "fsafe.err.unknown_font":       "Unknown font: {font}",
    "fsafe.err.incomplete_desc":    "Incomplete font description for {font}",
    "fsafe.err.unsupported_type":   "Unsupported font type for {font}",
    "fsafe.err.invalid_row_count":  "Invalid row/pointer count for {font}",
    "fsafe.err.ptr_table_outside":  "Pointer table outside EXE for {font}",
    "fsafe.err.ptr_table_size":     "Pointer table size mismatch for {font}: {got} bytes for {ptrs} pointers",
    "fsafe.err.glyph_range":        "Glyph range outside EXE or overlaps pointer table for {font}",
    "fsafe.err.ptr_target":         "Glyph pointer {idx} for {font} targets {addr:#x} outside {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "First glyph for {font} does not start at glyph_start",
    "fsafe.err.slot_invalid":       "Invalid/overlapping glyph slot at {addr:#x} in {font}",
    "fsafe.err.dynamic_uneven":     "Dynamic glyph slot at {addr:#x} has an uneven row layout",
    "fsafe.err.dynamic_capacity":   "Dynamic glyph slot at {addr:#x} has unsupported capacity {cap}",
    "fsafe.err.width_exceeds_slot": "Glyph width {width} at {addr:#x} exceeds slot capacity {max}",
    "fsafe.err.fixed_size":         "Fixed glyph slot at {addr:#x} has size {got}, expected {expected}",
    "fsafe.err.fixed_width":        "Fixed glyph width {width} at {addr:#x} is invalid",
    "fsafe.err.glyph_exceeds_slot": "Glyph data at {addr:#x} exceeds its physical slot",
    "fsafe.err.model_char_count":   "Font model has {got} characters, expected {expected}",
    "fsafe.err.invalid_char_idx":   "Invalid character index {idx}",
    "fsafe.err.no_glyph_obj":       "Character {idx} has no glyph object",
    "fsafe.err.invalid_glyph_off":  "Character {idx} has an invalid glyph offset",
    "fsafe.err.alias_not_shared":   "Aliases at {addr:#x} do not share one canonical glyph object",
    "fsafe.err.alias_meta":         "Alias metadata mismatch for character {idx}",
    "fsafe.err.glyph_start":        "Font model does not begin at glyph_start",
    "fsafe.err.slot_boundary":      "Slot boundary mismatch at {addr:#x}",
    "fsafe.err.slot_outside_exe":   "Slot at {addr:#x} is outside the EXE",
    "fsafe.err.dynamic_cap_meta":   "Invalid dynamic slot capacity at {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "Stored capacity mismatch at {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "Width/row-class exceeds slot at {addr:#x}",
    "fsafe.err.fixed_slot":         "Invalid fixed slot at {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "Stored fixed capacity mismatch at {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Invalid fixed width at {addr:#x}",
    "fsafe.err.bitmap_value":       "Bitmap value outside row class at {addr:#x}",
    "fsafe.err.serial_exceeds":     "Glyph serialization exceeds slot at {addr:#x}",
    "fsafe.err.bpr_conversion":     "Unsupported bytes-per-row conversion",
    "fsafe.err.width_not_int":      "Width must be an integer",
    "fsafe.err.width_exceeds_max":  "Width {width} exceeds this glyph slot (max {max})",
    "fsafe.err.fixed_width_range":  "FLOW/MICRO width must remain between 1 and 8",
    "fsafe.err.clipboard_invalid":  "Clipboard does not contain a valid glyph",
    "fsafe.err.height_mismatch":    "Incompatible glyph height: source {src}, target {tgt}",
    "fsafe.err.clip_type_invalid":  "Clipboard font type is invalid",
    "fsafe.err.clip_bpr_invalid":   "Clipboard row class is invalid",
    "fsafe.err.clip_fixed_width":   "Clipboard fixed width is invalid",
    "fsafe.err.clip_bitmap":        "Clipboard bitmap is invalid",
    "fsafe.err.target_too_wide":    "Glyph is wider than a FLOW/MICRO target",
    "fsafe.err.paste_exceeds_slot": "Glyph width {width} exceeds target slot capacity {max}",
    "fsafe.err.write_exceeds":      "Glyph write at {addr:#x} exceeds its slot",
    "fsafe.err.ptr_alias_struct":   "Font model no longer matches the EXE pointer/alias structure",
    "fsafe.err.changed_outside":    "Font serialization changed bytes outside glyph slots",
    "fsafe.err.readback_mismatch":  "Font readback mismatch at {addr:#x}",
    "fsafe.err.import_truncated":   "Import is truncated before glyph {idx}",
    "fsafe.err.import_width":       "Imported width {width} exceeds glyph {idx} capacity {cap}",
    "fsafe.err.import_fixed_width": "Imported fixed width {width} is invalid at glyph {idx}",
    "fsafe.err.import_trunc_body":  "Import is truncated inside glyph {idx}",
    "fsafe.err.import_trailing":    "Import has {n} unexpected trailing bytes",
    "fsafe.err.no_dir":             "Target directory does not exist: {dir}",
    "fsafe.err.short_write":        "Short write: {written} of {total} bytes",
    "fsafe.err.readback_tmp":       "Temporary-file readback mismatch",
    "fsafe.err.no_backup_src":      "Cannot back up a missing original file",
    "fsafe.err.buffers_differ":     "Font buffers differ in {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "Font buffers do not have the same pre-commit state",

    # ── diff_preview.py ───────────────────────────────────────────────────────
    "diff.err.no_raw":              "Entry {sid} does not contain strict raw bytes",
    "diff.err.no_ref_type":         "Entry {sid} has no reference type",
    "diff.err.range_outside":       "Baseline range for {label} is outside the EXE",
    "diff.err.not_nul_term":        "Baseline string {label} is not NUL-terminated",
    "diff.err.ptr_normal_outside":  "Normal pointer source outside EXE: {addr:#x}",
    "diff.err.ptr_code_outside":    "Code pointer source outside EXE: {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Unknown pointer kind: {kind}",
    "diff.err.ptr_base_mismatch":   "Pointer {addr:#x} has base {got}, expected {expected}",
    "diff.err.ptr_outside_ranges":  "Pointer {addr:#x} targets outside Repack ranges: {target:#x}",
    "diff.err.no_unique_sid":       "Current entries do not have unique string_ids",
    "diff.err.fixed_id":            "Invalid fixed string_id: {sid}",
    "diff.err.unknown_fixed_slot":  "Unknown fixed baseline slot: {sid}",
    "diff.err.ambiguous_targets":   "Baseline pointer sources for {sid} have {n} targets",
    "diff.err.baseline_failed":     "Baseline reconstruction failed: {detail}",
    "diff.err.repack_mutated":      "Authoritative Repack dry-run mutated its inputs",
    "diff.err.range_cross_end":     "Repacked string crosses block end at {addr:#x}",
    "diff.err.pending_preflight":   "Unknown pending string_id: {sid}",
    "diff.err.pending_not_bytes":   "Pending replacement for {sid} is not raw bytes",
    "diff.err.fixed_exceed":        "Fixed string {sid} exceeds {max} bytes ({got} bytes)",
    "diff.err.dup_normal_ptr":      "Duplicate normal pointer source: {addr:#x}",
    "diff.err.dup_code_ptr":        "Duplicate code pointer source: {addr:#x}",
    "diff.err.alias_not_canonical": "Aliases at {addr:#x} are not canonical",
    "diff.err.ptr_table_changed":   "Font pointer table changed for {font}",
    "diff.err.glyph_set_changed":   "Physical glyph set changed for {font}",
    "diff.err.alias_set_changed":   "Alias set changed at {addr:#x} in {font}",
    "diff.err.meta_reconstruct":    "String metadata could not be reconstructed: {error}",
    "diff.err.no_font_key":         "Pending font model has no font key",
    "diff.err.font_preview_failed": "Pending font preview failed: {error}",
    "diff.err.sid_sets_differ":     "Baseline/current string_id sets differ",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "Preview mutated baseline_data",
    "diff.err.mutated_current":     "Preview mutated current_data",
    "diff.err.mutated_entries":     "Preview mutated current entries",
    "diff.err.mutated_font":        "Preview mutated the pending font model",
    "diff.err.baseline_repack":     "Baseline Repack failed: {detail}",
    "diff.err.unknown_baseline":    "Unknown baseline validation failure",
    "diff.err.unknown_baseline_repack": "Unknown baseline Repack failure",

    # ── repack_validator.py ───────────────────────────────────────────────────
    "repack.err.encoding":          "String {sid} contains a character that cannot be encoded",
    "repack.err.site_outside":      "Relocation site outside file: {addr:#x}",
    "repack.err.missing_code_ptrs": "Missing code pointers: {addrs}",
    "repack.err.extra_code_ptrs":   "Unexpected code pointers: {addrs}",
    "repack.err.mismatched_ptrs":   "Mismatched code pointers: {addrs}",
    "repack.err.no_sid":            "Entry at {addr:#x} has no string_id",
    "repack.err.dup_sid":           "Duplicate string_id: {sid}",
    "repack.err.fixed_has_ptrs":    "Fixed entry {sid} unexpectedly has pointers",
    "repack.err.dup_normal_src":    "Duplicate normal pointer source: {addr:#x}",
    "repack.err.uninv_normal_src":  "Uninventoried normal pointer source: {addr:#x}",
    "repack.err.normal_target":     "Normal pointer {src:#x} targets {expected:#x}, entry is {actual:#x}",
    "repack.err.dup_code_src":      "Duplicate code pointer source: {addr:#x}",
    "repack.err.uninv_code_src":    "Uninventoried code pointer source: {addr:#x}",
    "repack.err.code_target":       "Code pointer {src:#x} targets {expected:#x}, entry is {actual:#x}",
    "repack.err.unowned_normal":    "{n} relocation-backed normal pointers are not owned",
    "repack.err.unowned_code":      "{n} relocation-backed code pointers are not owned",
    "repack.err.unknown_fixed":     "Unknown fixed string: {addr:#x}",
    "repack.err.fixed_slot_size":   "Fixed string exceeds slot at {addr:#x}",
    "repack.err.fixed_mismatch":    "Fixed string bytes mismatch at {addr:#x}",
    "repack.err.outside_ranges":    "String outside valid ranges: {addr:#x}",
    "repack.err.crosses_range":     "String crosses range end: {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "String bytes/NUL mismatch at {addr:#x}",
    "repack.err.illegal_overlap":   "Illegal string overlap: {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Unknown occupied bytes in range {idx}: {n} bytes, first {addr:#x}",
    "repack.err.entry_outside":     "Entry outside valid ranges: {addr:#x}",
    "repack.err.range_overflow":    "Range {idx} overflow: {required} > {total}",
    "repack.err.ptr_value_range":   "Pointer value outside 16-bit range: {value:#x}",
    "repack.err.normal_src_file":   "Normal pointer source outside file: {addr:#x}",
    "repack.err.code_src_file":     "Code pointer source outside file: {addr:#x}",
    "repack.err.suffix_chain":      "Unresolved suffix-sharing chain",
    "repack.err.file_size_changed": "File size changed",
    "repack.err.extra_diffs":       "Unexpected changed bytes outside ranges/pointer offsets: {n}, first {addr:#x}",

    # ── string_exchange.py ────────────────────────────────────────────────────
    "xchg.err.not_serialisable":    "Value cannot be canonicalised: {error}",
    "xchg.err.not_raw_text":        "Entry {sid} does not contain strict raw-byte text",
    "xchg.err.no_ref_type":         "Entry {sid} has no supported reference type",
    "xchg.err.charmap_not_obj":     "CharMap must be an object",
    "xchg.err.invalid_key":         "Invalid CharMap byte key: {key!r}",
    "xchg.err.key_not_one_byte":    "CharMap key must identify one byte: {key!r}",
    "xchg.err.invalid_char":        "Invalid CharMap character: {char!r}",
    "xchg.err.conflict_key":        "Conflicting CharMap key: {key!r}",
    "xchg.err.ambiguous_char":      "Ambiguous CharMap character: {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF cannot be exported as visible text",
    "xchg.err.no_sid":              "Every entry must have a string_id",
    "xchg.err.dup_sid":             "Duplicate string_id in live entries",
    "xchg.err.no_charmap":          "No confirmed CharMap/font codes for {font}",
    "xchg.err.outside_repack":      "Entry {sid} is outside all Repack blocks",
    "xchg.err.unknown_fixed_slot":  "Unknown fixed slot for {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR and LF are not allowed in imported strings",
    "xchg.err.unconfirmed_byte":    "Unconfirmed byte-like character U+{cp:04X} must use \\xNN",
    "xchg.err.trailing_backslash":  "Trailing backslash in exchange text",
    "xchg.err.bad_escape":          "Backslash must be escaped as \\\\ or form \\xNN",
    "xchg.err.nul_byte_escape":     "NUL, CR and LF byte escapes are not allowed",
    "xchg.err.use_visible":         "Byte 0x{byte:02X} must use its confirmed visible representation",
    "xchg.err.new_dup_escape":      "New or duplicated byte escape \\x{byte:02X}",
    "xchg.err.control_token":       "Invalid control token: {token!r}",
    "xchg.err.token_outside_font":  "Control token outside active font: {token!r}",
    "xchg.err.unconfirmed_intro":   "Unconfirmed byte 0x{byte:02X} was introduced or duplicated",
    "xchg.err.not_utf8":            "Import is not valid UTF-8",
    "xchg.err.invalid_json":        "Invalid or truncated JSON: {error}",
    "xchg.err.root_not_obj":        "Exchange document root must be an object",
    "xchg.err.dup_json_key":        "Duplicate JSON key: {key!r}",
    "xchg.err.invalid_constant":    "Invalid JSON numeric constant: {value}",
    "xchg.err.schema_mismatch":     "Top-level schema fields do not match version 1",
    "xchg.err.bad_format":          "Unsupported string exchange format",
    "xchg.err.bad_version":         "Unsupported string exchange version",
    "xchg.err.no_profile_id":       "profile_id must be a non-empty string",
    "xchg.err.bad_entry_count":     "entry_count must be a non-negative integer",
    "xchg.err.entries_not_array":   "entries must be an array",
    "xchg.err.count_mismatch":      "entry_count does not match entries",
    "xchg.err.entry_schema":        "Entry schema fields do not match version 1",
    "xchg.err.no_string_id":        "string_id must be a non-empty string",
    "xchg.err.dup_entry_id":        "Duplicate string_id: {sid}",
    "xchg.err.invalid_kind":        "Invalid kind for {sid}",
    "xchg.err.editable_not_bool":   "editable must be boolean for {sid}",
    "xchg.err.suffix_not_array":    "suffix_links must be an array for {sid}",
    "xchg.err.suffix_link_schema":  "Invalid suffix link schema for {sid}",
    "xchg.err.suffix_role":         "Invalid suffix role for {sid}",
    "xchg.err.suffix_peer":         "Invalid suffix peer for {sid}",
    "xchg.err.suffix_offset":       "Invalid suffix offset for {sid}",
    "xchg.err.no_font":             "Invalid font for {sid}",
    "xchg.err.invalid_block":       "Invalid repack_block for {sid}",
    "xchg.err.invalid_ptr_count":   "Invalid {field} for {sid}",
    "xchg.err.invalid_capacity":    "Invalid fixed capacity for {sid}",
    "xchg.err.bad_hash":            "{field} must be an uppercase SHA-256",
    "xchg.err.source_text_str":     "source_text must be a string for {sid}",
    "xchg.err.translated_type":     "translated_text must be null or string for {sid}",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 does not match entry hashes",
    "xchg.err.wrong_profile":       "Wrong profile: {got!r}, expected {expected!r}",
    "xchg.err.structure_mismatch":  "Profile structure fingerprint mismatch",
    "xchg.err.charmap_mismatch":    "CharMap fingerprint mismatch",
    "xchg.err.entry_count_mismatch": "Import entry count does not match the loaded EXE",
    "xchg.err.missing_sid":         "Missing string_id: {sid}",
    "xchg.err.unknown_sid":         "Unknown string_id: {sid}",
    "xchg.err.manipulated_field":   "Manipulated {field} for {sid}",
    "xchg.err.source_hash":         "source_text/hash mismatch for {sid}",
    "xchg.err.token_mismatch":      "Protected token mismatch for {sid}",
    "xchg.err.layout_mismatch":     "Protected whitespace/layout mismatch for {sid}",
    "xchg.err.read_only":           "Suffix entry is read-only: {sid}",
    "xchg.err.fixed_exceeds":       "Fixed string {sid} exceeds {cap} bytes",
    "xchg.err.stale_conflict":      "Stale source conflict for {sid}",
    "xchg.err.escape_changed":      "Unconfirmed byte escapes changed for {sid}",
    "xchg.err.unknown_sid_replace": "Replacement set contains an unknown string_id",
    "xchg.err.replace_not_bytes":   "Replacement for {sid} is not raw bytes",
    "xchg.err.fixed_exceed_import": "Fixed string {sid} exceeds {max} bytes",
    "xchg.err.repack_blocked":      "Import Repack blocked: {detail}",
    "xchg.err.suffix_changed":      "Import would change suffix-sharing relationships",
    "xchg.err.font_validation":     "Import font validation failed: {error}",
    "xchg.err.unknown_repack":      "Unknown Repack validation failure",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Invalid filter metadata at row {idx}",
    "sfilter.err.dup_sid":        "Missing or duplicate string_id at row {idx}",
    "sfilter.err.invalid_kind":   "Invalid string kind for {sid}: {kind!r}",
    "sfilter.err.invalid_font":   "Invalid effective font for {sid}",
    "sfilter.err.invalid_text":   "Invalid searchable text for {sid}",
    "sfilter.err.invalid_preview":"Invalid preview status for {sid}",
    "sfilter.err.invalid_override":"Invalid status override for {sid}",
    "sfilter.err.query_not_text": "Search query must be text",
    "sfilter.err.unknown_kind":   "Unknown Kind filter: {kind!r}",
    "sfilter.err.font_empty":     "Font filter must be a non-empty name",
    "sfilter.err.unknown_change": "Unknown Change filter: {change!r}",
    "sfilter.err.unknown_status": "Unknown Status filter: {status!r}",
}
