TEXTS_IT = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "File",
    "menu.file.open":               "Apri EXE…",
    "menu.file.save_as":            "Salva con nome…",
    "menu.file.quit":               "Esci",
    "menu.tools":                   "Strumenti",
    "menu.tools.details":           "Modifiche / Dettagli…",
    "menu.tools.export":            "Esporta stringhe…",
    "menu.tools.import":            "Importa stringhe…",
    "menu.tools.autotranslate":     "Traduzione automatica",
    "menu.tools.translate_all":     "Traduci tutte le stringhe…",
    "menu.view":                    "Visualizza",
    "menu.view.strings":            "Stringhe",
    "menu.view.fonts":              "Editor font",
    "menu.view.settings":           "Impostazioni editor",
    "menu.view.language":           "Lingua",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "📁 Scegli EXE…",
    "header.save_as":               "💾 Salva con nome…",
    "header.profile":               "Profilo:",
    "header.profile_none":          "—",
    "header.no_file":               "Nessun file caricato.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  📝 Stringhe  ",
    "tab.fonts":                    "  🔤 Editor font  ",
    "tab.settings":                 "  ⚙ Impostazioni editor  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "🔍 Cerca:",
    "filter.toggle_closed":         "Filtra ▸",
    "filter.toggle_open":           "Filtra ▾",
    "filter.kind":                  "Tipo:",
    "filter.font":                  "Font:",
    "filter.change":                "Modifica:",
    "filter.status":                "Stato:",
    "filter.reset":                 "❌ Reimposta filtri",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Offset",
    "col.text":                     "Testo stringa",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Modifica testo (spazi evidenziati) ",
    "edit.apply":                   "✔ Applica modifica",
    "edit.stats":                   "Lunghezza totale: {n} caratteri | Spazi iniziali: {lead} | Spazi finali: {trail}",
    "edit.encoding_blocked":        "Codifica bloccata: {error}",
    "edit.diff_unavailable":        "Stato differenze non disponibile: {error}",
    "edit.fixed_rest":              "Spazio residuo fisso: {rest}/{cap} byte",
    "edit.block_rest":              "Spazio residuo condiviso di B{block} dopo tutte le modifiche: {rest} byte",
    "edit.block_preview":           "Spazio residuo condiviso di B{block}: anteprima richiesta",
    "edit.range_info":              "{kind} | {font} | byte {old}→{new} (Δ {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "🌐 Traduzione",
    "action.details":               "🔎 Modifiche / Dettagli…",
    "action.export":                "📤 Esporta…",
    "action.import":                "📥 Importa…",
    "action.font_assign":           "Assegnazione font…",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Motore:",
    "tr.from":                      "Da:",
    "tr.to":                        "A:",
    "tr.all":                       "⚡ Traduci tutto",
    "tr.translated":                "Testo tradotto:",
    "tr.apply":                     "✔ Applica traduzione",
    "tr.translating":               "Traduzione in corso...",
    "tr.error":                     "Errore: {error}",
    "tr.no_changes":                "Nessuna modifica da applicare.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Mappatura caratteri (CharMap) ",
    "settings.font_group":          " Assegnazione font ",
    "settings.font_auto":           "L'assegnazione è automatica.\nUna scelta diversa si applica solo alla\nstringa attualmente selezionata.",
    "settings.font_label":          "Font assegnato:",
    "settings.hint_group":          " Comportamento del salvataggio ",
    "settings.hint_text":           "Le assegnazioni CharMap e font vengono salvate\nimmediatamente e automaticamente.\n\nL'EXE viene scritto solo tramite\n„File → Salva con nome…“.",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} di {total} stringhe",
    "status.filter_pending":        "La visualizzazione del filtro è in attesa — applica o annulla prima la modifica.",
    "status.selection_blocked":     "Cambio selezione bloccato — applica o annulla prima la modifica.",
    "status.filter_unavailable":    "Filtro non disponibile: {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Modifica testo in sospeso",
    "dlg.pending_font.msg":         "Applica o annulla la modifica di testo o la traduzione in sospeso prima di cambiare il font associato.\n\nNessuna modifica effettuata.",
    "dlg.pending_charmap.msg":      "Applica o annulla la modifica di testo o la traduzione in sospeso prima di cambiare il CharMap.\n\nNessuna modifica effettuata.",
    "dlg.pending_translation.title": "Traduzione in sospeso",
    "dlg.pending_translation.switch": "Applicare la traduzione in sospeso prima di disattivare la traduzione automatica?\n\nSì = Applica, No = Annulla, Annulla = Mantieni aperta",
    "dlg.pending_translation.new":  "Applica o annulla la traduzione in sospeso prima di richiederne una nuova.\n\nNessuna modifica effettuata.",
    "dlg.text_blocked.title":       "Modifica testo bloccata",
    "dlg.text_blocked.translation": "Applica o annulla la traduzione in sospeso prima di applicare la modifica al testo.\n\nNessuna modifica effettuata.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "TRADUCI TUTTO",
    "dlg.translate_all.none":       "Nessuna stringa caricata.",
    "dlg.translate_all.confirm":    "Tradurre automaticamente tutte le {n} stringhe con '{engine}'?",
    "dlg.translate_all.window":     "Traduzione di TUTTE...",
    "dlg.translate_all.progress":   "{current}/{total}: {text}",
    "dlg.translate_all.blocked":    "TRADUZIONE TUTTA bloccata",
    "dlg.translate_all.unchanged":  "Nessun testo modificato. L'EXE non è stato ricompattato e rimane invariato.",
    "dlg.translate_all.nochange":   "Nessun testo o dato dell'EXE è stato modificato.\n\n{detail}",
    "dlg.translate_all.done":       "Completato",
    "dlg.translate_all.summary":    "Completato: {translated} tradotte, {unchanged} invariate, {blank} vuote.",
    "dlg.translate_all.suffix":     "\n{n} voci del gruppo di suffisso ignorate in sicurezza.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Esportazione bloccata",
    "dlg.export.failed":            "Esportazione non riuscita",
    "dlg.export.partial":           "Nessun file di esportazione parziale è stato scritto.\n\n{error}",
    "dlg.export.done":              "Esportazione completata",
    "dlg.export.done_msg":          "Esportate {n} stringhe.\n\n{path}",
    "dlg.export.status":            "Esportate {n} stringhe in {file}.",
    "fd.export":                    "Esporta stringhe",
    "dlg.import.blocked":           "Importazione bloccata",
    "dlg.import.nochange":          "Lo stato dell'editor non è stato modificato.\n\n{error}",
    "dlg.import.done":              "Importazione completata",
    "dlg.import.none":              "Profilo: {profile}\nStringhe modificate: 0\n\nLo stato dell'editor non è stato modificato.",
    "dlg.import.confirm":           "Profilo: {profile}\nStringhe da modificare: {n}\n\nApplicare completamente l'importazione validata?",
    "dlg.import.title":             "Importa stringhe",
    "dlg.import.done_msg":          "Profilo: {profile}\nStringhe modificate: {n}\n\nL'EXE non è stato salvato automaticamente.",
    "dlg.import.status":            "Importate {n} stringhe.",
    "fd.import":                    "Importa stringhe",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "Modifiche / Anteprima — {profile}",
    "dlg.preview.warn":             "Anteprima",
    "dlg.preview.load_first":       "Carica prima un eseguibile supportato.",
    "dlg.preview.failed":           "Anteprima non riuscita",
    "dlg.preview.close":            "Chiudi",
    "preview.tab.summary":          "Riepilogo",
    "preview.tab.strings":          "Stringhe",
    "preview.tab.blocks":           "Blocchi",
    "preview.tab.pointers":         "Puntatori",
    "preview.tab.fonts":            "Font",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Apri eseguibile",
    "fd.save_exe":                  "Salva eseguibile con nome",
    "dlg.load.failed":              "Caricamento non riuscito",
    "dlg.load.failed_msg":          "Il nuovo EXE non è stato caricato. Lo stato precedente dell'editor è invariato.\n\n{error}",
    "dlg.load.unsupported_status":  "Eseguibile non supportato. Modifica e salvataggio sono disabilitati.",
    "dlg.load.unsupported_label":   "NON SUPPORTATO",
    "dlg.load.font_failed":         "Inizializzazione font non riuscita. Il salvataggio è bloccato.",
    "dlg.load.integrity_status":    "Controllo di integrità non riuscito: {error}",
    "dlg.load.integrity_title":     "Controllo di integrità non riuscito",
    "dlg.load.integrity_msg":       "Le modifiche possono essere esaminate, ma Ricompattazione e Salvataggio sono bloccati.\n\n{errors}",
    "dlg.unsaved.title":            "Modifiche non salvate",
    "dlg.unsaved.load":             "L'EXE corrente contiene modifiche non salvate o in sospeso.\n\nAnnullarle e caricare un altro file?",
    "dlg.unsaved.close":            "L'EXE corrente contiene modifiche non salvate o in sospeso.\n\nAnnullarle e chiudere l'editor?",
    "dlg.save.unsupported":         "Non supportato",
    "dlg.save.unsupported_msg":     "Carica un eseguibile supportato prima di salvare.",
    "dlg.save.blocked":             "Salvataggio bloccato",
    "dlg.save.verify":              "Impossibile verificare il sorgente caricato: {error}",
    "dlg.save.external":            "Il file sorgente caricato è cambiato al di fuori dell'editor. Non è stato sovrascritto.",
    "dlg.save.done":                "Salvataggio completato",
    "dlg.save.noop":                "Il file originale è già identico a livello di byte e invariato.",
    "dlg.save.overwrite_title":     "Sovrascrivere l'originale caricato",
    "dlg.save.overwrite_msg":       "Sostituire l'originale caricato con l'EXE modificato?\n\nPrima verrà creato un backup identico a livello di byte.",
    "dlg.save.failed":              "Salvataggio non riuscito",
    "dlg.save.failed_msg":          "Nessun file di destinazione parziale è stato scritto.\n\n{error}",
    "dlg.save.done_msg":            "Eseguibile salvato in:\n{path}{backup}",
    "dlg.save.backup":              "\nBackup: {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "È necessaria una convalida Ricompattazione riuscita.",
    "block.font_invalid":           "Convalida del font non riuscita.",
    "block.font_pending":           "Applica o annulla le modifiche al font in sospeso prima di salvare.",
    "block.text_pending":           "Applica o annulla la modifica al testo in sospeso prima di salvare.",
    "block.generic":                "Il salvataggio è attualmente bloccato.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Font:",
    "font.apply":                   "Applica modifiche",
    "font.load_first":              "Carica prima un EXE.",
    "font.characters":              " Caratteri ",
    "font.matrix":                  " Matrice pixel (clic/trascina) ",
    "font.props":                   " Proprietà ",
    "font.width":                   "Larghezza (px):",
    "font.tools":                   " Strumenti ",
    "font.copy":                    "📋 Copia",
    "font.paste":                   "📌 Incolla",
    "font.clear":                   "🧹 Cancella",
    "font.invert":                  "🔄 Inverti",
    "font.file":                    " File ",
    "font.import":                  "📥 Importa",
    "font.export":                  "📤 Esporta",
    "font.edit_charmap":            "Modifica mappatura caratteri…",
    "font.charmap_title":           "Mappatura caratteri",
    "font.charmap_title_for":       "Mappatura caratteri di {font}:",
    "font.remove":                  "✖ Rimuovi",
    "font.blocked_title":           "Operazione font bloccata",
    "font.blocked_status":          "✖ Operazione font bloccata: {error}",
    "font.no_profile":              "Nessun profilo font per '{profile}'.",
    "font.summary":                 "{font}  •  {chars} caratteri  •  {unique} glifi unici",
    "font.pending_title":           "Modifiche font in sospeso",
    "font.pending_msg":             "Applicare le modifiche in sospeso a {font} prima di cambiare?\n\nSì = Applica, No = Annulla, Annulla = Resta",
    "font.no_data":                 "Nessun dato",
    "font.no_data_msg":             "Carica un EXE e seleziona prima un font.",
    "font.no_exe_msg":              "Carica prima un file EXE.",
    "font.fd_export":               "Esporta font",
    "font.fd_import":               "Importa font ({font})",
    "font.export_error":            "Errore di esportazione",
    "font.exported":                "✔ Esportato {font} → {file}",
    "font.imported":                "✔ Importati {n} glifi da {file} in {font}",
    "font.written":                 "✔ {n} glifi scritti nei dati EXE  ({font})",
    "font.written_title":           "Font scritto",
    "font.written_msg":             "{n} glifi unici modificati nei dati EXE.\nUsa 'Salva con nome...' nella barra superiore per salvare il file.",
    "font.no_selection":            "Nessuna selezione",
    "font.no_selection_msg":        "Seleziona prima un carattere.",
    "font.empty_clipboard":         "Appunti vuoti",
    "font.empty_clipboard_msg":     "Copia prima un carattere (Ctrl+C).",
    "font.copied":                  "✓ Copiato 0x{code:02X} '{char}' negli appunti",
    "font.pasted":                  "✓ Incollato in 0x{code:02X} '{char}'",
    "font.alias":                   "⚠ Alias di 0x{code:02X} ('{char}')\nModificando questo glifo si modifica anche l'originale.",
    "font.invalid_entry":           "Voce CharMap non valida",
    "font.invalid_entry_msg":       "Inserisci un carattere Unicode.",
    "font.invalid_byte":            "Byte CharMap non valido",
    # font_editor internal (non-GUI) messages
    "font.err.live_unavailable":    "Nessuno stato font supportato è caricato",
    "font.err.buffer_unavailable":  "Il buffer EXE attivo non è disponibile",
    "font.err.import_failed":       "Importazione non riuscita senza modifiche: {error}",
    "font.err.apply_failed":        "Applicazione non riuscita; i dati attivi non sono stati modificati: {error}",
    "font.err.paste_rejected":      "Incolla rifiutato senza modifiche: {error}",
    "font.err.initial_load":        "Il font iniziale non può essere caricato",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Configurazione",
    "utils.cfg.damaged":            "La configurazione esistente è danneggiata e non è stata sostituita.\nLe modifiche alla configurazione rimangono bloccate finché non viene riparata o rimossa.\n\n{reason}",
    "utils.cfg.locked":             "Le modifiche alla configurazione non vengono salvate finché la configurazione esistente è danneggiata.\n\n{reason}",
    "utils.cfg.save_failed":        "Impossibile salvare la configurazione: {error}",

    # ── build_exe.py ──────────────────────────────────────────────────────────
    "build.err.no_entry":           "Punto di ingresso mancante: {path}",
    "build.err.no_config":          "Sorgente configurazione mancante: {path}",
    "build.err.no_icon":            "Risorsa icona mancante: {path}",
    "build.err.pyi_failed":         "PyInstaller non riuscito con codice di uscita {code}",
    "build.err.no_exe":             "L'eseguibile previsto non è stato prodotto: {path}",
    "build.err.config_mismatch":    "La configurazione della release non è identica a livello di byte al sorgente",
    "build.err.key_nonempty":       "deepl_key.txt deve essere vuoto",
    "build.step.config":            "[1/6] sorgente configurazione  {hash}  {size} B",
    "build.step.icon":              "      sorgente icona    {hash}  {size} B",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] compilato  {hash}  {size} B",
    "build.step.removed_obsolete":  "      release precedente rimossa: {name}",
    "build.step.release_exe":       "[4/6] exe release -> {path}",
    "build.step.config_verified":   "[5/6] configurazione release verificata  {hash}",
    "build.step.key_file":          "[6/6] deepl_key.txt release  0 B",
    "build.step.release_header":    "\nRelease:",

    # ── translator.py ─────────────────────────────────────────────────────────
    "tr.err.markers_changed":       "I marcatori di traduzione protetti sono cambiati (mancanti={missing}, imprevisti={unexpected})",
    "tr.err.marker_count":          "Il conteggio dei marcatori protetti è cambiato: {marker}",
    "tr.err.marker_unrestored":     "Rimane un marcatore di traduzione non ripristinato",
    "tr.err.no_text":               "Il traduttore non ha restituito testo",
    "tr.err.lingva_unreachable":    "Tutti i server sono inaccessibili (403/503). Prova Google Translate o MyMemory.",
    "tr.err.mymemory":              "Errore MyMemory {status}: {detail}",
    "tr.err.deepl_no_key":          "Chiave DeepL non trovata.\nRegistrati gratuitamente su https://www.deepl.com/pro#developer\nPoi salva la chiave in deepl_key.txt.",
    "tr.err.argos_not_installed":   "Argos Translate non è installato.\nEsegui: pip install argostranslate\ne scarica i pacchetti linguistici.",
    "tr.err.argos_no_package":      "Pacchetto Argos '{src}→{tgt}' non installato.\nScaricalo con argostranslate.package.",
    "tr.err.argos_no_translation":  "Nessuna traduzione Argos disponibile per {src}→{tgt}.",

    # ── charmap.py ───────────────────────────────────────────────────────────
    "charmap.err.invalid_key":      "Chiave byte CharMap non valida: {key}",
    "charmap.err.key_not_one_byte": "La chiave CharMap deve identificare un byte: {key}",
    "charmap.err.value_not_char":   "Il valore CharMap deve essere un solo carattere: {value}",
    "charmap.err.ambiguous":        "Carattere CharMap ambiguo: {char}",
    "charmap.err.outside_font":     "Il byte 0x{byte:02X} per {char!r} è esterno al font attivo",
    "charmap.err.no_codepoint":     "Il carattere U+{cp:04X} alla posizione {pos} non ha una voce CharMap",
    "charmap.err.conflict":         "Il carattere {char!r} alla posizione {pos} è in conflitto con il glifo {glyph!r}",

    # ── font_safety.py ───────────────────────────────────────────────────────
    "fsafe.err.invalid_width":      "Larghezza glifo non valida: {width!r}",
    "fsafe.err.unknown_font":       "Font sconosciuto: {font}",
    "fsafe.err.incomplete_desc":    "Descrizione font incompleta per {font}",
    "fsafe.err.unsupported_type":   "Tipo di font non supportato per {font}",
    "fsafe.err.invalid_row_count":  "Numero di righe/puntatori non valido per {font}",
    "fsafe.err.ptr_table_outside":  "Tabella puntatori esterna all'EXE per {font}",
    "fsafe.err.ptr_table_size":     "Dimensione tabella puntatori non corrispondente per {font}: {got} byte per {ptrs} puntatori",
    "fsafe.err.glyph_range":        "Intervallo glifi esterno all'EXE o sovrapposto alla tabella puntatori per {font}",
    "fsafe.err.ptr_target":         "Il puntatore glifo {idx} per {font} punta a {addr:#x}, fuori da {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "Il primo glifo per {font} non inizia a glyph_start",
    "fsafe.err.slot_invalid":       "Slot glifo non valido/sovrapposto a {addr:#x} in {font}",
    "fsafe.err.dynamic_uneven":     "Lo slot glifo dinamico a {addr:#x} ha una disposizione delle righe non uniforme",
    "fsafe.err.dynamic_capacity":   "Lo slot glifo dinamico a {addr:#x} ha capacità non supportata {cap}",
    "fsafe.err.width_exceeds_slot": "La larghezza glifo {width} a {addr:#x} supera la capacità dello slot {max}",
    "fsafe.err.fixed_size":         "Lo slot glifo fisso a {addr:#x} ha dimensione {got}, attesa {expected}",
    "fsafe.err.fixed_width":        "La larghezza glifo fisso {width} a {addr:#x} non è valida",
    "fsafe.err.glyph_exceeds_slot": "I dati del glifo a {addr:#x} superano il relativo slot fisico",
    "fsafe.err.model_char_count":   "Il modello font ha {got} caratteri, attesi {expected}",
    "fsafe.err.invalid_char_idx":   "Indice carattere non valido {idx}",
    "fsafe.err.no_glyph_obj":       "Il carattere {idx} non ha un oggetto glifo",
    "fsafe.err.invalid_glyph_off":  "Il carattere {idx} ha un offset glifo non valido",
    "fsafe.err.alias_not_shared":   "Gli alias a {addr:#x} non condividono un unico oggetto glifo canonico",
    "fsafe.err.alias_meta":         "Metadati alias non corrispondenti per il carattere {idx}",
    "fsafe.err.glyph_start":        "Il modello font non inizia a glyph_start",
    "fsafe.err.slot_boundary":      "Limite slot non corrispondente a {addr:#x}",
    "fsafe.err.slot_outside_exe":   "Lo slot a {addr:#x} è esterno all'EXE",
    "fsafe.err.dynamic_cap_meta":   "Capacità slot dinamico non valida a {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "Capacità memorizzata non corrispondente a {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "Larghezza/classe riga supera lo slot a {addr:#x}",
    "fsafe.err.fixed_slot":         "Slot fisso non valido a {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "Capacità fissa memorizzata non corrispondente a {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Larghezza fissa non valida a {addr:#x}",
    "fsafe.err.bitmap_value":       "Valore bitmap esterno alla classe riga a {addr:#x}",
    "fsafe.err.serial_exceeds":     "La serializzazione del glifo supera lo slot a {addr:#x}",
    "fsafe.err.bpr_conversion":     "Conversione byte-per-riga non supportata",
    "fsafe.err.width_not_int":      "La larghezza deve essere un intero",
    "fsafe.err.width_exceeds_max":  "La larghezza {width} supera questo slot glifo (max {max})",
    "fsafe.err.fixed_width_range":  "La larghezza FLOW/MICRO deve rimanere tra 1 e 8",
    "fsafe.err.clipboard_invalid":  "Gli appunti non contengono un glifo valido",
    "fsafe.err.height_mismatch":    "Altezza glifo incompatibile: sorgente {src}, destinazione {tgt}",
    "fsafe.err.clip_type_invalid":  "Il tipo di font negli appunti non è valido",
    "fsafe.err.clip_bpr_invalid":   "La classe riga negli appunti non è valida",
    "fsafe.err.clip_fixed_width":   "La larghezza fissa negli appunti non è valida",
    "fsafe.err.clip_bitmap":        "La bitmap negli appunti non è valida",
    "fsafe.err.target_too_wide":    "Il glifo è più largo di una destinazione FLOW/MICRO",
    "fsafe.err.paste_exceeds_slot": "La larghezza glifo {width} supera la capacità dello slot di destinazione {max}",
    "fsafe.err.write_exceeds":      "La scrittura del glifo a {addr:#x} supera il relativo slot",
    "fsafe.err.ptr_alias_struct":   "Il modello font non corrisponde più alla struttura puntatori/alias dell'EXE",
    "fsafe.err.changed_outside":    "La serializzazione del font ha modificato byte esterni agli slot glifo",
    "fsafe.err.readback_mismatch":  "Discrepanza nella rilettura del font a {addr:#x}",
    "fsafe.err.import_truncated":   "L'importazione è troncata prima del glifo {idx}",
    "fsafe.err.import_width":       "La larghezza importata {width} supera la capacità {cap} del glifo {idx}",
    "fsafe.err.import_fixed_width": "La larghezza fissa importata {width} non è valida al glifo {idx}",
    "fsafe.err.import_trunc_body":  "L'importazione è troncata all'interno del glifo {idx}",
    "fsafe.err.import_trailing":    "L'importazione contiene {n} byte finali imprevisti",
    "fsafe.err.no_dir":             "La directory di destinazione non esiste: {dir}",
    "fsafe.err.short_write":        "Scrittura parziale: {written} di {total} byte",
    "fsafe.err.readback_tmp":       "Discrepanza nella rilettura del file temporaneo",
    "fsafe.err.no_backup_src":      "Impossibile eseguire il backup di un file originale mancante",
    "fsafe.err.buffers_differ":     "I buffer font differiscono in {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "I buffer font non hanno lo stesso stato precedente al commit",

    # ── diff_preview.py ───────────────────────────────────────────────────────
    "diff.err.no_raw":              "La voce {sid} non contiene byte raw rigorosi",
    "diff.err.no_ref_type":         "La voce {sid} non ha un tipo di riferimento",
    "diff.err.range_outside":       "L'intervallo di base per {label} è esterno all'EXE",
    "diff.err.not_nul_term":        "La stringa di base {label} non è terminata da NUL",
    "diff.err.ptr_normal_outside":  "Sorgente puntatore normale esterna all'EXE: {addr:#x}",
    "diff.err.ptr_code_outside":    "Sorgente puntatore codice esterna all'EXE: {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Tipo di puntatore sconosciuto: {kind}",
    "diff.err.ptr_base_mismatch":   "Il puntatore {addr:#x} ha base {got}, atteso {expected}",
    "diff.err.ptr_outside_ranges":  "Il puntatore {addr:#x} punta fuori dagli intervalli Repack: {target:#x}",
    "diff.err.no_unique_sid":       "Le voci correnti non hanno string_id univoci",
    "diff.err.fixed_id":            "string_id fisso non valido: {sid}",
    "diff.err.unknown_fixed_slot":  "Slot di base fisso sconosciuto: {sid}",
    "diff.err.ambiguous_targets":   "Le sorgenti puntatore di base per {sid} hanno {n} destinazioni",
    "diff.err.baseline_failed":     "Ricostruzione della base non riuscita: {detail}",
    "diff.err.repack_mutated":      "La simulazione Repack autorevole ha modificato i propri input",
    "diff.err.range_cross_end":     "La stringa ricompattata oltrepassa la fine del blocco a {addr:#x}",
    "diff.err.pending_preflight":   "string_id in sospeso sconosciuto: {sid}",
    "diff.err.pending_not_bytes":   "La sostituzione in sospeso per {sid} non è composta da byte raw",
    "diff.err.fixed_exceed":        "La stringa fissa {sid} supera {max} byte ({got} byte)",
    "diff.err.dup_normal_ptr":      "Sorgente puntatore normale duplicata: {addr:#x}",
    "diff.err.dup_code_ptr":        "Sorgente puntatore codice duplicata: {addr:#x}",
    "diff.err.alias_not_canonical": "Gli alias a {addr:#x} non sono canonici",
    "diff.err.ptr_table_changed":   "La tabella puntatori del font è cambiata per {font}",
    "diff.err.glyph_set_changed":   "L'insieme fisico dei glifi è cambiato per {font}",
    "diff.err.alias_set_changed":   "L'insieme di alias è cambiato a {addr:#x} in {font}",
    "diff.err.meta_reconstruct":    "I metadati della stringa non possono essere ricostruiti: {error}",
    "diff.err.no_font_key":         "Il modello font in sospeso non ha una chiave font",
    "diff.err.font_preview_failed": "Anteprima del font in sospeso non riuscita: {error}",
    "diff.err.sid_sets_differ":     "Gli insiemi string_id di base/correnti differiscono",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "L'anteprima ha modificato baseline_data",
    "diff.err.mutated_current":     "L'anteprima ha modificato current_data",
    "diff.err.mutated_entries":     "L'anteprima ha modificato le voci correnti",
    "diff.err.mutated_font":        "L'anteprima ha modificato il modello font in sospeso",
    "diff.err.baseline_repack":     "Repack della base non riuscito: {detail}",
    "diff.err.unknown_baseline":    "Errore di convalida della base sconosciuto",
    "diff.err.unknown_baseline_repack": "Errore Repack della base sconosciuto",

    # ── repack_validator.py ───────────────────────────────────────────────────
    "repack.err.encoding":          "La stringa {sid} contiene un carattere che non può essere codificato",
    "repack.err.site_outside":      "Sito di rilocazione esterno al file: {addr:#x}",
    "repack.err.missing_code_ptrs": "Puntatori codice mancanti: {addrs}",
    "repack.err.extra_code_ptrs":   "Puntatori codice imprevisti: {addrs}",
    "repack.err.mismatched_ptrs":   "Puntatori codice non corrispondenti: {addrs}",
    "repack.err.no_sid":            "La voce a {addr:#x} non ha string_id",
    "repack.err.dup_sid":           "string_id duplicato: {sid}",
    "repack.err.fixed_has_ptrs":    "La voce fissa {sid} ha inaspettatamente dei puntatori",
    "repack.err.dup_normal_src":    "Sorgente puntatore normale duplicata: {addr:#x}",
    "repack.err.uninv_normal_src":  "Sorgente puntatore normale non inventariata: {addr:#x}",
    "repack.err.normal_target":     "Il puntatore normale {src:#x} punta a {expected:#x}, mentre la voce è {actual:#x}",
    "repack.err.dup_code_src":      "Sorgente puntatore codice duplicata: {addr:#x}",
    "repack.err.uninv_code_src":    "Sorgente puntatore codice non inventariata: {addr:#x}",
    "repack.err.code_target":       "Il puntatore codice {src:#x} punta a {expected:#x}, mentre la voce è {actual:#x}",
    "repack.err.unowned_normal":    "{n} puntatori normali supportati da rilocazione non sono assegnati",
    "repack.err.unowned_code":      "{n} puntatori codice supportati da rilocazione non sono assegnati",
    "repack.err.unknown_fixed":     "Stringa fissa sconosciuta: {addr:#x}",
    "repack.err.fixed_slot_size":   "La stringa fissa supera lo slot a {addr:#x}",
    "repack.err.fixed_mismatch":    "Byte stringa fissa non corrispondenti a {addr:#x}",
    "repack.err.outside_ranges":    "Stringa fuori dagli intervalli validi: {addr:#x}",
    "repack.err.crosses_range":     "La stringa supera la fine dell'intervallo: {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "Byte/NUL della stringa non corrispondenti a {addr:#x}",
    "repack.err.illegal_overlap":   "Sovrapposizione illegale tra stringhe: {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Byte occupati sconosciuti nell'intervallo {idx}: {n} byte, primo {addr:#x}",
    "repack.err.entry_outside":     "Voce fuori dagli intervalli validi: {addr:#x}",
    "repack.err.range_overflow":    "Overflow intervallo {idx}: {required} > {total}",
    "repack.err.ptr_value_range":   "Valore puntatore fuori dall'intervallo a 16 bit: {value:#x}",
    "repack.err.normal_src_file":   "Sorgente puntatore normale esterna al file: {addr:#x}",
    "repack.err.code_src_file":     "Sorgente puntatore codice esterna al file: {addr:#x}",
    "repack.err.suffix_chain":      "Catena di condivisione suffissi non risolta",
    "repack.err.file_size_changed": "La dimensione del file è cambiata",
    "repack.err.extra_diffs":       "Byte modificati imprevisti fuori da intervalli/offset puntatore: {n}, primo {addr:#x}",

    # ── string_exchange.py ────────────────────────────────────────────────────
    "xchg.err.not_serialisable":    "Il valore non può essere canonizzato: {error}",
    "xchg.err.not_raw_text":        "La voce {sid} non contiene testo in byte raw rigorosi",
    "xchg.err.no_ref_type":         "La voce {sid} non ha un tipo di riferimento supportato",
    "xchg.err.charmap_not_obj":     "CharMap deve essere un oggetto",
    "xchg.err.invalid_key":         "Chiave byte CharMap non valida: {key!r}",
    "xchg.err.key_not_one_byte":    "La chiave CharMap deve identificare un byte: {key!r}",
    "xchg.err.invalid_char":        "Carattere CharMap non valido: {char!r}",
    "xchg.err.conflict_key":        "Chiave CharMap in conflitto: {key!r}",
    "xchg.err.ambiguous_char":      "Carattere CharMap ambiguo: {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF non possono essere esportati come testo visibile",
    "xchg.err.no_sid":              "Ogni voce deve avere uno string_id",
    "xchg.err.dup_sid":             "string_id duplicato nelle voci attive",
    "xchg.err.no_charmap":          "Nessun codice CharMap/font confermato per {font}",
    "xchg.err.outside_repack":      "La voce {sid} è esterna a tutti i blocchi Repack",
    "xchg.err.unknown_fixed_slot":  "Slot fisso sconosciuto per {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR e LF non sono consentiti nelle stringhe importate",
    "xchg.err.unconfirmed_byte":    "Il carattere simile a byte U+{cp:04X} non confermato deve usare \\xNN",
    "xchg.err.trailing_backslash":  "Backslash finale nel testo di scambio",
    "xchg.err.bad_escape":          "Il backslash deve essere scritto come \\\\ o nella forma \\xNN",
    "xchg.err.nul_byte_escape":     "Le sequenze byte NUL, CR e LF non sono consentite",
    "xchg.err.use_visible":         "Il byte 0x{byte:02X} deve usare la sua rappresentazione visibile confermata",
    "xchg.err.new_dup_escape":      "Sequenza byte nuova o duplicata \\x{byte:02X}",
    "xchg.err.control_token":       "Token di controllo non valido: {token!r}",
    "xchg.err.token_outside_font":  "Token di controllo esterno al font attivo: {token!r}",
    "xchg.err.unconfirmed_intro":   "È stato introdotto o duplicato il byte non confermato 0x{byte:02X}",
    "xchg.err.not_utf8":            "L'importazione non è UTF-8 valida",
    "xchg.err.invalid_json":        "JSON non valido o troncato: {error}",
    "xchg.err.root_not_obj":        "La radice del documento di scambio deve essere un oggetto",
    "xchg.err.dup_json_key":        "Chiave JSON duplicata: {key!r}",
    "xchg.err.invalid_constant":    "Costante numerica JSON non valida: {value}",
    "xchg.err.schema_mismatch":     "I campi dello schema di primo livello non corrispondono alla versione 1",
    "xchg.err.bad_format":          "Formato di scambio stringhe non supportato",
    "xchg.err.bad_version":         "Versione del formato di scambio stringhe non supportata",
    "xchg.err.no_profile_id":       "profile_id deve essere una stringa non vuota",
    "xchg.err.bad_entry_count":     "entry_count deve essere un intero non negativo",
    "xchg.err.entries_not_array":   "entries deve essere un array",
    "xchg.err.count_mismatch":      "entry_count non corrisponde a entries",
    "xchg.err.entry_schema":        "I campi dello schema della voce non corrispondono alla versione 1",
    "xchg.err.no_string_id":        "string_id deve essere una stringa non vuota",
    "xchg.err.dup_entry_id":        "string_id duplicato: {sid}",
    "xchg.err.invalid_kind":        "Tipo non valido per {sid}",
    "xchg.err.editable_not_bool":   "editable deve essere booleano per {sid}",
    "xchg.err.suffix_not_array":    "suffix_links deve essere un array per {sid}",
    "xchg.err.suffix_link_schema":  "Schema collegamento suffisso non valido per {sid}",
    "xchg.err.suffix_role":         "Ruolo suffisso non valido per {sid}",
    "xchg.err.suffix_peer":         "Peer suffisso non valido per {sid}",
    "xchg.err.suffix_offset":       "Offset suffisso non valido per {sid}",
    "xchg.err.no_font":             "Font non valido per {sid}",
    "xchg.err.invalid_block":       "repack_block non valido per {sid}",
    "xchg.err.invalid_ptr_count":   "{field} non valido per {sid}",
    "xchg.err.invalid_capacity":    "Capacità fissa non valida per {sid}",
    "xchg.err.bad_hash":            "{field} deve essere uno SHA-256 maiuscolo",
    "xchg.err.source_text_str":     "source_text deve essere una stringa per {sid}",
    "xchg.err.translated_type":     "translated_text deve essere null o una stringa per {sid}",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 non corrisponde agli hash delle voci",
    "xchg.err.wrong_profile":       "Profilo errato: {got!r}, previsto {expected!r}",
    "xchg.err.structure_mismatch":  "Impronta della struttura del profilo non corrispondente",
    "xchg.err.charmap_mismatch":    "Impronta CharMap non corrispondente",
    "xchg.err.entry_count_mismatch": "Il numero di voci importate non corrisponde all'EXE caricato",
    "xchg.err.missing_sid":         "string_id mancante: {sid}",
    "xchg.err.unknown_sid":         "string_id sconosciuto: {sid}",
    "xchg.err.manipulated_field":   "{field} manipolato per {sid}",
    "xchg.err.source_hash":         "source_text/hash non corrispondenti per {sid}",
    "xchg.err.token_mismatch":      "Token protetto non corrispondente per {sid}",
    "xchg.err.layout_mismatch":     "Spaziatura/layout protetti non corrispondenti per {sid}",
    "xchg.err.read_only":           "La voce suffisso è in sola lettura: {sid}",
    "xchg.err.fixed_exceeds":       "La stringa fissa {sid} supera {cap} byte",
    "xchg.err.stale_conflict":      "Conflitto con sorgente obsoleta per {sid}",
    "xchg.err.escape_changed":      "Le sequenze byte non confermate sono cambiate per {sid}",
    "xchg.err.unknown_sid_replace": "L'insieme delle sostituzioni contiene uno string_id sconosciuto",
    "xchg.err.replace_not_bytes":   "La sostituzione per {sid} non è composta da byte raw",
    "xchg.err.fixed_exceed_import": "La stringa fissa {sid} supera {max} byte",
    "xchg.err.repack_blocked":      "Repack dell'importazione bloccato: {detail}",
    "xchg.err.suffix_changed":      "L'importazione modificherebbe le relazioni di condivisione dei suffissi",
    "xchg.err.font_validation":     "Convalida font dell'importazione non riuscita: {error}",
    "xchg.err.unknown_repack":      "Errore di convalida Repack sconosciuto",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Metadati filtro non validi alla riga {idx}",
    "sfilter.err.dup_sid":        "string_id mancante o duplicato alla riga {idx}",
    "sfilter.err.invalid_kind":   "Tipo stringa non valido per {sid}: {kind!r}",
    "sfilter.err.invalid_font":   "Font effettivo non valido per {sid}",
    "sfilter.err.invalid_text":   "Testo ricercabile non valido per {sid}",
    "sfilter.err.invalid_preview":"Stato anteprima non valido per {sid}",
    "sfilter.err.invalid_override":"Override stato non valido per {sid}",
    "sfilter.err.query_not_text": "La query di ricerca deve essere testo",
    "sfilter.err.unknown_kind":   "Filtro Tipo sconosciuto: {kind!r}",
    "sfilter.err.font_empty":     "Il filtro Font deve essere un nome non vuoto",
    "sfilter.err.unknown_change": "Filtro Modifica sconosciuto: {change!r}",
    "sfilter.err.unknown_status": "Filtro Stato sconosciuto: {status!r}",
}
