TEXTS_FR = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "Fichier",
    "menu.file.open":               "Ouvrir EXE…",
    "menu.file.save_as":            "Enregistrer sous…",
    "menu.file.quit":               "Quitter",
    "menu.tools":                   "Outils",
    "menu.tools.details":           "Modifications / Détails…",
    "menu.tools.export":            "Exporter les chaînes…",
    "menu.tools.import":            "Importer les chaînes…",
    "menu.tools.autotranslate":     "Traduction automatique",
    "menu.tools.translate_all":     "Traduire toutes les chaînes…",
    "menu.view":                    "Affichage",
    "menu.view.strings":            "Chaînes",
    "menu.view.fonts":              "Éditeur de polices",
    "menu.view.settings":           "Paramètres de l’éditeur",
    "menu.view.language":           "Langue",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "📁 Choisir l’EXE…",
    "header.save_as":               "💾 Enregistrer sous…",
    "header.profile":               "Profil :",
    "header.profile_none":          "—",
    "header.no_file":               "Aucun fichier chargé.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  📝 Chaînes  ",
    "tab.fonts":                    "  🔤 Éditeur de polices  ",
    "tab.settings":                 "  ⚙ Paramètres de l’éditeur  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "🔍 Rechercher :",
    "filter.toggle_closed":         "Filtrer ▸",
    "filter.toggle_open":           "Filtrer ▾",
    "filter.kind":                  "Type :",
    "filter.font":                  "Police :",
    "filter.change":                "Modification :",
    "filter.status":                "État :",
    "filter.reset":                 "❌ Réinitialiser les filtres",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Décalage",
    "col.text":                     "Texte de la chaîne",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Modifier le texte (espaces surlignés) ",
    "edit.apply":                   "✔ Appliquer la modification",
    "edit.stats":                   "Longueur totale : {n} caractères | Espaces initiaux : {lead} | Espaces finaux : {trail}",
    "edit.encoding_blocked":        "Encodage bloqué : {error}",
    "edit.diff_unavailable":        "État des différences indisponible : {error}",
    "edit.fixed_rest":              "Espace fixe restant : {rest}/{cap} octets",
    "edit.block_rest":              "Espace partagé restant de B{block} après toutes les modifications : {rest} octets",
    "edit.block_preview":           "Espace partagé restant de B{block} : aperçu requis",
    "edit.range_info":              "{kind} | {font} | octets {old}→{new} (Δ {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "🌐 Traduction",
    "action.details":               "🔎 Modifications / Détails…",
    "action.export":                "📤 Exporter…",
    "action.import":                "📥 Importer…",
    "action.font_assign":           "Affectation de police…",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Moteur :",
    "tr.from":                      "De :",
    "tr.to":                        "Vers :",
    "tr.all":                       "⚡ Tout traduire",
    "tr.translated":                "Texte traduit :",
    "tr.apply":                     "✔ Appliquer la traduction",
    "tr.translating":               "Traduction en cours...",
    "tr.error":                     "Erreur : {error}",
    "tr.no_changes":                "Aucune modification à appliquer.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Mappage des caractères (CharMap) ",
    "settings.font_group":          " Affectation de police ",
    "settings.font_auto":           "L’affectation est automatique.\nUn autre choix s’applique uniquement à la\nchaîne actuellement sélectionnée.",
    "settings.font_label":          "Police affectée :",
    "settings.hint_group":          " Comportement de l’enregistrement ",
    "settings.hint_text":           "Les affectations CharMap et de police sont enregistrées\nimédiatement et automatiquement.\n\nL’EXE lui-même n’est écrit que via\n« Fichier → Enregistrer sous… ».",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} sur {total} chaînes",
    "status.filter_pending":        "L’affichage du filtre est en attente — appliquez ou annulez d’abord la modification.",
    "status.selection_blocked":     "Changement de sélection bloqué — appliquez ou annulez d’abord la modification.",
    "status.filter_unavailable":    "Filtre indisponible : {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Modification de texte en attente",
    "dlg.pending_font.msg":         "Appliquez ou annulez la modification de texte ou la traduction en attente avant de changer la police associée.\n\nAucune modification n’a été effectuée.",
    "dlg.pending_charmap.msg":      "Appliquez ou annulez la modification de texte ou la traduction en attente avant de changer le CharMap.\n\nAucune modification n’a été effectuée.",
    "dlg.pending_translation.title": "Traduction en attente",
    "dlg.pending_translation.switch": "Appliquer la traduction en attente avant de désactiver la traduction automatique ?\n\nOui = Appliquer, Non = Annuler, Annuler = La garder ouverte",
    "dlg.pending_translation.new":  "Appliquez ou annulez la traduction en attente avant d’en demander une nouvelle.\n\nAucune modification n’a été effectuée.",
    "dlg.text_blocked.title":       "Modification de texte bloquée",
    "dlg.text_blocked.translation": "Appliquez ou annulez la traduction en attente avant d’appliquer la modification du texte.\n\nAucune modification n’a été effectuée.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "TRADUIRE TOUT",
    "dlg.translate_all.none":       "Aucune chaîne chargée.",
    "dlg.translate_all.confirm":    "Traduire automatiquement les {n} chaînes avec « {engine} » ?",
    "dlg.translate_all.window":     "Traduction de TOUTES...",
    "dlg.translate_all.progress":   "{current}/{total} : {text}",
    "dlg.translate_all.blocked":    "TRADUCTION DE TOUT bloquée",
    "dlg.translate_all.unchanged":  "Aucun texte n’a été modifié. L’EXE n’a pas été recompacté et reste inchangé.",
    "dlg.translate_all.nochange":   "Aucun texte ni aucune donnée de l’EXE n’a été modifié.\n\n{detail}",
    "dlg.translate_all.done":       "Terminé",
    "dlg.translate_all.summary":    "Terminé : {translated} traduites, {unchanged} inchangées, {blank} vides.",
    "dlg.translate_all.suffix":     "\n{n} entrées de groupe de suffixes ignorées en toute sécurité.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Exportation bloquée",
    "dlg.export.failed":            "Échec de l’exportation",
    "dlg.export.partial":           "Aucun fichier d’exportation partiel n’a été écrit.\n\n{error}",
    "dlg.export.done":              "Exportation terminée",
    "dlg.export.done_msg":          "{n} chaînes exportées.\n\n{path}",
    "dlg.export.status":            "{n} chaînes exportées vers {file}.",
    "fd.export":                    "Exporter les chaînes",
    "dlg.import.blocked":           "Importation bloquée",
    "dlg.import.nochange":          "L’état de l’éditeur n’a pas été modifié.\n\n{error}",
    "dlg.import.done":              "Importation terminée",
    "dlg.import.none":              "Profil : {profile}\nChaînes modifiées : 0\n\nL’état de l’éditeur n’a pas été modifié.",
    "dlg.import.confirm":           "Profil : {profile}\nChaînes à modifier : {n}\n\nAppliquer complètement la transaction d’importation validée ?",
    "dlg.import.title":             "Importer les chaînes",
    "dlg.import.done_msg":          "Profil : {profile}\nChaînes modifiées : {n}\n\nL’EXE n’a pas été enregistré automatiquement.",
    "dlg.import.status":            "{n} chaînes importées.",
    "fd.import":                    "Importer les chaînes",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "Modifications / Aperçu — {profile}",
    "dlg.preview.warn":             "Aperçu",
    "dlg.preview.load_first":       "Chargez d’abord un exécutable pris en charge.",
    "dlg.preview.failed":           "Échec de l’aperçu",
    "dlg.preview.close":            "Fermer",
    "preview.tab.summary":          "Résumé",
    "preview.tab.strings":          "Chaînes",
    "preview.tab.blocks":           "Blocs",
    "preview.tab.pointers":         "Pointeurs",
    "preview.tab.fonts":            "Polices",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Ouvrir l’exécutable",
    "fd.save_exe":                  "Enregistrer l’exécutable sous",
    "dlg.load.failed":              "Échec du chargement",
    "dlg.load.failed_msg":          "Le nouvel EXE n’a pas été chargé. L’état précédent de l’éditeur est inchangé.\n\n{error}",
    "dlg.load.unsupported_status":  "Exécutable non pris en charge. La modification et l’enregistrement sont désactivés.",
    "dlg.load.unsupported_label":   "NON PRIS EN CHARGE",
    "dlg.load.font_failed":         "Échec de l’initialisation de la police. L’enregistrement est bloqué.",
    "dlg.load.integrity_status":    "Échec de la vérification d’intégrité : {error}",
    "dlg.load.integrity_title":     "Échec de la vérification d’intégrité",
    "dlg.load.integrity_msg":       "Les modifications peuvent être inspectées, mais Repack et Enregistrer sont bloqués.\n\n{errors}",
    "dlg.unsaved.title":            "Modifications non enregistrées",
    "dlg.unsaved.load":             "L’EXE actuel contient des modifications non enregistrées ou en attente.\n\nLes annuler et charger un autre fichier ?",
    "dlg.unsaved.close":            "L’EXE actuel contient des modifications non enregistrées ou en attente.\n\nLes annuler et fermer l’éditeur ?",
    "dlg.save.unsupported":         "Non pris en charge",
    "dlg.save.unsupported_msg":     "Chargez un exécutable pris en charge avant d’enregistrer.",
    "dlg.save.blocked":             "Enregistrement bloqué",
    "dlg.save.verify":              "Impossible de vérifier la source chargée : {error}",
    "dlg.save.external":            "Le fichier source chargé a été modifié en dehors de l’éditeur. Il n’a pas été écrasé.",
    "dlg.save.done":                "Enregistrement terminé",
    "dlg.save.noop":                "Le fichier original est déjà identique octet par octet et inchangé.",
    "dlg.save.overwrite_title":     "Écraser l’original chargé",
    "dlg.save.overwrite_msg":       "Remplacer l’original chargé par l’EXE modifié ?\n\nUne sauvegarde identique octet par octet sera d’abord créée.",
    "dlg.save.failed":              "Échec de l’enregistrement",
    "dlg.save.failed_msg":          "Aucun fichier cible partiel n’a été écrit.\n\n{error}",
    "dlg.save.done_msg":            "Exécutable enregistré dans :\n{path}{backup}",
    "dlg.save.backup":              "\nSauvegarde : {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "Une validation Repack réussie est requise.",
    "block.font_invalid":           "Échec de la validation de la police.",
    "block.font_pending":           "Appliquez ou annulez les modifications de police en attente avant d’enregistrer.",
    "block.text_pending":           "Appliquez ou annulez la modification de texte en attente avant d’enregistrer.",
    "block.generic":                "L’enregistrement est actuellement bloqué.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Police :",
    "font.apply":                   "Appliquer les modifications",
    "font.load_first":              "Chargez d’abord un EXE.",
    "font.characters":              " Caractères ",
    "font.matrix":                  " Matrice de pixels (cliquer/glisser) ",
    "font.props":                   " Propriétés ",
    "font.width":                   "Largeur (px) :",
    "font.tools":                   " Outils ",
    "font.copy":                    "📋 Copier",
    "font.paste":                   "📌 Coller",
    "font.clear":                   "🧹 Effacer",
    "font.invert":                  "🔄 Inverser",
    "font.file":                    " Fichier ",
    "font.import":                  "📥 Importer",
    "font.export":                  "📤 Exporter",
    "font.edit_charmap":            "Modifier le mappage des caractères…",
    "font.charmap_title":           "Mappage des caractères",
    "font.charmap_title_for":       "Mappage des caractères de {font} :",
    "font.remove":                  "✖ Supprimer",
    "font.blocked_title":           "Opération sur la police bloquée",
    "font.blocked_status":          "✖ Opération sur la police bloquée : {error}",
    "font.no_profile":              "Aucun profil de police pour « {profile} ».",
    "font.summary":                 "{font}  •  {chars} caractères  •  {unique} glyphes uniques",
    "font.pending_title":           "Modifications de police en attente",
    "font.pending_msg":             "Appliquer les modifications en attente à {font} avant de changer ?\n\nOui = Appliquer, Non = Annuler, Annuler = Rester",
    "font.no_data":                 "Aucune donnée",
    "font.no_data_msg":             "Chargez un EXE et sélectionnez d’abord une police.",
    "font.no_exe_msg":              "Chargez d’abord un fichier EXE.",
    "font.fd_export":               "Exporter la police",
    "font.fd_import":               "Importer la police ({font})",
    "font.export_error":            "Erreur d’exportation",
    "font.exported":                "✔ {font} exporté → {file}",
    "font.imported":                "✔ {n} glyphes importés de {file} dans {font}",
    "font.written":                 "✔ {n} glyphes écrits dans les données EXE  ({font})",
    "font.written_title":           "Police écrite",
    "font.written_msg":             "{n} glyphes uniques modifiés dans les données EXE.\nUtilisez « Enregistrer sous... » dans la barre supérieure pour enregistrer le fichier.",
    "font.no_selection":            "Aucune sélection",
    "font.no_selection_msg":        "Sélectionnez d’abord un caractère.",
    "font.empty_clipboard":         "Presse-papiers vide",
    "font.empty_clipboard_msg":     "Copiez d’abord un caractère (Ctrl+C).",
    "font.copied":                  "✓ 0x{code:02X} « {char} » copié dans le presse-papiers",
    "font.pasted":                  "✓ Collé dans 0x{code:02X} « {char} »",
    "font.alias":                   "⚠ Alias de 0x{code:02X} (« {char} »)\nModifier ce glyphe modifie également l’original.",
    "font.invalid_entry":           "Entrée CharMap non valide",
    "font.invalid_entry_msg":       "Saisissez un caractère Unicode.",
    "font.invalid_byte":            "Octet CharMap non valide",
    # font_editor internal (non-GUI) messages
    "font.err.live_unavailable":    "Aucun état de police pris en charge n’est chargé",
    "font.err.buffer_unavailable":  "Le tampon EXE actif n’est pas disponible",
    "font.err.import_failed":       "Échec de l’importation sans modification : {error}",
    "font.err.apply_failed":        "Échec de l’application ; les données actives n’ont pas été modifiées : {error}",
    "font.err.paste_rejected":      "Collage refusé sans modification : {error}",
    "font.err.initial_load":        "La police initiale n’a pas pu être chargée",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Configuration",
    "utils.cfg.damaged":            "La configuration existante est endommagée et n’a pas été remplacée.\nLes modifications de configuration restent bloquées jusqu’à sa réparation ou sa suppression.\n\n{reason}",
    "utils.cfg.locked":             "Les modifications de configuration ne sont pas enregistrées tant que la configuration existante est endommagée.\n\n{reason}",
    "utils.cfg.save_failed":        "Impossible d’enregistrer la configuration : {error}",

    # ── build_exe.py ──────────────────────────────────────────────────────────
    "build.err.no_entry":           "Point d’entrée manquant : {path}",
    "build.err.no_config":          "Source de configuration manquante : {path}",
    "build.err.no_icon":            "Ressource d’icône manquante : {path}",
    "build.err.pyi_failed":         "PyInstaller a échoué avec le code de sortie {code}",
    "build.err.no_exe":             "L’exécutable attendu n’a pas été produit : {path}",
    "build.err.config_mismatch":    "La configuration de release n’est pas identique octet par octet à la source",
    "build.err.key_nonempty":       "deepl_key.txt doit être vide",
    "build.step.config":            "[1/6] source de configuration  {hash}  {size} o",
    "build.step.icon":              "      source de l’icône    {hash}  {size} o",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] compilé  {hash}  {size} o",
    "build.step.removed_obsolete":  "      release remplacée supprimée : {name}",
    "build.step.release_exe":       "[4/6] exe de release -> {path}",
    "build.step.config_verified":   "[5/6] configuration de release vérifiée  {hash}",
    "build.step.key_file":          "[6/6] deepl_key.txt de release  0 o",
    "build.step.release_header":    "\nRelease :",

    # ── translator.py ─────────────────────────────────────────────────────────
    "tr.err.markers_changed":       "Les marqueurs de traduction protégés ont changé (manquants={missing}, inattendus={unexpected})",
    "tr.err.marker_count":          "Le nombre de marqueurs protégés a changé : {marker}",
    "tr.err.marker_unrestored":     "Un marqueur de traduction non restauré subsiste",
    "tr.err.no_text":               "Le traducteur n’a renvoyé aucun texte",
    "tr.err.lingva_unreachable":    "Tous les serveurs sont inaccessibles (403/503). Essayez Google Translate ou MyMemory.",
    "tr.err.mymemory":              "Erreur MyMemory {status} : {detail}",
    "tr.err.deepl_no_key":          "Clé DeepL introuvable.\nInscrivez-vous gratuitement sur https://www.deepl.com/pro#developer\nPuis enregistrez la clé dans deepl_key.txt.",
    "tr.err.argos_not_installed":   "Argos Translate n’est pas installé.\nExécutez : pip install argostranslate\net téléchargez les packs de langues.",
    "tr.err.argos_no_package":      "Le paquet Argos « {src}→{tgt} » n’est pas installé.\nTéléchargez-le avec argostranslate.package.",
    "tr.err.argos_no_translation":  "Aucune traduction Argos disponible pour {src}→{tgt}.",

    # ── charmap.py ───────────────────────────────────────────────────────────
    "charmap.err.invalid_key":      "Clé d’octet CharMap non valide : {key}",
    "charmap.err.key_not_one_byte": "La clé CharMap doit identifier un octet : {key}",
    "charmap.err.value_not_char":   "La valeur CharMap doit être un seul caractère : {value}",
    "charmap.err.ambiguous":        "Caractère CharMap ambigu : {char}",
    "charmap.err.outside_font":     "L’octet 0x{byte:02X} pour {char!r} est hors de la police active",
    "charmap.err.no_codepoint":     "Le caractère U+{cp:04X} à la position {pos} n’a aucune entrée CharMap",
    "charmap.err.conflict":         "Le caractère {char!r} à la position {pos} est en conflit avec le glyphe {glyph!r}",

    # ── font_safety.py ───────────────────────────────────────────────────────
    "fsafe.err.invalid_width":      "Largeur de glyphe non valide : {width!r}",
    "fsafe.err.unknown_font":       "Police inconnue : {font}",
    "fsafe.err.incomplete_desc":    "Description de police incomplète pour {font}",
    "fsafe.err.unsupported_type":   "Type de police non pris en charge pour {font}",
    "fsafe.err.invalid_row_count":  "Nombre de lignes/pointeurs non valide pour {font}",
    "fsafe.err.ptr_table_outside":  "Table des pointeurs hors de l’EXE pour {font}",
    "fsafe.err.ptr_table_size":     "Taille de la table des pointeurs incohérente pour {font} : {got} octets pour {ptrs} pointeurs",
    "fsafe.err.glyph_range":        "Plage de glyphes hors de l’EXE ou chevauchant la table des pointeurs pour {font}",
    "fsafe.err.ptr_target":         "Le pointeur de glyphe {idx} pour {font} pointe vers {addr:#x}, hors de {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "Le premier glyphe de {font} ne commence pas à glyph_start",
    "fsafe.err.slot_invalid":       "Emplacement de glyphe non valide/chevauché à {addr:#x} dans {font}",
    "fsafe.err.dynamic_uneven":     "L’emplacement de glyphe dynamique à {addr:#x} a une disposition de lignes irrégulière",
    "fsafe.err.dynamic_capacity":   "L’emplacement de glyphe dynamique à {addr:#x} a une capacité non prise en charge de {cap}",
    "fsafe.err.width_exceeds_slot": "La largeur du glyphe {width} à {addr:#x} dépasse la capacité de l’emplacement {max}",
    "fsafe.err.fixed_size":         "L’emplacement de glyphe fixe à {addr:#x} a une taille {got}, attendue {expected}",
    "fsafe.err.fixed_width":        "La largeur du glyphe fixe {width} à {addr:#x} est invalide",
    "fsafe.err.glyph_exceeds_slot": "Les données du glyphe à {addr:#x} dépassent son emplacement physique",
    "fsafe.err.model_char_count":   "Le modèle de police contient {got} caractères, {expected} attendus",
    "fsafe.err.invalid_char_idx":   "Index de caractère non valide {idx}",
    "fsafe.err.no_glyph_obj":       "Le caractère {idx} n’a aucun objet glyphe",
    "fsafe.err.invalid_glyph_off":  "Le caractère {idx} a un décalage de glyphe non valide",
    "fsafe.err.alias_not_shared":   "Les alias à {addr:#x} ne partagent pas un objet glyphe canonique unique",
    "fsafe.err.alias_meta":         "Métadonnées d’alias incohérentes pour le caractère {idx}",
    "fsafe.err.glyph_start":        "Le modèle de police ne commence pas à glyph_start",
    "fsafe.err.slot_boundary":      "Limite d’emplacement incohérente à {addr:#x}",
    "fsafe.err.slot_outside_exe":   "L’emplacement à {addr:#x} est hors de l’EXE",
    "fsafe.err.dynamic_cap_meta":   "Capacité d’emplacement dynamique non valide à {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "Capacité enregistrée incohérente à {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "Largeur/classe de ligne dépassant l’emplacement à {addr:#x}",
    "fsafe.err.fixed_slot":         "Emplacement fixe non valide à {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "Capacité fixe enregistrée incohérente à {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Largeur fixe non valide à {addr:#x}",
    "fsafe.err.bitmap_value":       "Valeur bitmap hors de la classe de ligne à {addr:#x}",
    "fsafe.err.serial_exceeds":     "La sérialisation du glyphe dépasse l’emplacement à {addr:#x}",
    "fsafe.err.bpr_conversion":     "Conversion octets-par-ligne non prise en charge",
    "fsafe.err.width_not_int":      "La largeur doit être un entier",
    "fsafe.err.width_exceeds_max":  "La largeur {width} dépasse cet emplacement de glyphe (max {max})",
    "fsafe.err.fixed_width_range":  "La largeur FLOW/MICRO doit rester entre 1 et 8",
    "fsafe.err.clipboard_invalid":  "Le presse-papiers ne contient pas de glyphe valide",
    "fsafe.err.height_mismatch":    "Hauteur de glyphe incompatible : source {src}, cible {tgt}",
    "fsafe.err.clip_type_invalid":  "Le type de police du presse-papiers est invalide",
    "fsafe.err.clip_bpr_invalid":   "La classe de ligne du presse-papiers est invalide",
    "fsafe.err.clip_fixed_width":   "La largeur fixe du presse-papiers n’est pas valide",
    "fsafe.err.clip_bitmap":        "La bitmap du presse-papiers est invalide",
    "fsafe.err.target_too_wide":    "Le glyphe est plus large qu’une cible FLOW/MICRO",
    "fsafe.err.paste_exceeds_slot": "La largeur du glyphe {width} dépasse la capacité de l’emplacement cible {max}",
    "fsafe.err.write_exceeds":      "L’écriture du glyphe à {addr:#x} dépasse son emplacement",
    "fsafe.err.ptr_alias_struct":   "Le modèle de police ne correspond plus à la structure des pointeurs/alias de l’EXE",
    "fsafe.err.changed_outside":    "La sérialisation de la police a modifié des octets hors des emplacements de glyphes",
    "fsafe.err.readback_mismatch":  "Incohérence de relecture de la police à {addr:#x}",
    "fsafe.err.import_truncated":   "L’importation est tronquée avant le glyphe {idx}",
    "fsafe.err.import_width":       "La largeur importée {width} dépasse la capacité {cap} du glyphe {idx}",
    "fsafe.err.import_fixed_width": "La largeur fixe importée {width} est invalide au glyphe {idx}",
    "fsafe.err.import_trunc_body":  "L’importation est tronquée à l’intérieur du glyphe {idx}",
    "fsafe.err.import_trailing":    "L’importation contient {n} octets finaux inattendus",
    "fsafe.err.no_dir":             "Le répertoire cible n’existe pas : {dir}",
    "fsafe.err.short_write":        "Écriture partielle : {written} sur {total} octets",
    "fsafe.err.readback_tmp":       "Incohérence de relecture du fichier temporaire",
    "fsafe.err.no_backup_src":      "Impossible de sauvegarder un fichier original manquant",
    "fsafe.err.buffers_differ":     "Les tampons de police diffèrent sur {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "Les tampons de police n’ont pas le même état avant commit",

    # ── diff_preview.py ───────────────────────────────────────────────────────
    "diff.err.no_raw":              "L’entrée {sid} ne contient pas d’octets bruts stricts",
    "diff.err.no_ref_type":         "L’entrée {sid} n’a aucun type de référence",
    "diff.err.range_outside":       "La plage de référence pour {label} est hors de l’EXE",
    "diff.err.not_nul_term":        "La chaîne de référence {label} n’est pas terminée par NUL",
    "diff.err.ptr_normal_outside":  "Source de pointeur normal hors de l’EXE : {addr:#x}",
    "diff.err.ptr_code_outside":    "Source de pointeur de code hors de l’EXE : {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Type de pointeur inconnu : {kind}",
    "diff.err.ptr_base_mismatch":   "Le pointeur {addr:#x} a pour base {got}, attendu {expected}",
    "diff.err.ptr_outside_ranges":  "Le pointeur {addr:#x} cible une zone hors des plages Repack : {target:#x}",
    "diff.err.no_unique_sid":       "Les entrées actuelles n’ont pas de string_id uniques",
    "diff.err.fixed_id":            "string_id fixe non valide : {sid}",
    "diff.err.unknown_fixed_slot":  "Emplacement de référence fixe inconnu : {sid}",
    "diff.err.ambiguous_targets":   "Les sources de pointeur de référence pour {sid} ont {n} cibles",
    "diff.err.baseline_failed":     "Échec de la reconstruction de la référence : {detail}",
    "diff.err.repack_mutated":      "La simulation Repack de référence a modifié ses entrées",
    "diff.err.range_cross_end":     "La chaîne recompactée dépasse la fin du bloc à {addr:#x}",
    "diff.err.pending_preflight":   "string_id en attente inconnu : {sid}",
    "diff.err.pending_not_bytes":   "Le remplacement en attente pour {sid} n’est pas constitué d’octets bruts",
    "diff.err.fixed_exceed":        "La chaîne fixe {sid} dépasse {max} octets ({got} octets)",
    "diff.err.dup_normal_ptr":      "Source de pointeur normal dupliquée : {addr:#x}",
    "diff.err.dup_code_ptr":        "Source de pointeur de code dupliquée : {addr:#x}",
    "diff.err.alias_not_canonical": "Les alias à {addr:#x} ne sont pas canoniques",
    "diff.err.ptr_table_changed":   "La table des pointeurs de police a changé pour {font}",
    "diff.err.glyph_set_changed":   "L’ensemble physique des glyphes a changé pour {font}",
    "diff.err.alias_set_changed":   "L’ensemble des alias a changé à {addr:#x} dans {font}",
    "diff.err.meta_reconstruct":    "Les métadonnées de la chaîne n’ont pas pu être reconstruites : {error}",
    "diff.err.no_font_key":         "Le modèle de police en attente n’a aucune clé de police",
    "diff.err.font_preview_failed": "Échec de l’aperçu de la police en attente : {error}",
    "diff.err.sid_sets_differ":     "Les ensembles de string_id de référence et actuels diffèrent",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "L’aperçu a modifié baseline_data",
    "diff.err.mutated_current":     "L’aperçu a modifié current_data",
    "diff.err.mutated_entries":     "L’aperçu a modifié les entrées actuelles",
    "diff.err.mutated_font":        "L’aperçu a modifié le modèle de police en attente",
    "diff.err.baseline_repack":     "Échec du Repack de référence : {detail}",
    "diff.err.unknown_baseline":    "Échec de validation de référence inconnu",
    "diff.err.unknown_baseline_repack": "Échec du Repack de référence inconnu",

    # ── repack_validator.py ───────────────────────────────────────────────────
    "repack.err.encoding":          "La chaîne {sid} contient un caractère qui ne peut pas être encodé",
    "repack.err.site_outside":      "Site de relocalisation hors du fichier : {addr:#x}",
    "repack.err.missing_code_ptrs": "Pointeurs de code manquants : {addrs}",
    "repack.err.extra_code_ptrs":   "Pointeurs de code inattendus : {addrs}",
    "repack.err.mismatched_ptrs":   "Pointeurs de code incohérents : {addrs}",
    "repack.err.no_sid":            "L’entrée à {addr:#x} n’a aucun string_id",
    "repack.err.dup_sid":           "string_id dupliqué : {sid}",
    "repack.err.fixed_has_ptrs":    "L’entrée fixe {sid} possède des pointeurs de manière inattendue",
    "repack.err.dup_normal_src":    "Source de pointeur normal dupliquée : {addr:#x}",
    "repack.err.uninv_normal_src":  "Source de pointeur normal non inventoriée : {addr:#x}",
    "repack.err.normal_target":     "Le pointeur normal {src:#x} cible {expected:#x}, tandis que l’entrée est {actual:#x}",
    "repack.err.dup_code_src":      "Source de pointeur de code dupliquée : {addr:#x}",
    "repack.err.uninv_code_src":    "Source de pointeur de code non inventoriée : {addr:#x}",
    "repack.err.code_target":       "Le pointeur de code {src:#x} cible {expected:#x}, tandis que l’entrée est {actual:#x}",
    "repack.err.unowned_normal":    "{n} pointeurs normaux liés à une relocalisation ne sont pas attribués",
    "repack.err.unowned_code":      "{n} pointeurs de code liés à une relocalisation ne sont pas attribués",
    "repack.err.unknown_fixed":     "Chaîne fixe inconnue : {addr:#x}",
    "repack.err.fixed_slot_size":   "La chaîne fixe dépasse l’emplacement à {addr:#x}",
    "repack.err.fixed_mismatch":    "Octets de chaîne fixe incohérents à {addr:#x}",
    "repack.err.outside_ranges":    "Chaîne hors des plages valides : {addr:#x}",
    "repack.err.crosses_range":     "La chaîne dépasse la fin de la plage : {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "Octets/NUL de chaîne incohérents à {addr:#x}",
    "repack.err.illegal_overlap":   "Chevauchement illégal de chaînes : {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Octets occupés inconnus dans la plage {idx} : {n} octets, premier {addr:#x}",
    "repack.err.entry_outside":     "Entrée hors des plages valides : {addr:#x}",
    "repack.err.range_overflow":    "Dépassement de la plage {idx} : {required} > {total}",
    "repack.err.ptr_value_range":   "Valeur de pointeur hors de la plage 16 bits : {value:#x}",
    "repack.err.normal_src_file":   "Source de pointeur normal hors du fichier : {addr:#x}",
    "repack.err.code_src_file":     "Source de pointeur de code hors du fichier : {addr:#x}",
    "repack.err.suffix_chain":      "Chaîne de partage de suffixes non résolue",
    "repack.err.file_size_changed": "La taille du fichier a changé",
    "repack.err.extra_diffs":       "Octets modifiés inattendus hors des plages/offsets de pointeurs : {n}, premier {addr:#x}",

    # ── string_exchange.py ────────────────────────────────────────────────────
    "xchg.err.not_serialisable":    "La valeur ne peut pas être canonisée : {error}",
    "xchg.err.not_raw_text":        "L’entrée {sid} ne contient pas de texte en octets bruts stricts",
    "xchg.err.no_ref_type":         "L’entrée {sid} n’a aucun type de référence pris en charge",
    "xchg.err.charmap_not_obj":     "CharMap doit être un objet",
    "xchg.err.invalid_key":         "Clé d’octet CharMap non valide : {key!r}",
    "xchg.err.key_not_one_byte":    "La clé CharMap doit identifier un octet : {key!r}",
    "xchg.err.invalid_char":        "Caractère CharMap non valide : {char!r}",
    "xchg.err.conflict_key":        "Clé CharMap en conflit : {key!r}",
    "xchg.err.ambiguous_char":      "Caractère CharMap ambigu : {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF ne peuvent pas être exportés comme texte visible",
    "xchg.err.no_sid":              "Chaque entrée doit avoir un string_id",
    "xchg.err.dup_sid":             "string_id dupliqué dans les entrées actives",
    "xchg.err.no_charmap":          "Aucun code CharMap/police confirmé pour {font}",
    "xchg.err.outside_repack":      "L’entrée {sid} est en dehors de tous les blocs Repack",
    "xchg.err.unknown_fixed_slot":  "Emplacement fixe inconnu pour {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR et LF ne sont pas autorisés dans les chaînes importées",
    "xchg.err.unconfirmed_byte":    "Le caractère ressemblant à un octet U+{cp:04X} non confirmé doit utiliser \\xNN",
    "xchg.err.trailing_backslash":  "Backslash final dans le texte d’échange",
    "xchg.err.bad_escape":          "Le backslash doit être échappé en \\\\ ou sous la forme \\xNN",
    "xchg.err.nul_byte_escape":     "Les échappements d’octets NUL, CR et LF ne sont pas autorisés",
    "xchg.err.use_visible":         "L’octet 0x{byte:02X} doit utiliser sa représentation visible confirmée",
    "xchg.err.new_dup_escape":      "Échappement d’octet nouveau ou dupliqué \\x{byte:02X}",
    "xchg.err.control_token":       "Jeton de contrôle non valide : {token!r}",
    "xchg.err.token_outside_font":  "Jeton de contrôle hors de la police active : {token!r}",
    "xchg.err.unconfirmed_intro":   "L’octet non confirmé 0x{byte:02X} a été introduit ou dupliqué",
    "xchg.err.not_utf8":            "L’importation n’est pas un UTF-8 valide",
    "xchg.err.invalid_json":        "JSON non valide ou tronqué : {error}",
    "xchg.err.root_not_obj":        "La racine du document d’échange doit être un objet",
    "xchg.err.dup_json_key":        "Clé JSON dupliquée : {key!r}",
    "xchg.err.invalid_constant":    "Constante numérique JSON non valide : {value}",
    "xchg.err.schema_mismatch":     "Les champs du schéma de niveau supérieur ne correspondent pas à la version 1",
    "xchg.err.bad_format":          "Format d’échange de chaînes non pris en charge",
    "xchg.err.bad_version":         "Version du format d’échange de chaînes non prise en charge",
    "xchg.err.no_profile_id":       "profile_id doit être une chaîne non vide",
    "xchg.err.bad_entry_count":     "entry_count doit être un entier non négatif",
    "xchg.err.entries_not_array":   "entries doit être un tableau",
    "xchg.err.count_mismatch":      "entry_count ne correspond pas à entries",
    "xchg.err.entry_schema":        "Les champs du schéma de l’entrée ne correspondent pas à la version 1",
    "xchg.err.no_string_id":        "string_id doit être une chaîne non vide",
    "xchg.err.dup_entry_id":        "string_id dupliqué : {sid}",
    "xchg.err.invalid_kind":        "Type non valide pour {sid}",
    "xchg.err.editable_not_bool":   "editable doit être booléen pour {sid}",
    "xchg.err.suffix_not_array":    "suffix_links doit être un tableau pour {sid}",
    "xchg.err.suffix_link_schema":  "Schéma de lien de suffixe non valide pour {sid}",
    "xchg.err.suffix_role":         "Rôle de suffixe non valide pour {sid}",
    "xchg.err.suffix_peer":         "Pair de suffixe non valide pour {sid}",
    "xchg.err.suffix_offset":       "Offset de suffixe non valide pour {sid}",
    "xchg.err.no_font":             "Police non valide pour {sid}",
    "xchg.err.invalid_block":       "repack_block non valide pour {sid}",
    "xchg.err.invalid_ptr_count":   "{field} non valide pour {sid}",
    "xchg.err.invalid_capacity":    "Capacité fixe non valide pour {sid}",
    "xchg.err.bad_hash":            "{field} doit être un SHA-256 en majuscules",
    "xchg.err.source_text_str":     "source_text doit être une chaîne pour {sid}",
    "xchg.err.translated_type":     "translated_text doit être null ou une chaîne pour {sid}",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 ne correspond pas aux hachages des entrées",
    "xchg.err.wrong_profile":       "Mauvais profil : {got!r}, attendu {expected!r}",
    "xchg.err.structure_mismatch":  "Empreinte de structure du profil incohérente",
    "xchg.err.charmap_mismatch":    "Empreinte CharMap incohérente",
    "xchg.err.entry_count_mismatch": "Le nombre d’entrées importées ne correspond pas à l’EXE chargé",
    "xchg.err.missing_sid":         "string_id manquant : {sid}",
    "xchg.err.unknown_sid":         "string_id inconnu : {sid}",
    "xchg.err.manipulated_field":   "{field} manipulé pour {sid}",
    "xchg.err.source_hash":         "source_text/hash incohérents pour {sid}",
    "xchg.err.token_mismatch":      "Jeton protégé incohérent pour {sid}",
    "xchg.err.layout_mismatch":     "Espacement/mise en page protégés incohérents pour {sid}",
    "xchg.err.read_only":           "L’entrée de suffixe est en lecture seule : {sid}",
    "xchg.err.fixed_exceeds":       "La chaîne fixe {sid} dépasse {cap} octets",
    "xchg.err.stale_conflict":      "Conflit avec une source obsolète pour {sid}",
    "xchg.err.escape_changed":      "Les échappements d’octets non confirmés ont changé pour {sid}",
    "xchg.err.unknown_sid_replace": "L’ensemble des remplacements contient un string_id inconnu",
    "xchg.err.replace_not_bytes":   "Le remplacement pour {sid} n’est pas constitué d’octets bruts",
    "xchg.err.fixed_exceed_import": "La chaîne fixe {sid} dépasse {max} octets",
    "xchg.err.repack_blocked":      "Repack de l’importation bloqué : {detail}",
    "xchg.err.suffix_changed":      "L’importation modifierait les relations de partage des suffixes",
    "xchg.err.font_validation":     "Échec de validation de la police d’importation : {error}",
    "xchg.err.unknown_repack":      "Échec de validation Repack inconnu",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Métadonnées de filtre non valides à la ligne {idx}",
    "sfilter.err.dup_sid":        "string_id manquant ou dupliqué à la ligne {idx}",
    "sfilter.err.invalid_kind":   "Type de chaîne non valide pour {sid} : {kind!r}",
    "sfilter.err.invalid_font":   "Police effective non valide pour {sid}",
    "sfilter.err.invalid_text":   "Texte recherchable non valide pour {sid}",
    "sfilter.err.invalid_preview":"État d’aperçu non valide pour {sid}",
    "sfilter.err.invalid_override":"Surcharge d’état non valide pour {sid}",
    "sfilter.err.query_not_text": "La requête de recherche doit être du texte",
    "sfilter.err.unknown_kind":   "Filtre Type inconnu : {kind!r}",
    "sfilter.err.font_empty":     "Le filtre Police doit être un nom non vide",
    "sfilter.err.unknown_change": "Filtre Modification inconnu : {change!r}",
    "sfilter.err.unknown_status": "Filtre État inconnu : {status!r}",
}
