TEXTS_DE = {

    # ── main_editor.py — menu ─────────────────────────────────────────────────
    "menu.file":                    "Datei",
    "menu.file.open":               "EXE \u00f6ffnen\u2026",
    "menu.file.save_as":            "Speichern unter\u2026",
    "menu.file.quit":               "Beenden",
    "menu.tools":                   "Werkzeuge",
    "menu.tools.details":           "\u00c4nderungen / Details\u2026",
    "menu.tools.export":            "Strings exportieren\u2026",
    "menu.tools.import":            "Strings importieren\u2026",
    "menu.tools.autotranslate":     "Automatische \u00dcbersetzung",
    "menu.tools.translate_all":     "Alle Strings \u00fcbersetzen\u2026",
    "menu.view":                    "Ansicht",
    "menu.view.strings":            "Strings",
    "menu.view.fonts":              "Font-Editor",
    "menu.view.settings":           "Editor-Einstellungen",
    "menu.view.language":           "Sprache",

    # ── main_editor.py — header ───────────────────────────────────────────────
    "header.choose_exe":            "\U0001f4c1 EXE ausw\u00e4hlen\u2026",
    "header.save_as":               "\U0001f4be Speichern unter\u2026",
    "header.profile":               "Profil:",
    "header.profile_none":          "\u2014",
    "header.no_file":               "Keine Datei geladen.",

    # ── main_editor.py — tabs ─────────────────────────────────────────────────
    "tab.strings":                  "  \U0001f4dd Strings  ",
    "tab.fonts":                    "  \U0001f524 Font-Editor  ",
    "tab.settings":                 "  \u2699 Editor-Einstellungen  ",

    # ── main_editor.py — search / filter ──────────────────────────────────────
    "filter.search":                "\U0001f50d Suche:",
    "filter.toggle_closed":         "Filter \u25b8",
    "filter.toggle_open":           "Filter \u25be",
    "filter.kind":                  "Art:",
    "filter.font":                  "Font:",
    "filter.change":                "\u00c4nderung:",
    "filter.status":                "Status:",
    "filter.reset":                 "\u274c Filter zur\u00fccksetzen",

    # ── main_editor.py — string list ──────────────────────────────────────────
    "col.num":                      "#",
    "col.offset":                   "Offset",
    "col.text":                     "Stringtext",

    # ── main_editor.py — editor ───────────────────────────────────────────────
    "edit.frame":                   " Text bearbeiten (Leerzeichen hervorgehoben) ",
    "edit.apply":                   "\u2714 \u00c4nderung \u00fcbernehmen",
    "edit.stats":                   "Gesamtl\u00e4nge: {n} Zeichen | F\u00fchrende Leerzeichen: {lead} | Nachfolgende Leerzeichen: {trail}",
    "edit.encoding_blocked":        "Kodierung blockiert: {error}",
    "edit.diff_unavailable":        "Diff-Status nicht verf\u00fcgbar: {error}",
    "edit.fixed_rest":              "Fixed-Rest: {rest}/{cap} Bytes",
    "edit.block_rest":              "Gemeinsamer Rest B{block} nach allen \u00c4nderungen: {rest} Bytes",
    "edit.block_preview":           "B{block} gemeinsamer Rest: Vorschau erforderlich",
    "edit.range_info":              "{kind} | {font} | Bytes {old}\u2192{new} (\u0394 {delta}) | {status} | {suffix}",

    # ── main_editor.py — action bar ───────────────────────────────────────────
    "action.translation":           "\U0001f310 \u00dcbersetzung",
    "action.details":               "\U0001f50e \u00c4nderungen / Details\u2026",
    "action.export":                "\U0001f4e4 Exportieren\u2026",
    "action.import":                "\U0001f4e5 Importieren\u2026",
    "action.font_assign":           "Font-Zuordnung\u2026",

    # ── main_editor.py — translation panel ────────────────────────────────────
    "tr.engine":                    "Engine:",
    "tr.from":                      "Von:",
    "tr.to":                        "Nach:",
    "tr.all":                       "\u26a1 Alle \u00fcbersetzen",
    "tr.translated":                "\u00dcbersetzter Text:",
    "tr.apply":                     "\u2714 \u00dcbersetzung \u00fcbernehmen",
    "tr.translating":               "\u00dcbersetze...",
    "tr.error":                     "Fehler: {error}",
    "tr.no_changes":                "Keine \u00c4nderung zu \u00fcbernehmen.",

    # ── main_editor.py — settings ─────────────────────────────────────────────
    "settings.charmap_group":       " Zeichenzuordnung (CharMap) ",
    "settings.font_group":          " Font-Zuordnung ",
    "settings.font_auto":           "Die Zuordnung erfolgt automatisch.\nEine abweichende Auswahl gilt nur f\u00fcr den\naktuell gew\u00e4hlten String.",
    "settings.font_label":          "Zugeordneter Font:",
    "settings.hint_group":          " Speicherverhalten ",
    "settings.hint_text":           "CharMap- und Font-Zuordnungen werden sofort\nund automatisch gespeichert.\n\nDie EXE selbst wird erst \u00fcber\n\u201eDatei \u2192 Speichern unter\u2026\u201c geschrieben.",

    # ── main_editor.py — counter / status ─────────────────────────────────────
    "status.counter":               "{shown} von {total} Strings",
    "status.filter_pending":        "Filteransicht wartet \u2014 \u00c4nderung zuerst \u00fcbernehmen oder verwerfen.",
    "status.selection_blocked":     "Auswahlwechsel blockiert \u2014 \u00c4nderung zuerst \u00fcbernehmen oder verwerfen.",
    "status.filter_unavailable":    "Filter nicht verf\u00fcgbar: {error}",

    # ── main_editor.py — guards / dialogs ─────────────────────────────────────
    "dlg.pending_text.title":       "Nicht \u00fcbernommene Text\u00e4nderung",
    "dlg.pending_font.msg":         "\u00dcbernehmen oder verwerfen Sie die offene Text- oder \u00dcbersetzungs\u00e4nderung, bevor Sie den zugeordneten Font wechseln.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.pending_charmap.msg":      "\u00dcbernehmen oder verwerfen Sie die offene Text- oder \u00dcbersetzungs\u00e4nderung, bevor Sie die CharMap \u00e4ndern.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.pending_translation.title": "Nicht \u00fcbernommene \u00dcbersetzung",
    "dlg.pending_translation.switch": "Offene \u00dcbersetzung \u00fcbernehmen, bevor die automatische \u00dcbersetzung ausgeschaltet wird?\n\nJa = \u00dcbernehmen, Nein = Verwerfen, Abbrechen = Offen lassen",
    "dlg.pending_translation.new":  "\u00dcbernehmen oder verwerfen Sie die offene \u00dcbersetzung, bevor Sie eine neue anfordern.\n\nEs wurde nichts ge\u00e4ndert.",
    "dlg.text_blocked.title":       "Text\u00e4nderung blockiert",
    "dlg.text_blocked.translation": "\u00dcbernehmen oder verwerfen Sie die offene \u00dcbersetzung, bevor Sie die Text\u00e4nderung \u00fcbernehmen.\n\nEs wurde nichts ge\u00e4ndert.",

    # ── main_editor.py — translate all ────────────────────────────────────────
    "dlg.translate_all.title":      "Alle \u00fcbersetzen",
    "dlg.translate_all.none":       "Kein String geladen.",
    "dlg.translate_all.confirm":    "Alle {n} Strings automatisch mit '{engine}' \u00fcbersetzen?",
    "dlg.translate_all.window":     "\u00dcbersetze alle...",
    "dlg.translate_all.progress":   "{current}/{total}: {text}",
    "dlg.translate_all.blocked":    "Alle \u00fcbersetzen blockiert",
    "dlg.translate_all.unchanged":  "Kein Text ge\u00e4ndert. Die EXE wurde nicht neu gepackt und bleibt unver\u00e4ndert.",
    "dlg.translate_all.nochange":   "Es wurden weder Text noch EXE-Daten ge\u00e4ndert.\n\n{detail}",
    "dlg.translate_all.done":       "Abgeschlossen",
    "dlg.translate_all.summary":    "Fertig: {translated} \u00fcbersetzt, {unchanged} unver\u00e4ndert, {blank} leer.",
    "dlg.translate_all.suffix":     "\n{n} Suffix-Gruppeneintr\u00e4ge sicher \u00fcbersprungen.",

    # ── main_editor.py — export / import ──────────────────────────────────────
    "dlg.export.blocked":           "Export blockiert",
    "dlg.export.failed":            "Export fehlgeschlagen",
    "dlg.export.partial":           "Es wurde keine unvollst\u00e4ndige Exportdatei geschrieben.\n\n{error}",
    "dlg.export.done":              "Export abgeschlossen",
    "dlg.export.done_msg":          "{n} Strings exportiert.\n\n{path}",
    "dlg.export.status":            "{n} Strings nach {file} exportiert.",
    "fd.export":                    "Strings exportieren",
    "dlg.import.blocked":           "Import blockiert",
    "dlg.import.nochange":          "Es wurde kein Editorzustand ge\u00e4ndert.\n\n{error}",
    "dlg.import.done":              "Import abgeschlossen",
    "dlg.import.none":              "Profil: {profile}\nGe\u00e4nderte Strings: 0\n\nEs wurde kein Editorzustand ge\u00e4ndert.",
    "dlg.import.confirm":           "Profil: {profile}\nZu \u00e4ndernde Strings: {n}\n\nDie vollst\u00e4ndige validierte Import-Transaktion anwenden?",
    "dlg.import.title":             "Strings importieren",
    "dlg.import.done_msg":          "Profil: {profile}\nGe\u00e4nderte Strings: {n}\n\nDie EXE wurde nicht automatisch gespeichert.",
    "dlg.import.status":            "{n} Strings importiert.",
    "fd.import":                    "Strings importieren",

    # ── main_editor.py — preview dialog ───────────────────────────────────────
    "dlg.preview.title":            "\u00c4nderungen / Vorschau \u2014 {profile}",
    "dlg.preview.warn":             "Vorschau",
    "dlg.preview.load_first":       "Laden Sie zuerst eine unterst\u00fctzte EXE.",
    "dlg.preview.failed":           "Vorschau fehlgeschlagen",
    "dlg.preview.close":            "Schlie\u00dfen",
    "preview.tab.summary":          "\u00dcbersicht",
    "preview.tab.strings":          "Strings",
    "preview.tab.blocks":           "Bl\u00f6cke",
    "preview.tab.pointers":         "Pointer",
    "preview.tab.fonts":            "Fonts",

    # ── main_editor.py — load / save ──────────────────────────────────────────
    "fd.open_exe":                  "Ausf\u00fchrbare Datei \u00f6ffnen",
    "fd.save_exe":                  "Ausf\u00fchrbare Datei speichern unter",
    "dlg.load.failed":              "Laden fehlgeschlagen",
    "dlg.load.failed_msg":          "Die neue EXE wurde nicht geladen. Der bisherige Editorzustand bleibt unver\u00e4ndert.\n\n{error}",
    "dlg.load.unsupported_status":  "Nicht unterst\u00fctzte EXE. Bearbeiten und Speichern sind deaktiviert.",
    "dlg.load.unsupported_label":   "UNSUPPORTED",
    "dlg.load.font_failed":         "Font-Initialisierung fehlgeschlagen. Speichern ist blockiert.",
    "dlg.load.integrity_status":    "Integrit\u00e4tspr\u00fcfung fehlgeschlagen: {error}",
    "dlg.load.integrity_title":     "Integrit\u00e4tspr\u00fcfung fehlgeschlagen",
    "dlg.load.integrity_msg":       "Die Bearbeitung kann gepr\u00fcft werden, Repack und Speichern sind aber blockiert.\n\n{errors}",
    "dlg.unsaved.title":            "Nicht gespeicherte \u00c4nderungen",
    "dlg.unsaved.load":             "Die aktuelle EXE hat nicht gespeicherte oder offene \u00c4nderungen.\n\nVerwerfen und eine andere Datei laden?",
    "dlg.unsaved.close":            "Die aktuelle EXE hat nicht gespeicherte oder offene \u00c4nderungen.\n\nVerwerfen und den Editor schlie\u00dfen?",
    "dlg.save.unsupported":         "Nicht unterst\u00fctzt",
    "dlg.save.unsupported_msg":     "Laden Sie vor dem Speichern eine unterst\u00fctzte EXE.",
    "dlg.save.blocked":             "Speichern blockiert",
    "dlg.save.verify":              "Die geladene Quelle konnte nicht gepr\u00fcft werden: {error}",
    "dlg.save.external":            "Die geladene Quelldatei wurde au\u00dferhalb des Editors ge\u00e4ndert. Sie wurde nicht \u00fcberschrieben.",
    "dlg.save.done":                "Speichern abgeschlossen",
    "dlg.save.noop":                "Die Originaldatei ist bereits byteidentisch und unver\u00e4ndert.",
    "dlg.save.overwrite_title":     "Geladenes Original \u00fcberschreiben",
    "dlg.save.overwrite_msg":       "Das geladene Original durch die bearbeitete EXE ersetzen?\n\nZuvor wird eine byteidentische Sicherung angelegt.",
    "dlg.save.failed":              "Speichern fehlgeschlagen",
    "dlg.save.failed_msg":          "Es wurde keine unvollst\u00e4ndige Zieldatei geschrieben.\n\n{error}",
    "dlg.save.done_msg":            "EXE gespeichert unter:\n{path}{backup}",
    "dlg.save.backup":              "\nSicherung: {path}",

    # ── main_editor.py — block reasons ────────────────────────────────────────
    "block.repack":                 "Eine erfolgreiche Repack-Validierung ist erforderlich.",
    "block.font_invalid":           "Die Fontvalidierung ist fehlgeschlagen.",
    "block.font_pending":           "\u00dcbernehmen oder verwerfen Sie die offenen Font\u00e4nderungen vor dem Speichern.",
    "block.text_pending":           "\u00dcbernehmen oder verwerfen Sie die offene Text\u00e4nderung vor dem Speichern.",
    "block.generic":                "Speichern ist derzeit blockiert.",

    # ── font_editor.py ────────────────────────────────────────────────────────
    "font.font":                    "Font:",
    "font.apply":                   "\u00c4nderungen \u00fcbernehmen",
    "font.load_first":              "Laden Sie zuerst eine EXE.",
    "font.characters":              " Zeichen ",
    "font.matrix":                  " Pixelmatrix (Klicken/Ziehen) ",
    "font.props":                   " Eigenschaften ",
    "font.width":                   "Breite (px):",
    "font.tools":                   " Werkzeuge ",
    "font.copy":                    "\U0001f4cb Kopieren",
    "font.paste":                   "\U0001f4cc Einf\u00fcgen",
    "font.clear":                   "\U0001f9f9 Leeren",
    "font.invert":                  "\U0001f504 Invertieren",
    "font.file":                    " Datei ",
    "font.import":                  "\U0001f4e5 Import",
    "font.export":                  "\U0001f4e4 Export",
    "font.edit_charmap":            "Zeichenzuordnung bearbeiten\u2026",
    "font.charmap_title":           "Zeichenzuordnung",
    "font.charmap_title_for":       "Zeichenzuordnung {font}:",
    "font.remove":                  "\u2716 Entfernen",
    "font.blocked_title":           "Fontoperation blockiert",
    "font.blocked_status":          "\u2716 Fontoperation blockiert: {error}",
    "font.no_profile":              "Kein Fontprofil f\u00fcr '{profile}'.",
    "font.summary":                 "{font}  \u2022  {chars} Zeichen  \u2022  {unique} eindeutige Glyphen",
    "font.pending_title":           "Offene Font\u00e4nderungen",
    "font.pending_msg":             "Offene \u00c4nderungen an {font} vor dem Wechsel \u00fcbernehmen?\n\nJa = \u00dcbernehmen, Nein = Verwerfen, Abbrechen = Bleiben",
    "font.no_data":                 "Keine Daten",
    "font.no_data_msg":             "Laden Sie eine EXE und w\u00e4hlen Sie zuerst einen Font.",
    "font.no_exe_msg":              "Laden Sie zuerst eine EXE-Datei.",
    "font.fd_export":               "Font exportieren",
    "font.fd_import":               "Font importieren ({font})",
    "font.export_error":            "Exportfehler",
    "font.exported":                "\u2714 {font} exportiert \u2192 {file}",
    "font.imported":                "\u2714 {n} Glyphen aus {file} in {font} importiert",
    "font.written":                 "\u2714 {n} Glyphen in die EXE-Daten geschrieben  ({font})",
    "font.written_title":           "Font geschrieben",
    "font.written_msg":             "{n} eindeutige Glyphen in die EXE-Daten gepatcht.\nZum Speichern \u201eSpeichern unter\u2026\u201c in der Kopfzeile verwenden.",
    "font.no_selection":            "Keine Auswahl",
    "font.no_selection_msg":        "W\u00e4hlen Sie zuerst ein Zeichen.",
    "font.empty_clipboard":         "Zwischenablage leer",
    "font.empty_clipboard_msg":     "Kopieren Sie zuerst ein Zeichen (Strg+C).",
    "font.copied":                  "\u2713 0x{code:02X} '{char}' in die Zwischenablage kopiert",
    "font.pasted":                  "\u2713 Eingef\u00fcgt in 0x{code:02X} '{char}'",
    "font.alias":                   "\u26a0 Alias von 0x{code:02X} ('{char}')\nDas Bearbeiten \u00e4ndert auch das Original.",
    "font.invalid_entry":           "Ung\u00fcltiger CharMap-Eintrag",
    "font.invalid_entry_msg":       "Geben Sie ein Unicode-Zeichen ein.",
    "font.invalid_byte":            "Ung\u00fcltiges CharMap-Byte",
    # font_editor internal messages
    "font.err.live_unavailable":    "Kein unterst\u00fctzter Font-Zustand geladen",
    "font.err.buffer_unavailable":  "Live-EXE-Puffer nicht verf\u00fcgbar",
    "font.err.import_failed":       "Import ohne \u00c4nderungen fehlgeschlagen: {error}",
    "font.err.apply_failed":        "\u00dcbernehmen fehlgeschlagen; Live-Daten wurden nicht ge\u00e4ndert: {error}",
    "font.err.paste_rejected":      "Einf\u00fcgen ohne \u00c4nderungen abgelehnt: {error}",
    "font.err.initial_load":        "Initialer Font konnte nicht geladen werden",

    # ── utils.py ─────────────────────────────────────────────────────────────
    "utils.cfg.title":              "Konfiguration",
    "utils.cfg.damaged":            "Die vorhandene Konfiguration ist besch\u00e4digt und wurde nicht ersetzt.\n\u00c4nderungen an der Konfiguration sind gesperrt, bis sie repariert oder entfernt wird.\n\n{reason}",
    "utils.cfg.locked":             "Konfiguration\u00e4nderungen werden nicht gespeichert, solange die vorhandene Konfiguration besch\u00e4digt ist.\n\n{reason}",
    "utils.cfg.save_failed":        "Konfiguration konnte nicht gespeichert werden: {error}",

    # ── build_exe.py ─────────────────────────────────────────────────────────
    "build.err.no_entry":           "Einstiegspunkt fehlt: {path}",
    "build.err.no_config":          "Konfigurationsquelle fehlt: {path}",
    "build.err.no_icon":            "Icon-Ressource fehlt: {path}",
    "build.err.pyi_failed":         "PyInstaller fehlgeschlagen mit Exit-Code {code}",
    "build.err.no_exe":             "Erwartete ausf\u00fchr bare Datei nicht erstellt: {path}",
    "build.err.config_mismatch":    "Release-Konfiguration ist nicht byteidentisch mit der Quelle",
    "build.err.key_nonempty":       "deepl_key.txt muss leer sein",
    "build.step.config":            "[1/6] Konfigurationsquelle  {hash}  {size} B",
    "build.step.icon":              "      Icon-Quelle            {hash}  {size} B",
    "build.step.command":           "[2/6] {cmd}",
    "build.step.built":             "[3/6] Erstellt  {hash}  {size} B",
    "build.step.removed_obsolete":  "      Veraltetes Release entfernt: {name}",
    "build.step.release_exe":       "[4/6] Release-EXE -> {path}",
    "build.step.config_verified":   "[5/6] Release-Konfiguration verifiziert  {hash}",
    "build.step.key_file":          "[6/6] Release deepl_key.txt  0 B",
    "build.step.release_header":    "\nRelease:",

    # ── translator.py ────────────────────────────────────────────────────────
    "tr.err.markers_changed":       "Gesch\u00fctzte \u00dcbersetzungsmarkierungen wurden ge\u00e4ndert (fehlend={missing}, unerwartet={unexpected})",
    "tr.err.marker_count":          "Anzahl gesch\u00fctzter Markierungen ge\u00e4ndert: {marker}",
    "tr.err.marker_unrestored":     "Nicht wiederhergestellte \u00dcbersetzungsmarkierung verbleibt",
    "tr.err.no_text":               "\u00dcbersetzer hat keinen Text zur\u00fcckgegeben",
    "tr.err.lingva_unreachable":    "Alle Server nicht erreichbar (403/503). Versuchen Sie Google Translate oder MyMemory.",
    "tr.err.mymemory":              "MyMemory-Fehler {status}: {detail}",
    "tr.err.deepl_no_key":          "DeepL-Schl\u00fcssel nicht gefunden.\nKostenlos registrieren unter https://www.deepl.com/pro#developer\nDann den Schl\u00fcssel in deepl_key.txt speichern.",
    "tr.err.argos_not_installed":   "Argos Translate nicht installiert.\nAusf\u00fchren: pip install argostranslate\nund die Sprachpakete herunterladen.",
    "tr.err.argos_no_package":      "Argos-Paket '{src}\u2192{tgt}' nicht installiert.\nLaden Sie es mit argostranslate.package herunter.",
    "tr.err.argos_no_translation":  "Keine Argos-\u00dcbersetzung verf\u00fcgbar f\u00fcr {src}\u2192{tgt}.",

    # ── charmap.py ───────────────────────────────────────────────────────────
    "charmap.err.invalid_key":      "Ung\u00fcltiger CharMap-Byte-Schl\u00fcssel: {key}",
    "charmap.err.key_not_one_byte": "CharMap-Schl\u00fcssel muss genau ein Byte identifizieren: {key}",
    "charmap.err.value_not_char":   "CharMap-Wert muss ein einzelnes Zeichen sein: {value}",
    "charmap.err.ambiguous":        "Mehrdeutiges CharMap-Zeichen: {char}",
    "charmap.err.outside_font":     "Byte 0x{byte:02X} f\u00fcr {char!r} liegt au\u00dferhalb des aktiven Fonts",
    "charmap.err.no_codepoint":     "Zeichen U+{cp:04X} an Position {pos} hat keinen CharMap-Eintrag",
    "charmap.err.conflict":         "Zeichen {char!r} an Position {pos} steht im Konflikt mit Glyphe {glyph!r}",

    # ── font_safety.py ───────────────────────────────────────────────────────
    "fsafe.err.invalid_width":      "Ung\u00fcltige Glyphenbreite: {width!r}",
    "fsafe.err.unknown_font":       "Unbekannter Font: {font}",
    "fsafe.err.incomplete_desc":    "Unvollst\u00e4ndige Font-Beschreibung f\u00fcr {font}",
    "fsafe.err.unsupported_type":   "Nicht unterst\u00fctzter Font-Typ f\u00fcr {font}",
    "fsafe.err.invalid_row_count":  "Ung\u00fcltige Zeilen-/Pointer-Anzahl f\u00fcr {font}",
    "fsafe.err.ptr_table_outside":  "Pointer-Tabelle au\u00dferhalb der EXE f\u00fcr {font}",
    "fsafe.err.ptr_table_size":     "Gr\u00f6\u00dfenabweichung der Pointer-Tabelle f\u00fcr {font}: {got} Bytes f\u00fcr {ptrs} Pointer",
    "fsafe.err.glyph_range":        "Glyphenbereich au\u00dferhalb der EXE oder \u00fcberschneidet Pointer-Tabelle f\u00fcr {font}",
    "fsafe.err.ptr_target":         "Glyphen-Pointer {idx} f\u00fcr {font} zielt auf {addr:#x} au\u00dferhalb von {start:#x}-{end:#x}",
    "fsafe.err.first_glyph":        "Erste Glyphe f\u00fcr {font} beginnt nicht bei glyph_start",
    "fsafe.err.slot_invalid":       "Ung\u00fcltiger/\u00fcberlappender Glyphen-Slot bei {addr:#x} in {font}",
    "fsafe.err.dynamic_uneven":     "Dynamischer Glyphen-Slot bei {addr:#x} hat ein ungleichm\u00e4\u00dfiges Zeilen-Layout",
    "fsafe.err.dynamic_capacity":   "Dynamischer Glyphen-Slot bei {addr:#x} hat nicht unterst\u00fctzte Kapazit\u00e4t {cap}",
    "fsafe.err.width_exceeds_slot": "Glyphenbreite {width} bei {addr:#x} \u00fcberschreitet Slot-Kapazit\u00e4t {max}",
    "fsafe.err.fixed_size":         "Fester Glyphen-Slot bei {addr:#x} hat Gr\u00f6\u00dfe {got}, erwartet {expected}",
    "fsafe.err.fixed_width":        "Feste Glyphenbreite {width} bei {addr:#x} ist ung\u00fcltig",
    "fsafe.err.glyph_exceeds_slot": "Glyphendaten bei {addr:#x} \u00fcberschreiten ihren physischen Slot",
    "fsafe.err.model_char_count":   "Font-Modell hat {got} Zeichen, erwartet wurden {expected}",
    "fsafe.err.invalid_char_idx":   "Ung\u00fcltiger Zeichenindex {idx}",
    "fsafe.err.no_glyph_obj":       "Zeichen {idx} hat kein Glyphenobjekt",
    "fsafe.err.invalid_glyph_off":  "Zeichen {idx} hat einen ung\u00fcltigen Glyphen-Offset",
    "fsafe.err.alias_not_shared":   "Aliase bei {addr:#x} teilen kein kanonisches Glyphenobjekt",
    "fsafe.err.alias_meta":         "Alias-Metadatenabweichung f\u00fcr Zeichen {idx}",
    "fsafe.err.glyph_start":        "Font-Modell beginnt nicht bei glyph_start",
    "fsafe.err.slot_boundary":      "Slot-Grenzenabweichung bei {addr:#x}",
    "fsafe.err.slot_outside_exe":   "Slot bei {addr:#x} liegt au\u00dferhalb der EXE",
    "fsafe.err.dynamic_cap_meta":   "Ung\u00fcltige dynamische Slot-Kapazit\u00e4t bei {addr:#x}",
    "fsafe.err.dynamic_cap_stored": "Gespeicherte Kapazit\u00e4tsabweichung bei {addr:#x}",
    "fsafe.err.dynamic_width_bpr":  "Breite/Zeilenklasse \u00fcberschreitet Slot bei {addr:#x}",
    "fsafe.err.fixed_slot":         "Ung\u00fcltiger fester Slot bei {addr:#x}",
    "fsafe.err.fixed_cap_stored":   "Gespeicherte feste Kapazit\u00e4tsabweichung bei {addr:#x}",
    "fsafe.err.fixed_width_bpr":    "Ung\u00fcltige feste Breite bei {addr:#x}",
    "fsafe.err.bitmap_value":       "Bitmap-Wert au\u00dferhalb der Zeilenklasse bei {addr:#x}",
    "fsafe.err.serial_exceeds":     "Glyphen-Serialisierung \u00fcberschreitet Slot bei {addr:#x}",
    "fsafe.err.bpr_conversion":     "Nicht unterst\u00fctzte Bytes-pro-Zeile-Konvertierung",
    "fsafe.err.width_not_int":      "Breite muss eine Ganzzahl sein",
    "fsafe.err.width_exceeds_max":  "Breite {width} \u00fcberschreitet diesen Glyphen-Slot (Max {max})",
    "fsafe.err.fixed_width_range":  "FLOW/MICRO-Breite muss zwischen 1 und 8 liegen",
    "fsafe.err.clipboard_invalid":  "Zwischenablage enth\u00e4lt keine g\u00fcltige Glyphe",
    "fsafe.err.height_mismatch":    "Inkompatible Glyphenh\u00f6he: Quelle {src}, Ziel {tgt}",
    "fsafe.err.clip_type_invalid":  "Font-Typ der Zwischenablage ist ung\u00fcltig",
    "fsafe.err.clip_bpr_invalid":   "Zeilenklasse der Zwischenablage ist ung\u00fcltig",
    "fsafe.err.clip_fixed_width":   "Feste Breite der Zwischenablage ist ung\u00fcltig",
    "fsafe.err.clip_bitmap":        "Bitmap der Zwischenablage ist ung\u00fcltig",
    "fsafe.err.target_too_wide":    "Glyphe ist breiter als ein FLOW/MICRO-Ziel",
    "fsafe.err.paste_exceeds_slot": "Glyphenbreite {width} \u00fcberschreitet Ziel-Slot-Kapazit\u00e4t {max}",
    "fsafe.err.write_exceeds":      "Glyphen-Schreibvorgang bei {addr:#x} \u00fcberschreitet seinen Slot",
    "fsafe.err.ptr_alias_struct":   "Font-Modell entspricht nicht mehr der Pointer/Alias-Struktur der EXE",
    "fsafe.err.changed_outside":    "Font-Serialisierung hat Bytes au\u00dferhalb der Glyphen-Slots ge\u00e4ndert",
    "fsafe.err.readback_mismatch":  "Font-R\u00fcckleseabweichung bei {addr:#x}",
    "fsafe.err.import_truncated":   "Import vor Glyphe {idx} abgeschnitten",
    "fsafe.err.import_width":       "Importierte Breite {width} \u00fcberschreitet Kapazit\u00e4t {cap} von Glyphe {idx}",
    "fsafe.err.import_fixed_width": "Importierte feste Breite {width} ist ung\u00fcltig bei Glyphe {idx}",
    "fsafe.err.import_trunc_body":  "Import innerhalb von Glyphe {idx} abgeschnitten",
    "fsafe.err.import_trailing":    "Import hat {n} unerwartete nachfolgende Bytes",
    "fsafe.err.no_dir":             "Zielverzeichnis existiert nicht: {dir}",
    "fsafe.err.short_write":        "Unvollst\u00e4ndiger Schreibvorgang: {written} von {total} Bytes",
    "fsafe.err.readback_tmp":       "R\u00fcckleseabweichung der tempor\u00e4ren Datei",
    "fsafe.err.no_backup_src":      "Fehlende Originaldatei kann nicht gesichert werden",
    "fsafe.err.buffers_differ":     "Font-Puffer unterscheiden sich in {start:#x}-{end:#x}",
    "fsafe.err.buffers_state":      "Font-Puffer haben nicht denselben Pre-Commit-Zustand",

    # ── diff_preview.py ──────────────────────────────────────────────────────
    "diff.err.no_raw":              "Eintrag {sid} enth\u00e4lt keine strikten Rohbytes",
    "diff.err.no_ref_type":         "Eintrag {sid} hat keinen Referenztyp",
    "diff.err.range_outside":       "Baseline-Bereich f\u00fcr {label} liegt au\u00dferhalb der EXE",
    "diff.err.not_nul_term":        "Baseline-String {label} ist nicht NUL-terminiert",
    "diff.err.ptr_normal_outside":  "Normale Pointer-Quelle au\u00dferhalb der EXE: {addr:#x}",
    "diff.err.ptr_code_outside":    "Code-Pointer-Quelle au\u00dferhalb der EXE: {addr:#x}",
    "diff.err.ptr_unknown_kind":    "Unbekannte Pointer-Art: {kind}",
    "diff.err.ptr_base_mismatch":   "Pointer {addr:#x} hat Basis {got}, erwartet wurde {expected}",
    "diff.err.ptr_outside_ranges":  "Pointer {addr:#x} zielt au\u00dferhalb der Repack-Bereiche: {target:#x}",
    "diff.err.no_unique_sid":       "Aktuelle Eintr\u00e4ge haben keine eindeutigen string_ids",
    "diff.err.fixed_id":            "Ung\u00fcltige feste string_id: {sid}",
    "diff.err.unknown_fixed_slot":  "Unbekannter fester Baseline-Slot: {sid}",
    "diff.err.ambiguous_targets":   "Baseline-Pointer-Quellen f\u00fcr {sid} haben {n} Ziele",
    "diff.err.baseline_failed":     "Baseline-Rekonstruktion fehlgeschlagen: {detail}",
    "diff.err.repack_mutated":      "Autoritativer Repack-Trockenlauf hat seine Eingaben ver\u00e4ndert",
    "diff.err.range_cross_end":     "Neu gepackter String \u00fcberschreitet Blockende bei {addr:#x}",
    "diff.err.pending_preflight":   "Unbekannte ausstehende string_id: {sid}",
    "diff.err.pending_not_bytes":   "Ausstehender Ersatz f\u00fcr {sid} sind keine Rohbytes",
    "diff.err.fixed_exceed":        "Fester String {sid} \u00fcberschreitet {max} Bytes ({got} Bytes)",
    "diff.err.dup_normal_ptr":      "Doppelte normale Pointer-Quelle: {addr:#x}",
    "diff.err.dup_code_ptr":        "Doppelte Code-Pointer-Quelle: {addr:#x}",
    "diff.err.alias_not_canonical": "Aliase bei {addr:#x} sind nicht kanonisch",
    "diff.err.ptr_table_changed":   "Font-Pointer-Tabelle ge\u00e4ndert f\u00fcr {font}",
    "diff.err.glyph_set_changed":   "Physisches Glyphen-Set ge\u00e4ndert f\u00fcr {font}",
    "diff.err.alias_set_changed":   "Alias-Set ge\u00e4ndert bei {addr:#x} in {font}",
    "diff.err.meta_reconstruct":    "String-Metadaten konnten nicht rekonstruiert werden: {error}",
    "diff.err.no_font_key":         "Ausstehendes Font-Modell hat keinen Font-Schl\u00fcssel",
    "diff.err.font_preview_failed": "Ausstehende Font-Vorschau fehlgeschlagen: {error}",
    "diff.err.sid_sets_differ":     "Baseline/Aktuelle string_id-Sets unterscheiden sich",
    "diff.err.ptr_diffs":           "{error}",
    "diff.err.mutated_baseline":    "Vorschau hat baseline_data ver\u00e4ndert",
    "diff.err.mutated_current":     "Vorschau hat current_data ver\u00e4ndert",
    "diff.err.mutated_entries":     "Vorschau hat aktuelle Eintr\u00e4ge ver\u00e4ndert",
    "diff.err.mutated_font":        "Vorschau hat das ausstehende Font-Modell ver\u00e4ndert",
    "diff.err.baseline_repack":     "Baseline-Repack fehlgeschlagen: {detail}",
    "diff.err.unknown_baseline":    "Unbekannter Baseline-Validierungsfehler",
    "diff.err.unknown_baseline_repack": "Unbekannter Baseline-Repack-Fehler",

    # ── repack_validator.py ──────────────────────────────────────────────────
    "repack.err.encoding":          "String {sid} enth\u00e4lt ein Zeichen, das nicht kodiert werden kann",
    "repack.err.site_outside":      "Relokationsstelle au\u00dferhalb der Datei: {addr:#x}",
    "repack.err.missing_code_ptrs": "Fehlende Code-Pointer: {addrs}",
    "repack.err.extra_code_ptrs":   "Unerwartete Code-Pointer: {addrs}",
    "repack.err.mismatched_ptrs":   "Nicht \u00fcbereinstimmende Code-Pointer: {addrs}",
    "repack.err.no_sid":            "Eintrag bei {addr:#x} hat keine string_id",
    "repack.err.dup_sid":           "Doppelte string_id: {sid}",
    "repack.err.fixed_has_ptrs":    "Fester Eintrag {sid} hat unerwartet Pointer",
    "repack.err.dup_normal_src":    "Doppelte normale Pointer-Quelle: {addr:#x}",
    "repack.err.uninv_normal_src":  "Nicht inventarisierte normale Pointer-Quelle: {addr:#x}",
    "repack.err.normal_target":     "Normaler Pointer {src:#x} zielt auf {expected:#x}, Eintrag ist {actual:#x}",
    "repack.err.dup_code_src":      "Doppelte Code-Pointer-Quelle: {addr:#x}",
    "repack.err.uninv_code_src":    "Nicht inventarisierte Code-Pointer-Quelle: {addr:#x}",
    "repack.err.code_target":       "Code-Pointer {src:#x} zielt auf {expected:#x}, Eintrag ist {actual:#x}",
    "repack.err.unowned_normal":    "{n} relokationsgest\u00fctzte normale Pointer sind nicht zugewiesen",
    "repack.err.unowned_code":      "{n} relokationsgest\u00fctzte Code-Pointer sind nicht zugewiesen",
    "repack.err.unknown_fixed":     "Unbekannter fester String: {addr:#x}",
    "repack.err.fixed_slot_size":   "Fester String \u00fcberschreitet Slot bei {addr:#x}",
    "repack.err.fixed_mismatch":    "Abweichung der festen String-Bytes bei {addr:#x}",
    "repack.err.outside_ranges":    "String au\u00dferhalb g\u00fcltiger Bereiche: {addr:#x}",
    "repack.err.crosses_range":     "String \u00fcberschreitet Bereichsende: {start:#x}-{end:#x}",
    "repack.err.bytes_mismatch":    "String Bytes/NUL Abweichung bei {addr:#x}",
    "repack.err.illegal_overlap":   "Ung\u00fcltige String-\u00dcberlappung: {a_start:#x}-{a_end:#x} / {b_start:#x}-{b_end:#x}",
    "repack.err.unknown_bytes":     "Unbekannte belegte Bytes in Bereich {idx}: {n} Bytes, erste bei {addr:#x}",
    "repack.err.entry_outside":     "Eintrag au\u00dferhalb g\u00fcltiger Bereiche: {addr:#x}",
    "repack.err.range_overflow":    "Bereich {idx} \u00dcberlauf: {required} > {total}",
    "repack.err.ptr_value_range":   "Pointer-Wert au\u00dferhalb des 16-Bit-Bereichs: {value:#x}",
    "repack.err.normal_src_file":   "Normale Pointer-Quelle au\u00dferhalb der Datei: {addr:#x}",
    "repack.err.code_src_file":     "Code-Pointer-Quelle au\u00dferhalb der Datei: {addr:#x}",
    "repack.err.suffix_chain":      "Unaufgel\u00f6ste Suffix-Sharing-Kette",
    "repack.err.file_size_changed": "Dateigr\u00f6\u00dfe ge\u00e4ndert",
    "repack.err.extra_diffs":       "Unerwartet ge\u00e4nderte Bytes au\u00dferhalb der Bereiche/Pointer-Offsets: {n}, erste bei {addr:#x}",

    # ── string_exchange.py ───────────────────────────────────────────────────
    "xchg.err.not_serialisable":    "Wert kann nicht kanonisiert werden: {error}",
    "xchg.err.not_raw_text":        "Eintrag {sid} enth\u00e4lt keinen strikten Rohbyte-Text",
    "xchg.err.no_ref_type":         "Eintrag {sid} hat keinen unterst\u00fctzten Referenztyp",
    "xchg.err.charmap_not_obj":     "CharMap muss ein Objekt sein",
    "xchg.err.invalid_key":         "Ung\u00fcltiger CharMap-Byte-Schl\u00fcssel: {key!r}",
    "xchg.err.key_not_one_byte":    "CharMap-Schl\u00fcssel muss genau ein Byte identifizieren: {key!r}",
    "xchg.err.invalid_char":        "Ung\u00fcltiges CharMap-Zeichen: {char!r}",
    "xchg.err.conflict_key":        "Konfliktierender CharMap-Schl\u00fcssel: {key!r}",
    "xchg.err.ambiguous_char":      "Mehrdeutiges CharMap-Zeichen: {char!r}",
    "xchg.err.nul_cr_lf":          "NUL/CR/LF k\u00f6nnen nicht als sichtbarer Text exportiert werden",
    "xchg.err.no_sid":              "Jeder Eintrag muss eine string_id haben",
    "xchg.err.dup_sid":             "Doppelte string_id in Live-Eintr\u00e4gen",
    "xchg.err.no_charmap":          "Keine best\u00e4tigten CharMap/Font-Codes f\u00fcr {font}",
    "xchg.err.outside_repack":      "Eintrag {sid} liegt au\u00dferhalb aller Repack-Bl\u00f6cke",
    "xchg.err.unknown_fixed_slot":  "Unbekannter fester Slot f\u00fcr {sid}",
    "xchg.err.nul_cr_lf_import":   "NUL, CR und LF sind in importierten Strings nicht erlaubt",
    "xchg.err.unconfirmed_byte":    "Unbest\u00e4tigtes byteartiges Zeichen U+{cp:04X} muss \\xNN verwenden",
    "xchg.err.trailing_backslash":  "Abschlie\u00dfender Backslash im Austauschtext",
    "xchg.err.bad_escape":          "Backslash muss als \\\\ maskiert werden oder die Form \\xNN haben",
    "xchg.err.nul_byte_escape":     "NUL-, CR- und LF-Byte-Escapes sind nicht erlaubt",
    "xchg.err.use_visible":         "Byte 0x{byte:02X} muss seine best\u00e4tigte sichtbare Darstellung verwenden",
    "xchg.err.new_dup_escape":      "Neues oder doppeltes Byte-Escape \\x{byte:02X}",
    "xchg.err.control_token":       "Ung\u00fcltiges Steuer-Token: {token!r}",
    "xchg.err.token_outside_font":  "Steuer-Token au\u00dferhalb des aktiven Fonts: {token!r}",
    "xchg.err.unconfirmed_intro":   "Unbest\u00e4tigtes Byte 0x{byte:02X} wurde eingef\u00fchrt oder verdoppelt",
    "xchg.err.not_utf8":            "Import ist kein g\u00fcltiges UTF-8",
    "xchg.err.invalid_json":        "Ung\u00fcltiges oder abgeschnittenes JSON: {error}",
    "xchg.err.root_not_obj":        "Wurzelelement des Austauschdokuments muss ein Objekt sein",
    "xchg.err.dup_json_key":        "Doppelter JSON-Schl\u00fcssel: {key!r}",
    "xchg.err.invalid_constant":    "Ung\u00fcltige numerische JSON-Konstante: {value}",
    "xchg.err.schema_mismatch":     "Toplevel-Schemafelder entsprechen nicht Version 1",
    "xchg.err.bad_format":          "Nicht unterst\u00fctztes String-Austauschformat",
    "xchg.err.bad_version":         "Nicht unterst\u00fctzte String-Austauschversion",
    "xchg.err.no_profile_id":       "profile_id muss ein nicht-leerer String sein",
    "xchg.err.bad_entry_count":     "entry_count muss eine nicht-negative Ganzzahl sein",
    "xchg.err.entries_not_array":   "entries muss ein Array sein",
    "xchg.err.count_mismatch":      "entry_count stimmt nicht mit entries \u00fcberein",
    "xchg.err.entry_schema":        "Eintrags-Schemafelder entsprechen nicht Version 1",
    "xchg.err.no_string_id":        "string_id muss ein nicht-leerer String sein",
    "xchg.err.dup_entry_id":        "Doppelte string_id: {sid}",
    "xchg.err.invalid_kind":        "Ung\u00fcltige Art f\u00fcr {sid}",
    "xchg.err.editable_not_bool":   "editable muss f\u00fcr {sid} ein Boolscher Wert sein",
    "xchg.err.suffix_not_array":    "suffix_links muss f\u00fcr {sid} ein Array sein",
    "xchg.err.suffix_link_schema":  "Ung\u00fcltiges Suffix-Link-Schema f\u00fcr {sid}",
    "xchg.err.suffix_role":         "Ung\u00fcltige Suffix-Rolle f\u00fcr {sid}",
    "xchg.err.suffix_peer":         "Ung\u00fcltiger Suffix-Peer f\u00fcr {sid}",
    "xchg.err.suffix_offset":       "Ung\u00fcltiger Suffix-Offset f\u00fcr {sid}",
    "xchg.err.no_font":             "Ung\u00fcltiger Font f\u00fcr {sid}",
    "xchg.err.invalid_block":       "Ung\u00fcltiger repack_block f\u00fcr {sid}",
    "xchg.err.invalid_ptr_count":   "Ung\u00fcltiges {field} f\u00fcr {sid}",
    "xchg.err.invalid_capacity":    "Ung\u00fcltige feste Kapazit\u00e4t f\u00fcr {sid}",
    "xchg.err.bad_hash":            "{field} muss ein SHA-256 in Gro\u00dfbuchstaben sein",
    "xchg.err.source_text_str":     "source_text muss ein String f\u00fcr {sid} sein",
    "xchg.err.translated_type":     "translated_text muss null oder ein String f\u00fcr {sid} sein",
    "xchg.err.manifest_mismatch":   "source_manifest_sha256 stimmt nicht mit den Eintrags-Hashes \u00fcberein",
    "xchg.err.wrong_profile":       "Falsches Profil: {got!r}, erwartet {expected!r}",
    "xchg.err.structure_mismatch":  "Profil-Struktur-Fingerabdruck stimmt nicht \u00fcberein",
    "xchg.err.charmap_mismatch":    "CharMap-Fingerabdruck stimmt nicht \u00fcberein",
    "xchg.err.entry_count_mismatch": "Eintragsanzahl des Imports stimmt nicht mit der geladenen EXE \u00fcberein",
    "xchg.err.missing_sid":         "Fehlende string_id: {sid}",
    "xchg.err.unknown_sid":         "Unbekannte string_id: {sid}",
    "xchg.err.manipulated_field":   "Manipuliertes Feld {field} f\u00fcr {sid}",
    "xchg.err.source_hash":         "source_text/Hash-Abweichung f\u00fcr {sid}",
    "xchg.err.token_mismatch":      "Abweichung beim gesch\u00fctzten Token f\u00fcr {sid}",
    "xchg.err.layout_mismatch":     "Abweichung beim gesch\u00fctzten Whitespace/Layout f\u00fcr {sid}",
    "xchg.err.read_only":           "Suffix-Eintrag ist schreibgesch\u00fctzt: {sid}",
    "xchg.err.fixed_exceeds":       "Fester String {sid} \u00fcberschreitet {cap} Bytes",
    "xchg.err.stale_conflict":      "Veralteter Quellkonflikt f\u00fcr {sid}",
    "xchg.err.escape_changed":      "Unbest\u00e4tigte Byte-Escapes wurden f\u00fcr {sid} ge\u00e4ndert",
    "xchg.err.unknown_sid_replace": "Ersatz-Set enth\u00e4lt eine unbekannte string_id",
    "xchg.err.replace_not_bytes":   "Ersatz f\u00fcr {sid} sind keine Rohbytes",
    "xchg.err.fixed_exceed_import": "Fester String {sid} \u00fcberschreitet {max} Bytes",
    "xchg.err.repack_blocked":      "Import-Repack blockiert: {detail}",
    "xchg.err.suffix_changed":      "Import w\u00fcrde Suffix-Sharing-Beziehungen \u00e4ndern",
    "xchg.err.font_validation":     "Import-Fontvalidierung fehlgeschlagen: {error}",
    "xchg.err.unknown_repack":      "Unbekannter Repack-Validierungsfehler",

    # ── search_filter.py ──────────────────────────────────────────────────────
    "sfilter.err.invalid_meta":   "Ung\u00fcltige Filtermetadaten in Zeile {idx}",
    "sfilter.err.dup_sid":        "Fehlende oder doppelte string_id in Zeile {idx}",
    "sfilter.err.invalid_kind":   "Ung\u00fcltige String-Art f\u00fcr {sid}: {kind!r}",
    "sfilter.err.invalid_font":   "Ung\u00fcltiger effektiver Font f\u00fcr {sid}",
    "sfilter.err.invalid_text":   "Ung\u00fcltiger durchsuchbarer Text f\u00fcr {sid}",
    "sfilter.err.invalid_preview":"Ung\u00fcltiger Vorschaustatus f\u00fcr {sid}",
    "sfilter.err.invalid_override":"Ung\u00fcltige Status-\u00dcberschreibung f\u00fcr {sid}",
    "sfilter.err.query_not_text": "Suchanfrage muss Text sein",
    "sfilter.err.unknown_kind":   "Unbekannter Art-Filter: {kind!r}",
    "sfilter.err.font_empty":     "Font-Filter muss ein nicht leerer Name sein",
    "sfilter.err.unknown_change": "Unbekannter \u00c4nderungs-Filter: {change!r}",
    "sfilter.err.unknown_status": "Unbekannter Status-Filter: {status!r}",
}